// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.Prospect" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const ProspectTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	ProspectId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	Prospect: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Project: z.string(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: int
	 */
	SortOrder: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.Prospect" table.
 * This type represents the raw database record without case transforms.
 */
export type ProspectBaseRecord = z.output<typeof ProspectTableBaseSchema>;

/**
 * Read transform for the "dbo.Prospect" table.
 * Maps database fields to app case properties.
 */
export function transformProspectBaseRecord(data: ProspectBaseRecord): {
	prospectId: ProspectBaseRecord["ProspectId"]
	prospect: ProspectBaseRecord["Prospect"]
	description?: ProspectBaseRecord["Description"]
	project: ProspectBaseRecord["Project"]
	activeInd: ProspectBaseRecord["ActiveInd"]
	sortOrder?: ProspectBaseRecord["SortOrder"]
	createdOnDt: ProspectBaseRecord["CreatedOnDt"]
	createdBy: ProspectBaseRecord["CreatedBy"]
	modifiedOnDt?: ProspectBaseRecord["ModifiedOnDt"]
	modifiedBy?: ProspectBaseRecord["ModifiedBy"]
	rv: ProspectBaseRecord["rv"]
} {
	return {
		prospectId: data.ProspectId,
		prospect: data.Prospect,
		description: data.Description,
		project: data.Project,
		activeInd: data.ActiveInd,
		sortOrder: data.SortOrder,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.Prospect" table (after casing transform).
 */
export const ProspectTableSchema = ProspectTableBaseSchema.transform(transformProspectBaseRecord);

/**
 * Base insert/write schema for the "dbo.Prospect" table (no casing transforms).
 */
export const ProspectTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	prospectId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	prospect: z.string().max(30),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(-1).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	project: z.string().max(100),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: int
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.Prospect" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type ProspectInsertBaseRecord = z.output<typeof ProspectTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.Prospect" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type ProspectUpdateBaseRecord = Partial<ProspectInsertBaseRecord>;

/**
 * Insert transform for the "dbo.Prospect" table.
 * Maps app cased properties to database fields.
 */
export function transformProspectInsertBaseRecord(data: ProspectInsertBaseRecord): {
	ProspectId?: ProspectInsertBaseRecord["prospectId"]
	Prospect: ProspectInsertBaseRecord["prospect"]
	Description?: ProspectInsertBaseRecord["description"]
	Project: ProspectInsertBaseRecord["project"]
	ActiveInd?: ProspectInsertBaseRecord["activeInd"]
	SortOrder?: ProspectInsertBaseRecord["sortOrder"]
	CreatedOnDt?: ProspectInsertBaseRecord["createdOnDt"]
	CreatedBy?: ProspectInsertBaseRecord["createdBy"]
	ModifiedOnDt?: ProspectInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: ProspectInsertBaseRecord["modifiedBy"]
	rv: ProspectInsertBaseRecord["rv"]
} {
	return {
		ProspectId: data.prospectId,
		Prospect: data.prospect,
		Description: data.description,
		Project: data.project,
		ActiveInd: data.activeInd,
		SortOrder: data.sortOrder,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.Prospect" table.
 * Maps app cased properties to database fields.
 */
export function transformProspectUpdateBaseRecord(data: ProspectUpdateBaseRecord): {
	ProspectId?: ProspectUpdateBaseRecord["prospectId"]
	Prospect: ProspectUpdateBaseRecord["prospect"]
	Description?: ProspectUpdateBaseRecord["description"]
	Project: ProspectUpdateBaseRecord["project"]
	ActiveInd?: ProspectUpdateBaseRecord["activeInd"]
	SortOrder?: ProspectUpdateBaseRecord["sortOrder"]
	CreatedOnDt?: ProspectUpdateBaseRecord["createdOnDt"]
	CreatedBy?: ProspectUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: ProspectUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: ProspectUpdateBaseRecord["modifiedBy"]
	rv: ProspectUpdateBaseRecord["rv"]
} {
	return {
		ProspectId: data.prospectId,
		Prospect: data.prospect,
		Description: data.description,
		Project: data.project,
		ActiveInd: data.activeInd,
		SortOrder: data.sortOrder,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.Prospect" table (after casing transform).
 */
export const ProspectTableInsertSchema = ProspectTableInsertBaseSchema.transform(transformProspectInsertBaseRecord);

/**
 * Update schema for the "dbo.Prospect" table (after casing transform).
 */
export const ProspectTableUpdateSchema = ProspectTableInsertBaseSchema.partial().transform(transformProspectUpdateBaseRecord);

type TableInsertRecord = z.input<typeof ProspectTableInsertSchema>;
type TableReadRecord = z.output<typeof ProspectTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.Prospect" table.
 */
export interface ProspectRecord {
	prospectId: TableReadRecord["prospectId"]
	prospect: TableReadRecord["prospect"]
	description?: TableReadRecord["description"]
	project: TableReadRecord["project"]
	activeInd: TableReadRecord["activeInd"]
	sortOrder?: TableReadRecord["sortOrder"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.Prospect" table.
 */
export interface ProspectInsertRecord {
	/**
	 * @default: (newid())
	 */
	prospectId?: TableInsertRecord["prospectId"]
	/**
	 * @maxLen: 30
	 */
	prospect: TableInsertRecord["prospect"]
	/**
	 * @maxLen: -1
	 */
	description?: TableInsertRecord["description"]
	/**
	 * @maxLen: 100
	 */
	project: TableInsertRecord["project"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.Prospect" table.
 */
export type ProspectUpdateRecord = Partial<ProspectInsertRecord>;
