// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.MetamorphicGrade" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const MetamorphicGradeTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	MetamorphicGradeId: z.any(),
});

/**
 * The base record type for the "dbo.MetamorphicGrade" table.
 * This type represents the raw database record without case transforms.
 */
export type MetamorphicGradeBaseRecord = z.output<typeof MetamorphicGradeTableBaseSchema>;

/**
 * Read transform for the "dbo.MetamorphicGrade" table.
 * Maps database fields to app case properties.
 */
export function transformMetamorphicGradeBaseRecord(data: MetamorphicGradeBaseRecord): {
	code: MetamorphicGradeBaseRecord["Code"]
	description: MetamorphicGradeBaseRecord["Description"]
	sortOrder: MetamorphicGradeBaseRecord["SortOrder"]
	isDefaultInd: MetamorphicGradeBaseRecord["IsDefaultInd"]
	activeInd: MetamorphicGradeBaseRecord["ActiveInd"]
	createdOnDt: MetamorphicGradeBaseRecord["CreatedOnDt"]
	createdBy: MetamorphicGradeBaseRecord["CreatedBy"]
	modifiedOnDt?: MetamorphicGradeBaseRecord["ModifiedOnDt"]
	modifiedBy?: MetamorphicGradeBaseRecord["ModifiedBy"]
	rv: MetamorphicGradeBaseRecord["rv"]
	metamorphicGradeId: MetamorphicGradeBaseRecord["MetamorphicGradeId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		metamorphicGradeId: data.MetamorphicGradeId,
	};
}

/**
 * Read schema for the "dbo.MetamorphicGrade" table (after casing transform).
 */
export const MetamorphicGradeTableSchema = MetamorphicGradeTableBaseSchema.transform(transformMetamorphicGradeBaseRecord);

/**
 * Base insert/write schema for the "dbo.MetamorphicGrade" table (no casing transforms).
 */
export const MetamorphicGradeTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	metamorphicGradeId: z.any().optional(),
});

/**
 * The base record type for the "dbo.MetamorphicGrade" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type MetamorphicGradeInsertBaseRecord = z.output<typeof MetamorphicGradeTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.MetamorphicGrade" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type MetamorphicGradeUpdateBaseRecord = Partial<MetamorphicGradeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.MetamorphicGrade" table.
 * Maps app cased properties to database fields.
 */
export function transformMetamorphicGradeInsertBaseRecord(data: MetamorphicGradeInsertBaseRecord): {
	Code: MetamorphicGradeInsertBaseRecord["code"]
	Description: MetamorphicGradeInsertBaseRecord["description"]
	SortOrder?: MetamorphicGradeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: MetamorphicGradeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: MetamorphicGradeInsertBaseRecord["activeInd"]
	CreatedOnDt?: MetamorphicGradeInsertBaseRecord["createdOnDt"]
	CreatedBy?: MetamorphicGradeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: MetamorphicGradeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: MetamorphicGradeInsertBaseRecord["modifiedBy"]
	rv: MetamorphicGradeInsertBaseRecord["rv"]
	MetamorphicGradeId?: MetamorphicGradeInsertBaseRecord["metamorphicGradeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		MetamorphicGradeId: data.metamorphicGradeId,
	};
}

/**
 * Update transform for the "dbo.MetamorphicGrade" table.
 * Maps app cased properties to database fields.
 */
export function transformMetamorphicGradeUpdateBaseRecord(data: MetamorphicGradeUpdateBaseRecord): {
	Code: MetamorphicGradeUpdateBaseRecord["code"]
	Description: MetamorphicGradeUpdateBaseRecord["description"]
	SortOrder?: MetamorphicGradeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: MetamorphicGradeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: MetamorphicGradeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: MetamorphicGradeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: MetamorphicGradeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: MetamorphicGradeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: MetamorphicGradeUpdateBaseRecord["modifiedBy"]
	rv: MetamorphicGradeUpdateBaseRecord["rv"]
	MetamorphicGradeId?: MetamorphicGradeUpdateBaseRecord["metamorphicGradeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		MetamorphicGradeId: data.metamorphicGradeId,
	};
}

/**
 * Insert schema for the "dbo.MetamorphicGrade" table (after casing transform).
 */
export const MetamorphicGradeTableInsertSchema = MetamorphicGradeTableInsertBaseSchema.transform(transformMetamorphicGradeInsertBaseRecord);

/**
 * Update schema for the "dbo.MetamorphicGrade" table (after casing transform).
 */
export const MetamorphicGradeTableUpdateSchema = MetamorphicGradeTableInsertBaseSchema.partial().transform(transformMetamorphicGradeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof MetamorphicGradeTableInsertSchema>;
type TableReadRecord = z.output<typeof MetamorphicGradeTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.MetamorphicGrade" table.
 */
export interface MetamorphicGradeRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	metamorphicGradeId: TableReadRecord["metamorphicGradeId"]
}

/**
 * Insert record (casing transformed) for the "dbo.MetamorphicGrade" table.
 */
export interface MetamorphicGradeInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	metamorphicGradeId?: TableInsertRecord["metamorphicGradeId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.MetamorphicGrade" table.
 */
export type MetamorphicGradeUpdateRecord = Partial<MetamorphicGradeInsertRecord>;
