// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.PtGeologyLog" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const PtGeologyLogTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	PtGeologyLogId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	Organization: z.string(),
	/**
	 * dataType: uniqueidentifier
	 */
	PtLoggingEventId: z.any(),
	/**
	 * dataType: int
	 */
	Priority: z.number(),
	/**
	 * dataType: datetimeoffset
	 */
	LoggedDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	LoggedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	RegoLithologyProfile: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Weathering: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Lith_Code: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Lith_Texture: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Lith_Structure: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Lith_Grainsize: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Lith_Colour_Tone: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Lith_Colour_1: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Lith_Colour_2: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Alt_Code: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Alt_Int: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Alt_Style: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Min_Code: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Min_pct: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Min_Style: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Sulph_Code: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Sulph_pct: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Sulph_Style: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Vein_Code: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Vein_Style: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Vein_pct: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Dip: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Strike: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Comments: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	DataSource: z.string(),
	/**
	 * dataType: int
	 */
	MigrationId: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: binary
	 */
	migrationRv: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	JsonData: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ReportIncludeInd: z.any(),
	/**
	 * dataType: tinyint
	 */
	ValidationStatus: z.number(),
	/**
	 * dataType: nvarchar
	 */
	ValidationErrors: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: tinyint
	 */
	RowStatus: z.number(),
	/**
	 * dataType: uniqueidentifier
	 */
	SupersededById: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.PtGeologyLog" table.
 * This type represents the raw database record without case transforms.
 */
export type PtGeologyLogBaseRecord = z.output<typeof PtGeologyLogTableBaseSchema>;

/**
 * Read transform for the "dbo.PtGeologyLog" table.
 * Maps database fields to app case properties.
 */
export function transformPtGeologyLogBaseRecord(data: PtGeologyLogBaseRecord): {
	ptGeologyLogId: PtGeologyLogBaseRecord["PtGeologyLogId"]
	organization: PtGeologyLogBaseRecord["Organization"]
	ptLoggingEventId: PtGeologyLogBaseRecord["PtLoggingEventId"]
	priority: PtGeologyLogBaseRecord["Priority"]
	loggedDt?: PtGeologyLogBaseRecord["LoggedDt"]
	loggedBy?: PtGeologyLogBaseRecord["LoggedBy"]
	regoLithologyProfile?: PtGeologyLogBaseRecord["RegoLithologyProfile"]
	weathering?: PtGeologyLogBaseRecord["Weathering"]
	lithCode?: PtGeologyLogBaseRecord["Lith_Code"]
	lithTexture?: PtGeologyLogBaseRecord["Lith_Texture"]
	lithStructure?: PtGeologyLogBaseRecord["Lith_Structure"]
	lithGrainsize?: PtGeologyLogBaseRecord["Lith_Grainsize"]
	lithColourTone?: PtGeologyLogBaseRecord["Lith_Colour_Tone"]
	lithColour1?: PtGeologyLogBaseRecord["Lith_Colour_1"]
	lithColour2?: PtGeologyLogBaseRecord["Lith_Colour_2"]
	altCode?: PtGeologyLogBaseRecord["Alt_Code"]
	altInt?: PtGeologyLogBaseRecord["Alt_Int"]
	altStyle?: PtGeologyLogBaseRecord["Alt_Style"]
	minCode?: PtGeologyLogBaseRecord["Min_Code"]
	minPct?: PtGeologyLogBaseRecord["Min_pct"]
	minStyle?: PtGeologyLogBaseRecord["Min_Style"]
	sulphCode?: PtGeologyLogBaseRecord["Sulph_Code"]
	sulphPct?: PtGeologyLogBaseRecord["Sulph_pct"]
	sulphStyle?: PtGeologyLogBaseRecord["Sulph_Style"]
	veinCode?: PtGeologyLogBaseRecord["Vein_Code"]
	veinStyle?: PtGeologyLogBaseRecord["Vein_Style"]
	veinPct?: PtGeologyLogBaseRecord["Vein_pct"]
	dip?: PtGeologyLogBaseRecord["Dip"]
	strike?: PtGeologyLogBaseRecord["Strike"]
	comments?: PtGeologyLogBaseRecord["Comments"]
	dataSource: PtGeologyLogBaseRecord["DataSource"]
	migrationId?: PtGeologyLogBaseRecord["MigrationId"]
	migrationRv?: PtGeologyLogBaseRecord["migrationRv"]
	jsonData?: PtGeologyLogBaseRecord["JsonData"]
	reportIncludeInd: PtGeologyLogBaseRecord["ReportIncludeInd"]
	validationStatus: PtGeologyLogBaseRecord["ValidationStatus"]
	validationErrors?: PtGeologyLogBaseRecord["ValidationErrors"]
	rowStatus: PtGeologyLogBaseRecord["RowStatus"]
	supersededById?: PtGeologyLogBaseRecord["SupersededById"]
	activeInd: PtGeologyLogBaseRecord["ActiveInd"]
	createdOnDt: PtGeologyLogBaseRecord["CreatedOnDt"]
	createdBy: PtGeologyLogBaseRecord["CreatedBy"]
	modifiedOnDt?: PtGeologyLogBaseRecord["ModifiedOnDt"]
	modifiedBy?: PtGeologyLogBaseRecord["ModifiedBy"]
	rv: PtGeologyLogBaseRecord["rv"]
} {
	return {
		ptGeologyLogId: data.PtGeologyLogId,
		organization: data.Organization,
		ptLoggingEventId: data.PtLoggingEventId,
		priority: data.Priority,
		loggedDt: data.LoggedDt,
		loggedBy: data.LoggedBy,
		regoLithologyProfile: data.RegoLithologyProfile,
		weathering: data.Weathering,
		lithCode: data.Lith_Code,
		lithTexture: data.Lith_Texture,
		lithStructure: data.Lith_Structure,
		lithGrainsize: data.Lith_Grainsize,
		lithColourTone: data.Lith_Colour_Tone,
		lithColour1: data.Lith_Colour_1,
		lithColour2: data.Lith_Colour_2,
		altCode: data.Alt_Code,
		altInt: data.Alt_Int,
		altStyle: data.Alt_Style,
		minCode: data.Min_Code,
		minPct: data.Min_pct,
		minStyle: data.Min_Style,
		sulphCode: data.Sulph_Code,
		sulphPct: data.Sulph_pct,
		sulphStyle: data.Sulph_Style,
		veinCode: data.Vein_Code,
		veinStyle: data.Vein_Style,
		veinPct: data.Vein_pct,
		dip: data.Dip,
		strike: data.Strike,
		comments: data.Comments,
		dataSource: data.DataSource,
		migrationId: data.MigrationId,
		migrationRv: data.migrationRv,
		jsonData: data.JsonData,
		reportIncludeInd: data.ReportIncludeInd,
		validationStatus: data.ValidationStatus,
		validationErrors: data.ValidationErrors,
		rowStatus: data.RowStatus,
		supersededById: data.SupersededById,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.PtGeologyLog" table (after casing transform).
 */
export const PtGeologyLogTableSchema = PtGeologyLogTableBaseSchema.transform(transformPtGeologyLogBaseRecord);

/**
 * Base insert/write schema for the "dbo.PtGeologyLog" table (no casing transforms).
 */
export const PtGeologyLogTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	ptGeologyLogId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	organization: z.string().max(30),
	/**
	 * dataType: uniqueidentifier
	 */
	ptLoggingEventId: z.any(),
	/**
	 * dataType: int
	 * defaultValue: ((0))
	 */
	priority: z.number().int().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	loggedDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	loggedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	regoLithologyProfile: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	weathering: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	lithCode: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	lithTexture: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	lithStructure: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	lithGrainsize: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	lithColourTone: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	lithColour1: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	lithColour2: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	altCode: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	altInt: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	altStyle: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	minCode: z.string().max(50).nullable().optional(),
	/**
	 * dataType: decimal
	 */
	minPct: z.number().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	minStyle: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	sulphCode: z.string().max(50).nullable().optional(),
	/**
	 * dataType: decimal
	 */
	sulphPct: z.number().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	sulphStyle: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	veinCode: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	veinStyle: z.string().max(50).nullable().optional(),
	/**
	 * dataType: decimal
	 */
	veinPct: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	dip: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	strike: z.number().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	comments: z.string().max(1000).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	dataSource: z.string().max(255),
	/**
	 * dataType: int
	 */
	migrationId: z.number().int().nullable().optional(),
	/**
	 * dataType: binary
	 */
	migrationRv: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	jsonData: z.string().max(-1).nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	reportIncludeInd: z.any().optional(),
	/**
	 * dataType: tinyint
	 * defaultValue: ((0))
	 */
	validationStatus: z.number().int().optional(),
	/**
	 * dataType: nvarchar
	 */
	validationErrors: z.string().max(4000).nullable().optional(),
	/**
	 * dataType: tinyint
	 * defaultValue: ((0))
	 */
	rowStatus: z.number().int().optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	supersededById: z.any().nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.PtGeologyLog" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type PtGeologyLogInsertBaseRecord = z.output<typeof PtGeologyLogTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.PtGeologyLog" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type PtGeologyLogUpdateBaseRecord = Partial<PtGeologyLogInsertBaseRecord>;

/**
 * Insert transform for the "dbo.PtGeologyLog" table.
 * Maps app cased properties to database fields.
 */
export function transformPtGeologyLogInsertBaseRecord(data: PtGeologyLogInsertBaseRecord): {
	PtGeologyLogId?: PtGeologyLogInsertBaseRecord["ptGeologyLogId"]
	Organization: PtGeologyLogInsertBaseRecord["organization"]
	PtLoggingEventId: PtGeologyLogInsertBaseRecord["ptLoggingEventId"]
	Priority?: PtGeologyLogInsertBaseRecord["priority"]
	LoggedDt?: PtGeologyLogInsertBaseRecord["loggedDt"]
	LoggedBy?: PtGeologyLogInsertBaseRecord["loggedBy"]
	RegoLithologyProfile?: PtGeologyLogInsertBaseRecord["regoLithologyProfile"]
	Weathering?: PtGeologyLogInsertBaseRecord["weathering"]
	Lith_Code?: PtGeologyLogInsertBaseRecord["lithCode"]
	Lith_Texture?: PtGeologyLogInsertBaseRecord["lithTexture"]
	Lith_Structure?: PtGeologyLogInsertBaseRecord["lithStructure"]
	Lith_Grainsize?: PtGeologyLogInsertBaseRecord["lithGrainsize"]
	Lith_Colour_Tone?: PtGeologyLogInsertBaseRecord["lithColourTone"]
	Lith_Colour_1?: PtGeologyLogInsertBaseRecord["lithColour1"]
	Lith_Colour_2?: PtGeologyLogInsertBaseRecord["lithColour2"]
	Alt_Code?: PtGeologyLogInsertBaseRecord["altCode"]
	Alt_Int?: PtGeologyLogInsertBaseRecord["altInt"]
	Alt_Style?: PtGeologyLogInsertBaseRecord["altStyle"]
	Min_Code?: PtGeologyLogInsertBaseRecord["minCode"]
	Min_pct?: PtGeologyLogInsertBaseRecord["minPct"]
	Min_Style?: PtGeologyLogInsertBaseRecord["minStyle"]
	Sulph_Code?: PtGeologyLogInsertBaseRecord["sulphCode"]
	Sulph_pct?: PtGeologyLogInsertBaseRecord["sulphPct"]
	Sulph_Style?: PtGeologyLogInsertBaseRecord["sulphStyle"]
	Vein_Code?: PtGeologyLogInsertBaseRecord["veinCode"]
	Vein_Style?: PtGeologyLogInsertBaseRecord["veinStyle"]
	Vein_pct?: PtGeologyLogInsertBaseRecord["veinPct"]
	Dip?: PtGeologyLogInsertBaseRecord["dip"]
	Strike?: PtGeologyLogInsertBaseRecord["strike"]
	Comments?: PtGeologyLogInsertBaseRecord["comments"]
	DataSource: PtGeologyLogInsertBaseRecord["dataSource"]
	MigrationId?: PtGeologyLogInsertBaseRecord["migrationId"]
	migrationRv?: PtGeologyLogInsertBaseRecord["migrationRv"]
	JsonData?: PtGeologyLogInsertBaseRecord["jsonData"]
	ReportIncludeInd?: PtGeologyLogInsertBaseRecord["reportIncludeInd"]
	ValidationStatus?: PtGeologyLogInsertBaseRecord["validationStatus"]
	ValidationErrors?: PtGeologyLogInsertBaseRecord["validationErrors"]
	RowStatus?: PtGeologyLogInsertBaseRecord["rowStatus"]
	SupersededById?: PtGeologyLogInsertBaseRecord["supersededById"]
	ActiveInd?: PtGeologyLogInsertBaseRecord["activeInd"]
	CreatedOnDt?: PtGeologyLogInsertBaseRecord["createdOnDt"]
	CreatedBy?: PtGeologyLogInsertBaseRecord["createdBy"]
	ModifiedOnDt?: PtGeologyLogInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: PtGeologyLogInsertBaseRecord["modifiedBy"]
	rv: PtGeologyLogInsertBaseRecord["rv"]
} {
	return {
		PtGeologyLogId: data.ptGeologyLogId,
		Organization: data.organization,
		PtLoggingEventId: data.ptLoggingEventId,
		Priority: data.priority,
		LoggedDt: data.loggedDt,
		LoggedBy: data.loggedBy,
		RegoLithologyProfile: data.regoLithologyProfile,
		Weathering: data.weathering,
		Lith_Code: data.lithCode,
		Lith_Texture: data.lithTexture,
		Lith_Structure: data.lithStructure,
		Lith_Grainsize: data.lithGrainsize,
		Lith_Colour_Tone: data.lithColourTone,
		Lith_Colour_1: data.lithColour1,
		Lith_Colour_2: data.lithColour2,
		Alt_Code: data.altCode,
		Alt_Int: data.altInt,
		Alt_Style: data.altStyle,
		Min_Code: data.minCode,
		Min_pct: data.minPct,
		Min_Style: data.minStyle,
		Sulph_Code: data.sulphCode,
		Sulph_pct: data.sulphPct,
		Sulph_Style: data.sulphStyle,
		Vein_Code: data.veinCode,
		Vein_Style: data.veinStyle,
		Vein_pct: data.veinPct,
		Dip: data.dip,
		Strike: data.strike,
		Comments: data.comments,
		DataSource: data.dataSource,
		MigrationId: data.migrationId,
		migrationRv: data.migrationRv,
		JsonData: data.jsonData,
		ReportIncludeInd: data.reportIncludeInd,
		ValidationStatus: data.validationStatus,
		ValidationErrors: data.validationErrors,
		RowStatus: data.rowStatus,
		SupersededById: data.supersededById,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.PtGeologyLog" table.
 * Maps app cased properties to database fields.
 */
export function transformPtGeologyLogUpdateBaseRecord(data: PtGeologyLogUpdateBaseRecord): {
	PtGeologyLogId?: PtGeologyLogUpdateBaseRecord["ptGeologyLogId"]
	Organization: PtGeologyLogUpdateBaseRecord["organization"]
	PtLoggingEventId: PtGeologyLogUpdateBaseRecord["ptLoggingEventId"]
	Priority?: PtGeologyLogUpdateBaseRecord["priority"]
	LoggedDt?: PtGeologyLogUpdateBaseRecord["loggedDt"]
	LoggedBy?: PtGeologyLogUpdateBaseRecord["loggedBy"]
	RegoLithologyProfile?: PtGeologyLogUpdateBaseRecord["regoLithologyProfile"]
	Weathering?: PtGeologyLogUpdateBaseRecord["weathering"]
	Lith_Code?: PtGeologyLogUpdateBaseRecord["lithCode"]
	Lith_Texture?: PtGeologyLogUpdateBaseRecord["lithTexture"]
	Lith_Structure?: PtGeologyLogUpdateBaseRecord["lithStructure"]
	Lith_Grainsize?: PtGeologyLogUpdateBaseRecord["lithGrainsize"]
	Lith_Colour_Tone?: PtGeologyLogUpdateBaseRecord["lithColourTone"]
	Lith_Colour_1?: PtGeologyLogUpdateBaseRecord["lithColour1"]
	Lith_Colour_2?: PtGeologyLogUpdateBaseRecord["lithColour2"]
	Alt_Code?: PtGeologyLogUpdateBaseRecord["altCode"]
	Alt_Int?: PtGeologyLogUpdateBaseRecord["altInt"]
	Alt_Style?: PtGeologyLogUpdateBaseRecord["altStyle"]
	Min_Code?: PtGeologyLogUpdateBaseRecord["minCode"]
	Min_pct?: PtGeologyLogUpdateBaseRecord["minPct"]
	Min_Style?: PtGeologyLogUpdateBaseRecord["minStyle"]
	Sulph_Code?: PtGeologyLogUpdateBaseRecord["sulphCode"]
	Sulph_pct?: PtGeologyLogUpdateBaseRecord["sulphPct"]
	Sulph_Style?: PtGeologyLogUpdateBaseRecord["sulphStyle"]
	Vein_Code?: PtGeologyLogUpdateBaseRecord["veinCode"]
	Vein_Style?: PtGeologyLogUpdateBaseRecord["veinStyle"]
	Vein_pct?: PtGeologyLogUpdateBaseRecord["veinPct"]
	Dip?: PtGeologyLogUpdateBaseRecord["dip"]
	Strike?: PtGeologyLogUpdateBaseRecord["strike"]
	Comments?: PtGeologyLogUpdateBaseRecord["comments"]
	DataSource: PtGeologyLogUpdateBaseRecord["dataSource"]
	MigrationId?: PtGeologyLogUpdateBaseRecord["migrationId"]
	migrationRv?: PtGeologyLogUpdateBaseRecord["migrationRv"]
	JsonData?: PtGeologyLogUpdateBaseRecord["jsonData"]
	ReportIncludeInd?: PtGeologyLogUpdateBaseRecord["reportIncludeInd"]
	ValidationStatus?: PtGeologyLogUpdateBaseRecord["validationStatus"]
	ValidationErrors?: PtGeologyLogUpdateBaseRecord["validationErrors"]
	RowStatus?: PtGeologyLogUpdateBaseRecord["rowStatus"]
	SupersededById?: PtGeologyLogUpdateBaseRecord["supersededById"]
	ActiveInd?: PtGeologyLogUpdateBaseRecord["activeInd"]
	CreatedOnDt?: PtGeologyLogUpdateBaseRecord["createdOnDt"]
	CreatedBy?: PtGeologyLogUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: PtGeologyLogUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: PtGeologyLogUpdateBaseRecord["modifiedBy"]
	rv: PtGeologyLogUpdateBaseRecord["rv"]
} {
	return {
		PtGeologyLogId: data.ptGeologyLogId,
		Organization: data.organization,
		PtLoggingEventId: data.ptLoggingEventId,
		Priority: data.priority,
		LoggedDt: data.loggedDt,
		LoggedBy: data.loggedBy,
		RegoLithologyProfile: data.regoLithologyProfile,
		Weathering: data.weathering,
		Lith_Code: data.lithCode,
		Lith_Texture: data.lithTexture,
		Lith_Structure: data.lithStructure,
		Lith_Grainsize: data.lithGrainsize,
		Lith_Colour_Tone: data.lithColourTone,
		Lith_Colour_1: data.lithColour1,
		Lith_Colour_2: data.lithColour2,
		Alt_Code: data.altCode,
		Alt_Int: data.altInt,
		Alt_Style: data.altStyle,
		Min_Code: data.minCode,
		Min_pct: data.minPct,
		Min_Style: data.minStyle,
		Sulph_Code: data.sulphCode,
		Sulph_pct: data.sulphPct,
		Sulph_Style: data.sulphStyle,
		Vein_Code: data.veinCode,
		Vein_Style: data.veinStyle,
		Vein_pct: data.veinPct,
		Dip: data.dip,
		Strike: data.strike,
		Comments: data.comments,
		DataSource: data.dataSource,
		MigrationId: data.migrationId,
		migrationRv: data.migrationRv,
		JsonData: data.jsonData,
		ReportIncludeInd: data.reportIncludeInd,
		ValidationStatus: data.validationStatus,
		ValidationErrors: data.validationErrors,
		RowStatus: data.rowStatus,
		SupersededById: data.supersededById,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.PtGeologyLog" table (after casing transform).
 */
export const PtGeologyLogTableInsertSchema = PtGeologyLogTableInsertBaseSchema.transform(transformPtGeologyLogInsertBaseRecord);

/**
 * Update schema for the "dbo.PtGeologyLog" table (after casing transform).
 */
export const PtGeologyLogTableUpdateSchema = PtGeologyLogTableInsertBaseSchema.partial().transform(transformPtGeologyLogUpdateBaseRecord);

type TableInsertRecord = z.input<typeof PtGeologyLogTableInsertSchema>;
type TableReadRecord = z.output<typeof PtGeologyLogTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.PtGeologyLog" table.
 */
export interface PtGeologyLogRecord {
	ptGeologyLogId: TableReadRecord["ptGeologyLogId"]
	organization: TableReadRecord["organization"]
	ptLoggingEventId: TableReadRecord["ptLoggingEventId"]
	priority: TableReadRecord["priority"]
	loggedDt?: TableReadRecord["loggedDt"]
	loggedBy?: TableReadRecord["loggedBy"]
	regoLithologyProfile?: TableReadRecord["regoLithologyProfile"]
	weathering?: TableReadRecord["weathering"]
	lithCode?: TableReadRecord["lithCode"]
	lithTexture?: TableReadRecord["lithTexture"]
	lithStructure?: TableReadRecord["lithStructure"]
	lithGrainsize?: TableReadRecord["lithGrainsize"]
	lithColourTone?: TableReadRecord["lithColourTone"]
	lithColour1?: TableReadRecord["lithColour1"]
	lithColour2?: TableReadRecord["lithColour2"]
	altCode?: TableReadRecord["altCode"]
	altInt?: TableReadRecord["altInt"]
	altStyle?: TableReadRecord["altStyle"]
	minCode?: TableReadRecord["minCode"]
	minPct?: TableReadRecord["minPct"]
	minStyle?: TableReadRecord["minStyle"]
	sulphCode?: TableReadRecord["sulphCode"]
	sulphPct?: TableReadRecord["sulphPct"]
	sulphStyle?: TableReadRecord["sulphStyle"]
	veinCode?: TableReadRecord["veinCode"]
	veinStyle?: TableReadRecord["veinStyle"]
	veinPct?: TableReadRecord["veinPct"]
	dip?: TableReadRecord["dip"]
	strike?: TableReadRecord["strike"]
	comments?: TableReadRecord["comments"]
	dataSource: TableReadRecord["dataSource"]
	migrationId?: TableReadRecord["migrationId"]
	migrationRv?: TableReadRecord["migrationRv"]
	jsonData?: TableReadRecord["jsonData"]
	reportIncludeInd: TableReadRecord["reportIncludeInd"]
	validationStatus: TableReadRecord["validationStatus"]
	validationErrors?: TableReadRecord["validationErrors"]
	rowStatus: TableReadRecord["rowStatus"]
	supersededById?: TableReadRecord["supersededById"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.PtGeologyLog" table.
 */
export interface PtGeologyLogInsertRecord {
	/**
	 * @default: (newid())
	 */
	ptGeologyLogId?: TableInsertRecord["ptGeologyLogId"]
	/**
	 * @maxLen: 30
	 */
	organization: TableInsertRecord["organization"]
	ptLoggingEventId: TableInsertRecord["ptLoggingEventId"]
	/**
	 * @default: ((0))
	 */
	priority?: TableInsertRecord["priority"]
	loggedDt?: TableInsertRecord["loggedDt"]
	/**
	 * @maxLen: 50
	 */
	loggedBy?: TableInsertRecord["loggedBy"]
	/**
	 * @maxLen: 50
	 */
	regoLithologyProfile?: TableInsertRecord["regoLithologyProfile"]
	/**
	 * @maxLen: 50
	 */
	weathering?: TableInsertRecord["weathering"]
	/**
	 * @maxLen: 50
	 */
	lithCode?: TableInsertRecord["lithCode"]
	/**
	 * @maxLen: 50
	 */
	lithTexture?: TableInsertRecord["lithTexture"]
	/**
	 * @maxLen: 50
	 */
	lithStructure?: TableInsertRecord["lithStructure"]
	/**
	 * @maxLen: 50
	 */
	lithGrainsize?: TableInsertRecord["lithGrainsize"]
	/**
	 * @maxLen: 50
	 */
	lithColourTone?: TableInsertRecord["lithColourTone"]
	/**
	 * @maxLen: 50
	 */
	lithColour1?: TableInsertRecord["lithColour1"]
	/**
	 * @maxLen: 50
	 */
	lithColour2?: TableInsertRecord["lithColour2"]
	/**
	 * @maxLen: 50
	 */
	altCode?: TableInsertRecord["altCode"]
	/**
	 * @maxLen: 50
	 */
	altInt?: TableInsertRecord["altInt"]
	/**
	 * @maxLen: 50
	 */
	altStyle?: TableInsertRecord["altStyle"]
	/**
	 * @maxLen: 50
	 */
	minCode?: TableInsertRecord["minCode"]
	minPct?: TableInsertRecord["minPct"]
	/**
	 * @maxLen: 50
	 */
	minStyle?: TableInsertRecord["minStyle"]
	/**
	 * @maxLen: 50
	 */
	sulphCode?: TableInsertRecord["sulphCode"]
	sulphPct?: TableInsertRecord["sulphPct"]
	/**
	 * @maxLen: 50
	 */
	sulphStyle?: TableInsertRecord["sulphStyle"]
	/**
	 * @maxLen: 50
	 */
	veinCode?: TableInsertRecord["veinCode"]
	/**
	 * @maxLen: 50
	 */
	veinStyle?: TableInsertRecord["veinStyle"]
	veinPct?: TableInsertRecord["veinPct"]
	dip?: TableInsertRecord["dip"]
	strike?: TableInsertRecord["strike"]
	/**
	 * @maxLen: 1000
	 */
	comments?: TableInsertRecord["comments"]
	/**
	 * @maxLen: 255
	 */
	dataSource: TableInsertRecord["dataSource"]
	migrationId?: TableInsertRecord["migrationId"]
	/**
	 * @maxLen: 8
	 */
	migrationRv?: TableInsertRecord["migrationRv"]
	/**
	 * @maxLen: -1
	 */
	jsonData?: TableInsertRecord["jsonData"]
	/**
	 * @default: ((0))
	 */
	reportIncludeInd?: TableInsertRecord["reportIncludeInd"]
	/**
	 * @default: ((0))
	 */
	validationStatus?: TableInsertRecord["validationStatus"]
	/**
	 * @maxLen: 4000
	 */
	validationErrors?: TableInsertRecord["validationErrors"]
	/**
	 * @default: ((0))
	 */
	rowStatus?: TableInsertRecord["rowStatus"]
	supersededById?: TableInsertRecord["supersededById"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.PtGeologyLog" table.
 */
export type PtGeologyLogUpdateRecord = Partial<PtGeologyLogInsertRecord>;
