// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.vQAQC_StandardPerformance" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const VqaqcStandardperformanceTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	AssayId: z.any(),
	/**
	 * dataType: uniqueidentifier
	 */
	SampleId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	BatchNo: z.string(),
	/**
	 * dataType: nvarchar
	 */
	LabCode: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Element: z.string(),
	/**
	 * dataType: decimal
	 */
	ActualValue: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	ExpectedValue: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	ExpectedStDev: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Z_Score: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	WarningLimitSigma: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	FailureLimitSigma: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: varchar
	 */
	QC_Status: z.string(),
});

/**
 * The base record type for the "dbo.vQAQC_StandardPerformance" table.
 * This type represents the raw database record without case transforms.
 */
export type VQaqcStandardPerformanceBaseRecord = z.output<typeof VqaqcStandardperformanceTableBaseSchema>;

/**
 * Read transform for the "dbo.vQAQC_StandardPerformance" table.
 * Maps database fields to app case properties.
 */
export function transformVQaqcStandardPerformanceBaseRecord(data: VQaqcStandardPerformanceBaseRecord): {
	assayId: VQaqcStandardPerformanceBaseRecord["AssayId"]
	sampleId: VQaqcStandardPerformanceBaseRecord["SampleId"]
	batchNo: VQaqcStandardPerformanceBaseRecord["BatchNo"]
	labCode: VQaqcStandardPerformanceBaseRecord["LabCode"]
	element: VQaqcStandardPerformanceBaseRecord["Element"]
	actualValue?: VQaqcStandardPerformanceBaseRecord["ActualValue"]
	expectedValue?: VQaqcStandardPerformanceBaseRecord["ExpectedValue"]
	expectedStDev?: VQaqcStandardPerformanceBaseRecord["ExpectedStDev"]
	zScore?: VQaqcStandardPerformanceBaseRecord["Z_Score"]
	warningLimitSigma?: VQaqcStandardPerformanceBaseRecord["WarningLimitSigma"]
	failureLimitSigma?: VQaqcStandardPerformanceBaseRecord["FailureLimitSigma"]
	qcStatus: VQaqcStandardPerformanceBaseRecord["QC_Status"]
} {
	return {
		assayId: data.AssayId,
		sampleId: data.SampleId,
		batchNo: data.BatchNo,
		labCode: data.LabCode,
		element: data.Element,
		actualValue: data.ActualValue,
		expectedValue: data.ExpectedValue,
		expectedStDev: data.ExpectedStDev,
		zScore: data.Z_Score,
		warningLimitSigma: data.WarningLimitSigma,
		failureLimitSigma: data.FailureLimitSigma,
		qcStatus: data.QC_Status,
	};
}

/**
 * Read schema for the "dbo.vQAQC_StandardPerformance" table (after casing transform).
 */
export const VqaqcStandardperformanceTableSchema = VqaqcStandardperformanceTableBaseSchema.transform(transformVQaqcStandardPerformanceBaseRecord);

/**
 * Base insert/write schema for the "dbo.vQAQC_StandardPerformance" table (no casing transforms).
 */
export const VqaqcStandardperformanceTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	assayId: z.any(),
	/**
	 * dataType: uniqueidentifier
	 */
	sampleId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	batchNo: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	labCode: z.string().max(20),
	/**
	 * dataType: nvarchar
	 */
	element: z.string().max(50),
	/**
	 * dataType: decimal
	 */
	actualValue: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	expectedValue: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	expectedStDev: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	zScore: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	warningLimitSigma: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	failureLimitSigma: z.number().nullable().optional(),
	/**
	 * dataType: varchar
	 */
	qcStatus: z.string().max(4),
});

/**
 * The base record type for the "dbo.vQAQC_StandardPerformance" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type VQaqcStandardPerformanceInsertBaseRecord = z.output<typeof VqaqcStandardperformanceTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.vQAQC_StandardPerformance" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type VQaqcStandardPerformanceUpdateBaseRecord = Partial<VQaqcStandardPerformanceInsertBaseRecord>;

/**
 * Insert transform for the "dbo.vQAQC_StandardPerformance" table.
 * Maps app cased properties to database fields.
 */
export function transformVQaqcStandardPerformanceInsertBaseRecord(data: VQaqcStandardPerformanceInsertBaseRecord): {
	AssayId: VQaqcStandardPerformanceInsertBaseRecord["assayId"]
	SampleId: VQaqcStandardPerformanceInsertBaseRecord["sampleId"]
	BatchNo: VQaqcStandardPerformanceInsertBaseRecord["batchNo"]
	LabCode: VQaqcStandardPerformanceInsertBaseRecord["labCode"]
	Element: VQaqcStandardPerformanceInsertBaseRecord["element"]
	ActualValue?: VQaqcStandardPerformanceInsertBaseRecord["actualValue"]
	ExpectedValue?: VQaqcStandardPerformanceInsertBaseRecord["expectedValue"]
	ExpectedStDev?: VQaqcStandardPerformanceInsertBaseRecord["expectedStDev"]
	Z_Score?: VQaqcStandardPerformanceInsertBaseRecord["zScore"]
	WarningLimitSigma?: VQaqcStandardPerformanceInsertBaseRecord["warningLimitSigma"]
	FailureLimitSigma?: VQaqcStandardPerformanceInsertBaseRecord["failureLimitSigma"]
	QC_Status: VQaqcStandardPerformanceInsertBaseRecord["qcStatus"]
} {
	return {
		AssayId: data.assayId,
		SampleId: data.sampleId,
		BatchNo: data.batchNo,
		LabCode: data.labCode,
		Element: data.element,
		ActualValue: data.actualValue,
		ExpectedValue: data.expectedValue,
		ExpectedStDev: data.expectedStDev,
		Z_Score: data.zScore,
		WarningLimitSigma: data.warningLimitSigma,
		FailureLimitSigma: data.failureLimitSigma,
		QC_Status: data.qcStatus,
	};
}

/**
 * Update transform for the "dbo.vQAQC_StandardPerformance" table.
 * Maps app cased properties to database fields.
 */
export function transformVQaqcStandardPerformanceUpdateBaseRecord(data: VQaqcStandardPerformanceUpdateBaseRecord): {
	AssayId: VQaqcStandardPerformanceUpdateBaseRecord["assayId"]
	SampleId: VQaqcStandardPerformanceUpdateBaseRecord["sampleId"]
	BatchNo: VQaqcStandardPerformanceUpdateBaseRecord["batchNo"]
	LabCode: VQaqcStandardPerformanceUpdateBaseRecord["labCode"]
	Element: VQaqcStandardPerformanceUpdateBaseRecord["element"]
	ActualValue?: VQaqcStandardPerformanceUpdateBaseRecord["actualValue"]
	ExpectedValue?: VQaqcStandardPerformanceUpdateBaseRecord["expectedValue"]
	ExpectedStDev?: VQaqcStandardPerformanceUpdateBaseRecord["expectedStDev"]
	Z_Score?: VQaqcStandardPerformanceUpdateBaseRecord["zScore"]
	WarningLimitSigma?: VQaqcStandardPerformanceUpdateBaseRecord["warningLimitSigma"]
	FailureLimitSigma?: VQaqcStandardPerformanceUpdateBaseRecord["failureLimitSigma"]
	QC_Status: VQaqcStandardPerformanceUpdateBaseRecord["qcStatus"]
} {
	return {
		AssayId: data.assayId,
		SampleId: data.sampleId,
		BatchNo: data.batchNo,
		LabCode: data.labCode,
		Element: data.element,
		ActualValue: data.actualValue,
		ExpectedValue: data.expectedValue,
		ExpectedStDev: data.expectedStDev,
		Z_Score: data.zScore,
		WarningLimitSigma: data.warningLimitSigma,
		FailureLimitSigma: data.failureLimitSigma,
		QC_Status: data.qcStatus,
	};
}

/**
 * Insert schema for the "dbo.vQAQC_StandardPerformance" table (after casing transform).
 */
export const VqaqcStandardperformanceTableInsertSchema = VqaqcStandardperformanceTableInsertBaseSchema.transform(transformVQaqcStandardPerformanceInsertBaseRecord);

/**
 * Update schema for the "dbo.vQAQC_StandardPerformance" table (after casing transform).
 */
export const VqaqcStandardperformanceTableUpdateSchema = VqaqcStandardperformanceTableInsertBaseSchema.partial().transform(transformVQaqcStandardPerformanceUpdateBaseRecord);

type TableInsertRecord = z.input<typeof VqaqcStandardperformanceTableInsertSchema>;
type TableReadRecord = z.output<typeof VqaqcStandardperformanceTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.vQAQC_StandardPerformance" table.
 */
export interface VQaqcStandardPerformanceRecord {
	assayId: TableReadRecord["assayId"]
	sampleId: TableReadRecord["sampleId"]
	batchNo: TableReadRecord["batchNo"]
	labCode: TableReadRecord["labCode"]
	element: TableReadRecord["element"]
	actualValue?: TableReadRecord["actualValue"]
	expectedValue?: TableReadRecord["expectedValue"]
	expectedStDev?: TableReadRecord["expectedStDev"]
	zScore?: TableReadRecord["zScore"]
	warningLimitSigma?: TableReadRecord["warningLimitSigma"]
	failureLimitSigma?: TableReadRecord["failureLimitSigma"]
	qcStatus: TableReadRecord["qcStatus"]
}

/**
 * Insert record (casing transformed) for the "dbo.vQAQC_StandardPerformance" table.
 */
export interface VQaqcStandardPerformanceInsertRecord {
	assayId: TableInsertRecord["assayId"]
	sampleId: TableInsertRecord["sampleId"]
	/**
	 * @maxLen: 50
	 */
	batchNo: TableInsertRecord["batchNo"]
	/**
	 * @maxLen: 20
	 */
	labCode: TableInsertRecord["labCode"]
	/**
	 * @maxLen: 50
	 */
	element: TableInsertRecord["element"]
	actualValue?: TableInsertRecord["actualValue"]
	expectedValue?: TableInsertRecord["expectedValue"]
	expectedStDev?: TableInsertRecord["expectedStDev"]
	zScore?: TableInsertRecord["zScore"]
	warningLimitSigma?: TableInsertRecord["warningLimitSigma"]
	failureLimitSigma?: TableInsertRecord["failureLimitSigma"]
	/**
	 * @maxLen: 4
	 */
	qcStatus: TableInsertRecord["qcStatus"]
}

/**
 * Updatable record (casing transformed) for the "dbo.vQAQC_StandardPerformance" table.
 */
export type VQaqcStandardPerformanceUpdateRecord = Partial<VQaqcStandardPerformanceInsertRecord>;
