// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.vw_UnifiedQC_Base" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const VwUnifiedqcBaseTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Organization: z.string(),
	/**
	 * dataType: uniqueidentifier
	 */
	SampleId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	SampleNm: z.string(),
	/**
	 * dataType: nvarchar
	 */
	StandardId: z.string(),
	/**
	 * dataType: uniqueidentifier
	 */
	OriginalSampleId: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: varchar
	 */
	QCType: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	SampledDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	SampledBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	CollarId: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: smallint
	 */
	Priority: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Element: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	GenericMethod: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	LabElement: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	UnitCode: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	AssayResult: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	AssayResultNum: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Repeat: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	BatchNo: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	LabCode: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	LabFinalDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	BatchValidated: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	BatchStatus: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	ExpectedValue: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	ExpectedStDev: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	ExpectedOutlier: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ReferenceValueType: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ReferenceUnits: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	DetectionLimit: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	UpperLimit: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	SampleWeight: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	SampleWeightUnitCode: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	AssayPassFail: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	sysAssayStatus: z.string().nullable().transform(value => value ?? undefined).optional(),
});

/**
 * The base record type for the "dbo.vw_UnifiedQC_Base" table.
 * This type represents the raw database record without case transforms.
 */
export type VwUnifiedQcBaseBaseRecord = z.output<typeof VwUnifiedqcBaseTableBaseSchema>;

/**
 * Read transform for the "dbo.vw_UnifiedQC_Base" table.
 * Maps database fields to app case properties.
 */
export function transformVwUnifiedQcBaseBaseRecord(data: VwUnifiedQcBaseBaseRecord): {
	organization: VwUnifiedQcBaseBaseRecord["Organization"]
	sampleId: VwUnifiedQcBaseBaseRecord["SampleId"]
	sampleNm: VwUnifiedQcBaseBaseRecord["SampleNm"]
	standardId: VwUnifiedQcBaseBaseRecord["StandardId"]
	originalSampleId?: VwUnifiedQcBaseBaseRecord["OriginalSampleId"]
	qCType: VwUnifiedQcBaseBaseRecord["QCType"]
	sampledDt?: VwUnifiedQcBaseBaseRecord["SampledDt"]
	sampledBy?: VwUnifiedQcBaseBaseRecord["SampledBy"]
	collarId?: VwUnifiedQcBaseBaseRecord["CollarId"]
	priority?: VwUnifiedQcBaseBaseRecord["Priority"]
	element?: VwUnifiedQcBaseBaseRecord["Element"]
	genericMethod?: VwUnifiedQcBaseBaseRecord["GenericMethod"]
	labElement?: VwUnifiedQcBaseBaseRecord["LabElement"]
	unitCode?: VwUnifiedQcBaseBaseRecord["UnitCode"]
	assayResult?: VwUnifiedQcBaseBaseRecord["AssayResult"]
	assayResultNum?: VwUnifiedQcBaseBaseRecord["AssayResultNum"]
	repeat?: VwUnifiedQcBaseBaseRecord["Repeat"]
	batchNo?: VwUnifiedQcBaseBaseRecord["BatchNo"]
	labCode?: VwUnifiedQcBaseBaseRecord["LabCode"]
	labFinalDt?: VwUnifiedQcBaseBaseRecord["LabFinalDt"]
	batchValidated?: VwUnifiedQcBaseBaseRecord["BatchValidated"]
	batchStatus?: VwUnifiedQcBaseBaseRecord["BatchStatus"]
	expectedValue?: VwUnifiedQcBaseBaseRecord["ExpectedValue"]
	expectedStDev?: VwUnifiedQcBaseBaseRecord["ExpectedStDev"]
	expectedOutlier?: VwUnifiedQcBaseBaseRecord["ExpectedOutlier"]
	referenceValueType?: VwUnifiedQcBaseBaseRecord["ReferenceValueType"]
	referenceUnits?: VwUnifiedQcBaseBaseRecord["ReferenceUnits"]
	detectionLimit?: VwUnifiedQcBaseBaseRecord["DetectionLimit"]
	upperLimit?: VwUnifiedQcBaseBaseRecord["UpperLimit"]
	sampleWeight?: VwUnifiedQcBaseBaseRecord["SampleWeight"]
	sampleWeightUnitCode?: VwUnifiedQcBaseBaseRecord["SampleWeightUnitCode"]
	assayPassFail?: VwUnifiedQcBaseBaseRecord["AssayPassFail"]
	sysAssayStatus?: VwUnifiedQcBaseBaseRecord["sysAssayStatus"]
} {
	return {
		organization: data.Organization,
		sampleId: data.SampleId,
		sampleNm: data.SampleNm,
		standardId: data.StandardId,
		originalSampleId: data.OriginalSampleId,
		qCType: data.QCType,
		sampledDt: data.SampledDt,
		sampledBy: data.SampledBy,
		collarId: data.CollarId,
		priority: data.Priority,
		element: data.Element,
		genericMethod: data.GenericMethod,
		labElement: data.LabElement,
		unitCode: data.UnitCode,
		assayResult: data.AssayResult,
		assayResultNum: data.AssayResultNum,
		repeat: data.Repeat,
		batchNo: data.BatchNo,
		labCode: data.LabCode,
		labFinalDt: data.LabFinalDt,
		batchValidated: data.BatchValidated,
		batchStatus: data.BatchStatus,
		expectedValue: data.ExpectedValue,
		expectedStDev: data.ExpectedStDev,
		expectedOutlier: data.ExpectedOutlier,
		referenceValueType: data.ReferenceValueType,
		referenceUnits: data.ReferenceUnits,
		detectionLimit: data.DetectionLimit,
		upperLimit: data.UpperLimit,
		sampleWeight: data.SampleWeight,
		sampleWeightUnitCode: data.SampleWeightUnitCode,
		assayPassFail: data.AssayPassFail,
		sysAssayStatus: data.sysAssayStatus,
	};
}

/**
 * Read schema for the "dbo.vw_UnifiedQC_Base" table (after casing transform).
 */
export const VwUnifiedqcBaseTableSchema = VwUnifiedqcBaseTableBaseSchema.transform(transformVwUnifiedQcBaseBaseRecord);

/**
 * Base insert/write schema for the "dbo.vw_UnifiedQC_Base" table (no casing transforms).
 */
export const VwUnifiedqcBaseTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	organization: z.string().max(30),
	/**
	 * dataType: uniqueidentifier
	 */
	sampleId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	sampleNm: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	standardId: z.string().max(50),
	/**
	 * dataType: uniqueidentifier
	 */
	originalSampleId: z.any().nullable().optional(),
	/**
	 * dataType: varchar
	 */
	qCType: z.string().max(3),
	/**
	 * dataType: datetimeoffset
	 */
	sampledDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	sampledBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	collarId: z.any().nullable().optional(),
	/**
	 * dataType: smallint
	 */
	priority: z.number().int().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	element: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	genericMethod: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	labElement: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	unitCode: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	assayResult: z.string().max(20).nullable().optional(),
	/**
	 * dataType: decimal
	 */
	assayResultNum: z.number().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	repeat: z.string().max(10).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	batchNo: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	labCode: z.string().max(20).nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	labFinalDt: z.any().nullable().optional(),
	/**
	 * dataType: bit
	 */
	batchValidated: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	batchStatus: z.string().max(50).nullable().optional(),
	/**
	 * dataType: decimal
	 */
	expectedValue: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	expectedStDev: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	expectedOutlier: z.number().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	referenceValueType: z.string().max(10).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	referenceUnits: z.string().max(50).nullable().optional(),
	/**
	 * dataType: decimal
	 */
	detectionLimit: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	upperLimit: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	sampleWeight: z.number().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	sampleWeightUnitCode: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	assayPassFail: z.string().max(1000).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	sysAssayStatus: z.string().max(4).nullable().optional(),
});

/**
 * The base record type for the "dbo.vw_UnifiedQC_Base" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type VwUnifiedQcBaseInsertBaseRecord = z.output<typeof VwUnifiedqcBaseTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.vw_UnifiedQC_Base" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type VwUnifiedQcBaseUpdateBaseRecord = Partial<VwUnifiedQcBaseInsertBaseRecord>;

/**
 * Insert transform for the "dbo.vw_UnifiedQC_Base" table.
 * Maps app cased properties to database fields.
 */
export function transformVwUnifiedQcBaseInsertBaseRecord(data: VwUnifiedQcBaseInsertBaseRecord): {
	Organization: VwUnifiedQcBaseInsertBaseRecord["organization"]
	SampleId: VwUnifiedQcBaseInsertBaseRecord["sampleId"]
	SampleNm: VwUnifiedQcBaseInsertBaseRecord["sampleNm"]
	StandardId: VwUnifiedQcBaseInsertBaseRecord["standardId"]
	OriginalSampleId?: VwUnifiedQcBaseInsertBaseRecord["originalSampleId"]
	QCType: VwUnifiedQcBaseInsertBaseRecord["qCType"]
	SampledDt?: VwUnifiedQcBaseInsertBaseRecord["sampledDt"]
	SampledBy?: VwUnifiedQcBaseInsertBaseRecord["sampledBy"]
	CollarId?: VwUnifiedQcBaseInsertBaseRecord["collarId"]
	Priority?: VwUnifiedQcBaseInsertBaseRecord["priority"]
	Element?: VwUnifiedQcBaseInsertBaseRecord["element"]
	GenericMethod?: VwUnifiedQcBaseInsertBaseRecord["genericMethod"]
	LabElement?: VwUnifiedQcBaseInsertBaseRecord["labElement"]
	UnitCode?: VwUnifiedQcBaseInsertBaseRecord["unitCode"]
	AssayResult?: VwUnifiedQcBaseInsertBaseRecord["assayResult"]
	AssayResultNum?: VwUnifiedQcBaseInsertBaseRecord["assayResultNum"]
	Repeat?: VwUnifiedQcBaseInsertBaseRecord["repeat"]
	BatchNo?: VwUnifiedQcBaseInsertBaseRecord["batchNo"]
	LabCode?: VwUnifiedQcBaseInsertBaseRecord["labCode"]
	LabFinalDt?: VwUnifiedQcBaseInsertBaseRecord["labFinalDt"]
	BatchValidated?: VwUnifiedQcBaseInsertBaseRecord["batchValidated"]
	BatchStatus?: VwUnifiedQcBaseInsertBaseRecord["batchStatus"]
	ExpectedValue?: VwUnifiedQcBaseInsertBaseRecord["expectedValue"]
	ExpectedStDev?: VwUnifiedQcBaseInsertBaseRecord["expectedStDev"]
	ExpectedOutlier?: VwUnifiedQcBaseInsertBaseRecord["expectedOutlier"]
	ReferenceValueType?: VwUnifiedQcBaseInsertBaseRecord["referenceValueType"]
	ReferenceUnits?: VwUnifiedQcBaseInsertBaseRecord["referenceUnits"]
	DetectionLimit?: VwUnifiedQcBaseInsertBaseRecord["detectionLimit"]
	UpperLimit?: VwUnifiedQcBaseInsertBaseRecord["upperLimit"]
	SampleWeight?: VwUnifiedQcBaseInsertBaseRecord["sampleWeight"]
	SampleWeightUnitCode?: VwUnifiedQcBaseInsertBaseRecord["sampleWeightUnitCode"]
	AssayPassFail?: VwUnifiedQcBaseInsertBaseRecord["assayPassFail"]
	sysAssayStatus?: VwUnifiedQcBaseInsertBaseRecord["sysAssayStatus"]
} {
	return {
		Organization: data.organization,
		SampleId: data.sampleId,
		SampleNm: data.sampleNm,
		StandardId: data.standardId,
		OriginalSampleId: data.originalSampleId,
		QCType: data.qCType,
		SampledDt: data.sampledDt,
		SampledBy: data.sampledBy,
		CollarId: data.collarId,
		Priority: data.priority,
		Element: data.element,
		GenericMethod: data.genericMethod,
		LabElement: data.labElement,
		UnitCode: data.unitCode,
		AssayResult: data.assayResult,
		AssayResultNum: data.assayResultNum,
		Repeat: data.repeat,
		BatchNo: data.batchNo,
		LabCode: data.labCode,
		LabFinalDt: data.labFinalDt,
		BatchValidated: data.batchValidated,
		BatchStatus: data.batchStatus,
		ExpectedValue: data.expectedValue,
		ExpectedStDev: data.expectedStDev,
		ExpectedOutlier: data.expectedOutlier,
		ReferenceValueType: data.referenceValueType,
		ReferenceUnits: data.referenceUnits,
		DetectionLimit: data.detectionLimit,
		UpperLimit: data.upperLimit,
		SampleWeight: data.sampleWeight,
		SampleWeightUnitCode: data.sampleWeightUnitCode,
		AssayPassFail: data.assayPassFail,
		sysAssayStatus: data.sysAssayStatus,
	};
}

/**
 * Update transform for the "dbo.vw_UnifiedQC_Base" table.
 * Maps app cased properties to database fields.
 */
export function transformVwUnifiedQcBaseUpdateBaseRecord(data: VwUnifiedQcBaseUpdateBaseRecord): {
	Organization: VwUnifiedQcBaseUpdateBaseRecord["organization"]
	SampleId: VwUnifiedQcBaseUpdateBaseRecord["sampleId"]
	SampleNm: VwUnifiedQcBaseUpdateBaseRecord["sampleNm"]
	StandardId: VwUnifiedQcBaseUpdateBaseRecord["standardId"]
	OriginalSampleId?: VwUnifiedQcBaseUpdateBaseRecord["originalSampleId"]
	QCType: VwUnifiedQcBaseUpdateBaseRecord["qCType"]
	SampledDt?: VwUnifiedQcBaseUpdateBaseRecord["sampledDt"]
	SampledBy?: VwUnifiedQcBaseUpdateBaseRecord["sampledBy"]
	CollarId?: VwUnifiedQcBaseUpdateBaseRecord["collarId"]
	Priority?: VwUnifiedQcBaseUpdateBaseRecord["priority"]
	Element?: VwUnifiedQcBaseUpdateBaseRecord["element"]
	GenericMethod?: VwUnifiedQcBaseUpdateBaseRecord["genericMethod"]
	LabElement?: VwUnifiedQcBaseUpdateBaseRecord["labElement"]
	UnitCode?: VwUnifiedQcBaseUpdateBaseRecord["unitCode"]
	AssayResult?: VwUnifiedQcBaseUpdateBaseRecord["assayResult"]
	AssayResultNum?: VwUnifiedQcBaseUpdateBaseRecord["assayResultNum"]
	Repeat?: VwUnifiedQcBaseUpdateBaseRecord["repeat"]
	BatchNo?: VwUnifiedQcBaseUpdateBaseRecord["batchNo"]
	LabCode?: VwUnifiedQcBaseUpdateBaseRecord["labCode"]
	LabFinalDt?: VwUnifiedQcBaseUpdateBaseRecord["labFinalDt"]
	BatchValidated?: VwUnifiedQcBaseUpdateBaseRecord["batchValidated"]
	BatchStatus?: VwUnifiedQcBaseUpdateBaseRecord["batchStatus"]
	ExpectedValue?: VwUnifiedQcBaseUpdateBaseRecord["expectedValue"]
	ExpectedStDev?: VwUnifiedQcBaseUpdateBaseRecord["expectedStDev"]
	ExpectedOutlier?: VwUnifiedQcBaseUpdateBaseRecord["expectedOutlier"]
	ReferenceValueType?: VwUnifiedQcBaseUpdateBaseRecord["referenceValueType"]
	ReferenceUnits?: VwUnifiedQcBaseUpdateBaseRecord["referenceUnits"]
	DetectionLimit?: VwUnifiedQcBaseUpdateBaseRecord["detectionLimit"]
	UpperLimit?: VwUnifiedQcBaseUpdateBaseRecord["upperLimit"]
	SampleWeight?: VwUnifiedQcBaseUpdateBaseRecord["sampleWeight"]
	SampleWeightUnitCode?: VwUnifiedQcBaseUpdateBaseRecord["sampleWeightUnitCode"]
	AssayPassFail?: VwUnifiedQcBaseUpdateBaseRecord["assayPassFail"]
	sysAssayStatus?: VwUnifiedQcBaseUpdateBaseRecord["sysAssayStatus"]
} {
	return {
		Organization: data.organization,
		SampleId: data.sampleId,
		SampleNm: data.sampleNm,
		StandardId: data.standardId,
		OriginalSampleId: data.originalSampleId,
		QCType: data.qCType,
		SampledDt: data.sampledDt,
		SampledBy: data.sampledBy,
		CollarId: data.collarId,
		Priority: data.priority,
		Element: data.element,
		GenericMethod: data.genericMethod,
		LabElement: data.labElement,
		UnitCode: data.unitCode,
		AssayResult: data.assayResult,
		AssayResultNum: data.assayResultNum,
		Repeat: data.repeat,
		BatchNo: data.batchNo,
		LabCode: data.labCode,
		LabFinalDt: data.labFinalDt,
		BatchValidated: data.batchValidated,
		BatchStatus: data.batchStatus,
		ExpectedValue: data.expectedValue,
		ExpectedStDev: data.expectedStDev,
		ExpectedOutlier: data.expectedOutlier,
		ReferenceValueType: data.referenceValueType,
		ReferenceUnits: data.referenceUnits,
		DetectionLimit: data.detectionLimit,
		UpperLimit: data.upperLimit,
		SampleWeight: data.sampleWeight,
		SampleWeightUnitCode: data.sampleWeightUnitCode,
		AssayPassFail: data.assayPassFail,
		sysAssayStatus: data.sysAssayStatus,
	};
}

/**
 * Insert schema for the "dbo.vw_UnifiedQC_Base" table (after casing transform).
 */
export const VwUnifiedqcBaseTableInsertSchema = VwUnifiedqcBaseTableInsertBaseSchema.transform(transformVwUnifiedQcBaseInsertBaseRecord);

/**
 * Update schema for the "dbo.vw_UnifiedQC_Base" table (after casing transform).
 */
export const VwUnifiedqcBaseTableUpdateSchema = VwUnifiedqcBaseTableInsertBaseSchema.partial().transform(transformVwUnifiedQcBaseUpdateBaseRecord);

type TableInsertRecord = z.input<typeof VwUnifiedqcBaseTableInsertSchema>;
type TableReadRecord = z.output<typeof VwUnifiedqcBaseTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.vw_UnifiedQC_Base" table.
 */
export interface VwUnifiedQcBaseRecord {
	organization: TableReadRecord["organization"]
	sampleId: TableReadRecord["sampleId"]
	sampleNm: TableReadRecord["sampleNm"]
	standardId: TableReadRecord["standardId"]
	originalSampleId?: TableReadRecord["originalSampleId"]
	qCType: TableReadRecord["qCType"]
	sampledDt?: TableReadRecord["sampledDt"]
	sampledBy?: TableReadRecord["sampledBy"]
	collarId?: TableReadRecord["collarId"]
	priority?: TableReadRecord["priority"]
	element?: TableReadRecord["element"]
	genericMethod?: TableReadRecord["genericMethod"]
	labElement?: TableReadRecord["labElement"]
	unitCode?: TableReadRecord["unitCode"]
	assayResult?: TableReadRecord["assayResult"]
	assayResultNum?: TableReadRecord["assayResultNum"]
	repeat?: TableReadRecord["repeat"]
	batchNo?: TableReadRecord["batchNo"]
	labCode?: TableReadRecord["labCode"]
	labFinalDt?: TableReadRecord["labFinalDt"]
	batchValidated?: TableReadRecord["batchValidated"]
	batchStatus?: TableReadRecord["batchStatus"]
	expectedValue?: TableReadRecord["expectedValue"]
	expectedStDev?: TableReadRecord["expectedStDev"]
	expectedOutlier?: TableReadRecord["expectedOutlier"]
	referenceValueType?: TableReadRecord["referenceValueType"]
	referenceUnits?: TableReadRecord["referenceUnits"]
	detectionLimit?: TableReadRecord["detectionLimit"]
	upperLimit?: TableReadRecord["upperLimit"]
	sampleWeight?: TableReadRecord["sampleWeight"]
	sampleWeightUnitCode?: TableReadRecord["sampleWeightUnitCode"]
	assayPassFail?: TableReadRecord["assayPassFail"]
	sysAssayStatus?: TableReadRecord["sysAssayStatus"]
}

/**
 * Insert record (casing transformed) for the "dbo.vw_UnifiedQC_Base" table.
 */
export interface VwUnifiedQcBaseInsertRecord {
	/**
	 * @maxLen: 30
	 */
	organization: TableInsertRecord["organization"]
	sampleId: TableInsertRecord["sampleId"]
	/**
	 * @maxLen: 50
	 */
	sampleNm: TableInsertRecord["sampleNm"]
	/**
	 * @maxLen: 50
	 */
	standardId: TableInsertRecord["standardId"]
	originalSampleId?: TableInsertRecord["originalSampleId"]
	/**
	 * @maxLen: 3
	 */
	qCType: TableInsertRecord["qCType"]
	sampledDt?: TableInsertRecord["sampledDt"]
	/**
	 * @maxLen: 50
	 */
	sampledBy?: TableInsertRecord["sampledBy"]
	collarId?: TableInsertRecord["collarId"]
	priority?: TableInsertRecord["priority"]
	/**
	 * @maxLen: 50
	 */
	element?: TableInsertRecord["element"]
	/**
	 * @maxLen: 50
	 */
	genericMethod?: TableInsertRecord["genericMethod"]
	/**
	 * @maxLen: 50
	 */
	labElement?: TableInsertRecord["labElement"]
	/**
	 * @maxLen: 50
	 */
	unitCode?: TableInsertRecord["unitCode"]
	/**
	 * @maxLen: 20
	 */
	assayResult?: TableInsertRecord["assayResult"]
	assayResultNum?: TableInsertRecord["assayResultNum"]
	/**
	 * @maxLen: 10
	 */
	repeat?: TableInsertRecord["repeat"]
	/**
	 * @maxLen: 50
	 */
	batchNo?: TableInsertRecord["batchNo"]
	/**
	 * @maxLen: 20
	 */
	labCode?: TableInsertRecord["labCode"]
	labFinalDt?: TableInsertRecord["labFinalDt"]
	batchValidated?: TableInsertRecord["batchValidated"]
	/**
	 * @maxLen: 50
	 */
	batchStatus?: TableInsertRecord["batchStatus"]
	expectedValue?: TableInsertRecord["expectedValue"]
	expectedStDev?: TableInsertRecord["expectedStDev"]
	expectedOutlier?: TableInsertRecord["expectedOutlier"]
	/**
	 * @maxLen: 10
	 */
	referenceValueType?: TableInsertRecord["referenceValueType"]
	/**
	 * @maxLen: 50
	 */
	referenceUnits?: TableInsertRecord["referenceUnits"]
	detectionLimit?: TableInsertRecord["detectionLimit"]
	upperLimit?: TableInsertRecord["upperLimit"]
	sampleWeight?: TableInsertRecord["sampleWeight"]
	/**
	 * @maxLen: 50
	 */
	sampleWeightUnitCode?: TableInsertRecord["sampleWeightUnitCode"]
	/**
	 * @maxLen: 1000
	 */
	assayPassFail?: TableInsertRecord["assayPassFail"]
	/**
	 * @maxLen: 4
	 */
	sysAssayStatus?: TableInsertRecord["sysAssayStatus"]
}

/**
 * Updatable record (casing transformed) for the "dbo.vw_UnifiedQC_Base" table.
 */
export type VwUnifiedQcBaseUpdateRecord = Partial<VwUnifiedQcBaseInsertRecord>;
