// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.CoreQuality" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const CoreQualityTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	CoreQualityId: z.any(),
});

/**
 * The base record type for the "dbo.CoreQuality" table.
 * This type represents the raw database record without case transforms.
 */
export type CoreQualityBaseRecord = z.output<typeof CoreQualityTableBaseSchema>;

/**
 * Read transform for the "dbo.CoreQuality" table.
 * Maps database fields to app case properties.
 */
export function transformCoreQualityBaseRecord(data: CoreQualityBaseRecord): {
	code: CoreQualityBaseRecord["Code"]
	sortOrder: CoreQualityBaseRecord["SortOrder"]
	isDefaultInd: CoreQualityBaseRecord["IsDefaultInd"]
	activeInd: CoreQualityBaseRecord["ActiveInd"]
	createdOnDt: CoreQualityBaseRecord["CreatedOnDt"]
	createdBy: CoreQualityBaseRecord["CreatedBy"]
	modifiedOnDt?: CoreQualityBaseRecord["ModifiedOnDt"]
	modifiedBy?: CoreQualityBaseRecord["ModifiedBy"]
	rv: CoreQualityBaseRecord["rv"]
	coreQualityId: CoreQualityBaseRecord["CoreQualityId"]
} {
	return {
		code: data.Code,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		coreQualityId: data.CoreQualityId,
	};
}

/**
 * Read schema for the "dbo.CoreQuality" table (after casing transform).
 */
export const CoreQualityTableSchema = CoreQualityTableBaseSchema.transform(transformCoreQualityBaseRecord);

/**
 * Base insert/write schema for the "dbo.CoreQuality" table (no casing transforms).
 */
export const CoreQualityTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	coreQualityId: z.any().optional(),
});

/**
 * The base record type for the "dbo.CoreQuality" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type CoreQualityInsertBaseRecord = z.output<typeof CoreQualityTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.CoreQuality" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type CoreQualityUpdateBaseRecord = Partial<CoreQualityInsertBaseRecord>;

/**
 * Insert transform for the "dbo.CoreQuality" table.
 * Maps app cased properties to database fields.
 */
export function transformCoreQualityInsertBaseRecord(data: CoreQualityInsertBaseRecord): {
	Code: CoreQualityInsertBaseRecord["code"]
	SortOrder?: CoreQualityInsertBaseRecord["sortOrder"]
	IsDefaultInd?: CoreQualityInsertBaseRecord["isDefaultInd"]
	ActiveInd?: CoreQualityInsertBaseRecord["activeInd"]
	CreatedOnDt?: CoreQualityInsertBaseRecord["createdOnDt"]
	CreatedBy?: CoreQualityInsertBaseRecord["createdBy"]
	ModifiedOnDt?: CoreQualityInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: CoreQualityInsertBaseRecord["modifiedBy"]
	rv: CoreQualityInsertBaseRecord["rv"]
	CoreQualityId?: CoreQualityInsertBaseRecord["coreQualityId"]
} {
	return {
		Code: data.code,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		CoreQualityId: data.coreQualityId,
	};
}

/**
 * Update transform for the "dbo.CoreQuality" table.
 * Maps app cased properties to database fields.
 */
export function transformCoreQualityUpdateBaseRecord(data: CoreQualityUpdateBaseRecord): {
	Code: CoreQualityUpdateBaseRecord["code"]
	SortOrder?: CoreQualityUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: CoreQualityUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: CoreQualityUpdateBaseRecord["activeInd"]
	CreatedOnDt?: CoreQualityUpdateBaseRecord["createdOnDt"]
	CreatedBy?: CoreQualityUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: CoreQualityUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: CoreQualityUpdateBaseRecord["modifiedBy"]
	rv: CoreQualityUpdateBaseRecord["rv"]
	CoreQualityId?: CoreQualityUpdateBaseRecord["coreQualityId"]
} {
	return {
		Code: data.code,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		CoreQualityId: data.coreQualityId,
	};
}

/**
 * Insert schema for the "dbo.CoreQuality" table (after casing transform).
 */
export const CoreQualityTableInsertSchema = CoreQualityTableInsertBaseSchema.transform(transformCoreQualityInsertBaseRecord);

/**
 * Update schema for the "dbo.CoreQuality" table (after casing transform).
 */
export const CoreQualityTableUpdateSchema = CoreQualityTableInsertBaseSchema.partial().transform(transformCoreQualityUpdateBaseRecord);

type TableInsertRecord = z.input<typeof CoreQualityTableInsertSchema>;
type TableReadRecord = z.output<typeof CoreQualityTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.CoreQuality" table.
 */
export interface CoreQualityRecord {
	code: TableReadRecord["code"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	coreQualityId: TableReadRecord["coreQualityId"]
}

/**
 * Insert record (casing transformed) for the "dbo.CoreQuality" table.
 */
export interface CoreQualityInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	coreQualityId?: TableInsertRecord["coreQualityId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.CoreQuality" table.
 */
export type CoreQualityUpdateRecord = Partial<CoreQualityInsertRecord>;
