// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.AutoAssayImportRuleTypes" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const AutoAssayImportRuleTypesTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	AutoAssayImportRuleTypesId: z.any(),
});

/**
 * The base record type for the "dbo.AutoAssayImportRuleTypes" table.
 * This type represents the raw database record without case transforms.
 */
export type AutoAssayImportRuleTypeBaseRecord = z.output<typeof AutoAssayImportRuleTypesTableBaseSchema>;

/**
 * Read transform for the "dbo.AutoAssayImportRuleTypes" table.
 * Maps database fields to app case properties.
 */
export function transformAutoAssayImportRuleTypeBaseRecord(data: AutoAssayImportRuleTypeBaseRecord): {
	code: AutoAssayImportRuleTypeBaseRecord["Code"]
	description?: AutoAssayImportRuleTypeBaseRecord["Description"]
	sortOrder: AutoAssayImportRuleTypeBaseRecord["SortOrder"]
	isDefaultInd: AutoAssayImportRuleTypeBaseRecord["IsDefaultInd"]
	activeInd: AutoAssayImportRuleTypeBaseRecord["ActiveInd"]
	createdOnDt: AutoAssayImportRuleTypeBaseRecord["CreatedOnDt"]
	createdBy: AutoAssayImportRuleTypeBaseRecord["CreatedBy"]
	modifiedOnDt?: AutoAssayImportRuleTypeBaseRecord["ModifiedOnDt"]
	modifiedBy?: AutoAssayImportRuleTypeBaseRecord["ModifiedBy"]
	rv: AutoAssayImportRuleTypeBaseRecord["rv"]
	autoAssayImportRuleTypesId: AutoAssayImportRuleTypeBaseRecord["AutoAssayImportRuleTypesId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		autoAssayImportRuleTypesId: data.AutoAssayImportRuleTypesId,
	};
}

/**
 * Read schema for the "dbo.AutoAssayImportRuleTypes" table (after casing transform).
 */
export const AutoAssayImportRuleTypesTableSchema = AutoAssayImportRuleTypesTableBaseSchema.transform(transformAutoAssayImportRuleTypeBaseRecord);

/**
 * Base insert/write schema for the "dbo.AutoAssayImportRuleTypes" table (no casing transforms).
 */
export const AutoAssayImportRuleTypesTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(10),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(50).nullable().optional(),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	autoAssayImportRuleTypesId: z.any().optional(),
});

/**
 * The base record type for the "dbo.AutoAssayImportRuleTypes" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type AutoAssayImportRuleTypeInsertBaseRecord = z.output<typeof AutoAssayImportRuleTypesTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.AutoAssayImportRuleTypes" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type AutoAssayImportRuleTypeUpdateBaseRecord = Partial<AutoAssayImportRuleTypeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.AutoAssayImportRuleTypes" table.
 * Maps app cased properties to database fields.
 */
export function transformAutoAssayImportRuleTypeInsertBaseRecord(data: AutoAssayImportRuleTypeInsertBaseRecord): {
	Code: AutoAssayImportRuleTypeInsertBaseRecord["code"]
	Description?: AutoAssayImportRuleTypeInsertBaseRecord["description"]
	SortOrder?: AutoAssayImportRuleTypeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: AutoAssayImportRuleTypeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: AutoAssayImportRuleTypeInsertBaseRecord["activeInd"]
	CreatedOnDt?: AutoAssayImportRuleTypeInsertBaseRecord["createdOnDt"]
	CreatedBy?: AutoAssayImportRuleTypeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: AutoAssayImportRuleTypeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: AutoAssayImportRuleTypeInsertBaseRecord["modifiedBy"]
	rv: AutoAssayImportRuleTypeInsertBaseRecord["rv"]
	AutoAssayImportRuleTypesId?: AutoAssayImportRuleTypeInsertBaseRecord["autoAssayImportRuleTypesId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		AutoAssayImportRuleTypesId: data.autoAssayImportRuleTypesId,
	};
}

/**
 * Update transform for the "dbo.AutoAssayImportRuleTypes" table.
 * Maps app cased properties to database fields.
 */
export function transformAutoAssayImportRuleTypeUpdateBaseRecord(data: AutoAssayImportRuleTypeUpdateBaseRecord): {
	Code: AutoAssayImportRuleTypeUpdateBaseRecord["code"]
	Description?: AutoAssayImportRuleTypeUpdateBaseRecord["description"]
	SortOrder?: AutoAssayImportRuleTypeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: AutoAssayImportRuleTypeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: AutoAssayImportRuleTypeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: AutoAssayImportRuleTypeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: AutoAssayImportRuleTypeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: AutoAssayImportRuleTypeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: AutoAssayImportRuleTypeUpdateBaseRecord["modifiedBy"]
	rv: AutoAssayImportRuleTypeUpdateBaseRecord["rv"]
	AutoAssayImportRuleTypesId?: AutoAssayImportRuleTypeUpdateBaseRecord["autoAssayImportRuleTypesId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		AutoAssayImportRuleTypesId: data.autoAssayImportRuleTypesId,
	};
}

/**
 * Insert schema for the "dbo.AutoAssayImportRuleTypes" table (after casing transform).
 */
export const AutoAssayImportRuleTypesTableInsertSchema = AutoAssayImportRuleTypesTableInsertBaseSchema.transform(transformAutoAssayImportRuleTypeInsertBaseRecord);

/**
 * Update schema for the "dbo.AutoAssayImportRuleTypes" table (after casing transform).
 */
export const AutoAssayImportRuleTypesTableUpdateSchema = AutoAssayImportRuleTypesTableInsertBaseSchema.partial().transform(transformAutoAssayImportRuleTypeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof AutoAssayImportRuleTypesTableInsertSchema>;
type TableReadRecord = z.output<typeof AutoAssayImportRuleTypesTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.AutoAssayImportRuleTypes" table.
 */
export interface AutoAssayImportRuleTypeRecord {
	code: TableReadRecord["code"]
	description?: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	autoAssayImportRuleTypesId: TableReadRecord["autoAssayImportRuleTypesId"]
}

/**
 * Insert record (casing transformed) for the "dbo.AutoAssayImportRuleTypes" table.
 */
export interface AutoAssayImportRuleTypeInsertRecord {
	/**
	 * @maxLen: 10
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 50
	 */
	description?: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	autoAssayImportRuleTypesId?: TableInsertRecord["autoAssayImportRuleTypesId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.AutoAssayImportRuleTypes" table.
 */
export type AutoAssayImportRuleTypeUpdateRecord = Partial<AutoAssayImportRuleTypeInsertRecord>;
