// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.StructPTQuality" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const StructPTQualityTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	StructPTQualityId: z.any(),
});

/**
 * The base record type for the "dbo.StructPTQuality" table.
 * This type represents the raw database record without case transforms.
 */
export type StructPtqualityBaseRecord = z.output<typeof StructPTQualityTableBaseSchema>;

/**
 * Read transform for the "dbo.StructPTQuality" table.
 * Maps database fields to app case properties.
 */
export function transformStructPtqualityBaseRecord(data: StructPtqualityBaseRecord): {
	code: StructPtqualityBaseRecord["Code"]
	description: StructPtqualityBaseRecord["Description"]
	sortOrder: StructPtqualityBaseRecord["SortOrder"]
	isDefaultInd: StructPtqualityBaseRecord["IsDefaultInd"]
	activeInd: StructPtqualityBaseRecord["ActiveInd"]
	createdOnDt: StructPtqualityBaseRecord["CreatedOnDt"]
	createdBy: StructPtqualityBaseRecord["CreatedBy"]
	modifiedOnDt?: StructPtqualityBaseRecord["ModifiedOnDt"]
	modifiedBy?: StructPtqualityBaseRecord["ModifiedBy"]
	rv: StructPtqualityBaseRecord["rv"]
	structPTQualityId: StructPtqualityBaseRecord["StructPTQualityId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		structPTQualityId: data.StructPTQualityId,
	};
}

/**
 * Read schema for the "dbo.StructPTQuality" table (after casing transform).
 */
export const StructPTQualityTableSchema = StructPTQualityTableBaseSchema.transform(transformStructPtqualityBaseRecord);

/**
 * Base insert/write schema for the "dbo.StructPTQuality" table (no casing transforms).
 */
export const StructPTQualityTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	structPTQualityId: z.any().optional(),
});

/**
 * The base record type for the "dbo.StructPTQuality" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type StructPtqualityInsertBaseRecord = z.output<typeof StructPTQualityTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.StructPTQuality" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type StructPtqualityUpdateBaseRecord = Partial<StructPtqualityInsertBaseRecord>;

/**
 * Insert transform for the "dbo.StructPTQuality" table.
 * Maps app cased properties to database fields.
 */
export function transformStructPtqualityInsertBaseRecord(data: StructPtqualityInsertBaseRecord): {
	Code: StructPtqualityInsertBaseRecord["code"]
	Description: StructPtqualityInsertBaseRecord["description"]
	SortOrder?: StructPtqualityInsertBaseRecord["sortOrder"]
	IsDefaultInd?: StructPtqualityInsertBaseRecord["isDefaultInd"]
	ActiveInd?: StructPtqualityInsertBaseRecord["activeInd"]
	CreatedOnDt?: StructPtqualityInsertBaseRecord["createdOnDt"]
	CreatedBy?: StructPtqualityInsertBaseRecord["createdBy"]
	ModifiedOnDt?: StructPtqualityInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: StructPtqualityInsertBaseRecord["modifiedBy"]
	rv: StructPtqualityInsertBaseRecord["rv"]
	StructPTQualityId?: StructPtqualityInsertBaseRecord["structPTQualityId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		StructPTQualityId: data.structPTQualityId,
	};
}

/**
 * Update transform for the "dbo.StructPTQuality" table.
 * Maps app cased properties to database fields.
 */
export function transformStructPtqualityUpdateBaseRecord(data: StructPtqualityUpdateBaseRecord): {
	Code: StructPtqualityUpdateBaseRecord["code"]
	Description: StructPtqualityUpdateBaseRecord["description"]
	SortOrder?: StructPtqualityUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: StructPtqualityUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: StructPtqualityUpdateBaseRecord["activeInd"]
	CreatedOnDt?: StructPtqualityUpdateBaseRecord["createdOnDt"]
	CreatedBy?: StructPtqualityUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: StructPtqualityUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: StructPtqualityUpdateBaseRecord["modifiedBy"]
	rv: StructPtqualityUpdateBaseRecord["rv"]
	StructPTQualityId?: StructPtqualityUpdateBaseRecord["structPTQualityId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		StructPTQualityId: data.structPTQualityId,
	};
}

/**
 * Insert schema for the "dbo.StructPTQuality" table (after casing transform).
 */
export const StructPTQualityTableInsertSchema = StructPTQualityTableInsertBaseSchema.transform(transformStructPtqualityInsertBaseRecord);

/**
 * Update schema for the "dbo.StructPTQuality" table (after casing transform).
 */
export const StructPTQualityTableUpdateSchema = StructPTQualityTableInsertBaseSchema.partial().transform(transformStructPtqualityUpdateBaseRecord);

type TableInsertRecord = z.input<typeof StructPTQualityTableInsertSchema>;
type TableReadRecord = z.output<typeof StructPTQualityTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.StructPTQuality" table.
 */
export interface StructPtqualityRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	structPTQualityId: TableReadRecord["structPTQualityId"]
}

/**
 * Insert record (casing transformed) for the "dbo.StructPTQuality" table.
 */
export interface StructPtqualityInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	structPTQualityId?: TableInsertRecord["structPTQualityId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.StructPTQuality" table.
 */
export type StructPtqualityUpdateRecord = Partial<StructPtqualityInsertRecord>;
