// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.vw_MethodPerformanceComparison" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const VwMethodperformancecomparisonTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Element: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	GenericMethod: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	LabCode: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	BatchCount: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	TotalQC: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	StandardCount: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	AvgZScore: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: float
	 */
	StDevZScore: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	OverallFailureRate_Pct: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	StandardFailureRate_Pct: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	BlankFailureRate_Pct: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	AvgDetectionLimit: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	FirstSample: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	LastSample: z.any().nullable().transform(value => value ?? undefined).optional(),
});

/**
 * The base record type for the "dbo.vw_MethodPerformanceComparison" table.
 * This type represents the raw database record without case transforms.
 */
export type VwMethodPerformanceComparisonBaseRecord = z.output<typeof VwMethodperformancecomparisonTableBaseSchema>;

/**
 * Read transform for the "dbo.vw_MethodPerformanceComparison" table.
 * Maps database fields to app case properties.
 */
export function transformVwMethodPerformanceComparisonBaseRecord(data: VwMethodPerformanceComparisonBaseRecord): {
	element?: VwMethodPerformanceComparisonBaseRecord["Element"]
	genericMethod?: VwMethodPerformanceComparisonBaseRecord["GenericMethod"]
	labCode?: VwMethodPerformanceComparisonBaseRecord["LabCode"]
	batchCount?: VwMethodPerformanceComparisonBaseRecord["BatchCount"]
	totalQC?: VwMethodPerformanceComparisonBaseRecord["TotalQC"]
	standardCount?: VwMethodPerformanceComparisonBaseRecord["StandardCount"]
	avgZScore?: VwMethodPerformanceComparisonBaseRecord["AvgZScore"]
	stDevZScore?: VwMethodPerformanceComparisonBaseRecord["StDevZScore"]
	overallfailureratePct?: VwMethodPerformanceComparisonBaseRecord["OverallFailureRate_Pct"]
	standardfailureratePct?: VwMethodPerformanceComparisonBaseRecord["StandardFailureRate_Pct"]
	blankfailureratePct?: VwMethodPerformanceComparisonBaseRecord["BlankFailureRate_Pct"]
	avgDetectionLimit?: VwMethodPerformanceComparisonBaseRecord["AvgDetectionLimit"]
	firstSample?: VwMethodPerformanceComparisonBaseRecord["FirstSample"]
	lastSample?: VwMethodPerformanceComparisonBaseRecord["LastSample"]
} {
	return {
		element: data.Element,
		genericMethod: data.GenericMethod,
		labCode: data.LabCode,
		batchCount: data.BatchCount,
		totalQC: data.TotalQC,
		standardCount: data.StandardCount,
		avgZScore: data.AvgZScore,
		stDevZScore: data.StDevZScore,
		overallfailureratePct: data.OverallFailureRate_Pct,
		standardfailureratePct: data.StandardFailureRate_Pct,
		blankfailureratePct: data.BlankFailureRate_Pct,
		avgDetectionLimit: data.AvgDetectionLimit,
		firstSample: data.FirstSample,
		lastSample: data.LastSample,
	};
}

/**
 * Read schema for the "dbo.vw_MethodPerformanceComparison" table (after casing transform).
 */
export const VwMethodperformancecomparisonTableSchema = VwMethodperformancecomparisonTableBaseSchema.transform(transformVwMethodPerformanceComparisonBaseRecord);

/**
 * Base insert/write schema for the "dbo.vw_MethodPerformanceComparison" table (no casing transforms).
 */
export const VwMethodperformancecomparisonTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	element: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	genericMethod: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	labCode: z.string().max(20).nullable().optional(),
	/**
	 * dataType: int
	 */
	batchCount: z.number().int().nullable().optional(),
	/**
	 * dataType: int
	 */
	totalQC: z.number().int().nullable().optional(),
	/**
	 * dataType: int
	 */
	standardCount: z.number().int().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	avgZScore: z.number().nullable().optional(),
	/**
	 * dataType: float
	 */
	stDevZScore: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	overallfailureratePct: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	standardfailureratePct: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	blankfailureratePct: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	avgDetectionLimit: z.number().nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	firstSample: z.any().nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	lastSample: z.any().nullable().optional(),
});

/**
 * The base record type for the "dbo.vw_MethodPerformanceComparison" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type VwMethodPerformanceComparisonInsertBaseRecord = z.output<typeof VwMethodperformancecomparisonTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.vw_MethodPerformanceComparison" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type VwMethodPerformanceComparisonUpdateBaseRecord = Partial<VwMethodPerformanceComparisonInsertBaseRecord>;

/**
 * Insert transform for the "dbo.vw_MethodPerformanceComparison" table.
 * Maps app cased properties to database fields.
 */
export function transformVwMethodPerformanceComparisonInsertBaseRecord(data: VwMethodPerformanceComparisonInsertBaseRecord): {
	Element?: VwMethodPerformanceComparisonInsertBaseRecord["element"]
	GenericMethod?: VwMethodPerformanceComparisonInsertBaseRecord["genericMethod"]
	LabCode?: VwMethodPerformanceComparisonInsertBaseRecord["labCode"]
	BatchCount?: VwMethodPerformanceComparisonInsertBaseRecord["batchCount"]
	TotalQC?: VwMethodPerformanceComparisonInsertBaseRecord["totalQC"]
	StandardCount?: VwMethodPerformanceComparisonInsertBaseRecord["standardCount"]
	AvgZScore?: VwMethodPerformanceComparisonInsertBaseRecord["avgZScore"]
	StDevZScore?: VwMethodPerformanceComparisonInsertBaseRecord["stDevZScore"]
	OverallFailureRate_Pct?: VwMethodPerformanceComparisonInsertBaseRecord["overallfailureratePct"]
	StandardFailureRate_Pct?: VwMethodPerformanceComparisonInsertBaseRecord["standardfailureratePct"]
	BlankFailureRate_Pct?: VwMethodPerformanceComparisonInsertBaseRecord["blankfailureratePct"]
	AvgDetectionLimit?: VwMethodPerformanceComparisonInsertBaseRecord["avgDetectionLimit"]
	FirstSample?: VwMethodPerformanceComparisonInsertBaseRecord["firstSample"]
	LastSample?: VwMethodPerformanceComparisonInsertBaseRecord["lastSample"]
} {
	return {
		Element: data.element,
		GenericMethod: data.genericMethod,
		LabCode: data.labCode,
		BatchCount: data.batchCount,
		TotalQC: data.totalQC,
		StandardCount: data.standardCount,
		AvgZScore: data.avgZScore,
		StDevZScore: data.stDevZScore,
		OverallFailureRate_Pct: data.overallfailureratePct,
		StandardFailureRate_Pct: data.standardfailureratePct,
		BlankFailureRate_Pct: data.blankfailureratePct,
		AvgDetectionLimit: data.avgDetectionLimit,
		FirstSample: data.firstSample,
		LastSample: data.lastSample,
	};
}

/**
 * Update transform for the "dbo.vw_MethodPerformanceComparison" table.
 * Maps app cased properties to database fields.
 */
export function transformVwMethodPerformanceComparisonUpdateBaseRecord(data: VwMethodPerformanceComparisonUpdateBaseRecord): {
	Element?: VwMethodPerformanceComparisonUpdateBaseRecord["element"]
	GenericMethod?: VwMethodPerformanceComparisonUpdateBaseRecord["genericMethod"]
	LabCode?: VwMethodPerformanceComparisonUpdateBaseRecord["labCode"]
	BatchCount?: VwMethodPerformanceComparisonUpdateBaseRecord["batchCount"]
	TotalQC?: VwMethodPerformanceComparisonUpdateBaseRecord["totalQC"]
	StandardCount?: VwMethodPerformanceComparisonUpdateBaseRecord["standardCount"]
	AvgZScore?: VwMethodPerformanceComparisonUpdateBaseRecord["avgZScore"]
	StDevZScore?: VwMethodPerformanceComparisonUpdateBaseRecord["stDevZScore"]
	OverallFailureRate_Pct?: VwMethodPerformanceComparisonUpdateBaseRecord["overallfailureratePct"]
	StandardFailureRate_Pct?: VwMethodPerformanceComparisonUpdateBaseRecord["standardfailureratePct"]
	BlankFailureRate_Pct?: VwMethodPerformanceComparisonUpdateBaseRecord["blankfailureratePct"]
	AvgDetectionLimit?: VwMethodPerformanceComparisonUpdateBaseRecord["avgDetectionLimit"]
	FirstSample?: VwMethodPerformanceComparisonUpdateBaseRecord["firstSample"]
	LastSample?: VwMethodPerformanceComparisonUpdateBaseRecord["lastSample"]
} {
	return {
		Element: data.element,
		GenericMethod: data.genericMethod,
		LabCode: data.labCode,
		BatchCount: data.batchCount,
		TotalQC: data.totalQC,
		StandardCount: data.standardCount,
		AvgZScore: data.avgZScore,
		StDevZScore: data.stDevZScore,
		OverallFailureRate_Pct: data.overallfailureratePct,
		StandardFailureRate_Pct: data.standardfailureratePct,
		BlankFailureRate_Pct: data.blankfailureratePct,
		AvgDetectionLimit: data.avgDetectionLimit,
		FirstSample: data.firstSample,
		LastSample: data.lastSample,
	};
}

/**
 * Insert schema for the "dbo.vw_MethodPerformanceComparison" table (after casing transform).
 */
export const VwMethodperformancecomparisonTableInsertSchema = VwMethodperformancecomparisonTableInsertBaseSchema.transform(transformVwMethodPerformanceComparisonInsertBaseRecord);

/**
 * Update schema for the "dbo.vw_MethodPerformanceComparison" table (after casing transform).
 */
export const VwMethodperformancecomparisonTableUpdateSchema = VwMethodperformancecomparisonTableInsertBaseSchema.partial().transform(transformVwMethodPerformanceComparisonUpdateBaseRecord);

type TableInsertRecord = z.input<typeof VwMethodperformancecomparisonTableInsertSchema>;
type TableReadRecord = z.output<typeof VwMethodperformancecomparisonTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.vw_MethodPerformanceComparison" table.
 */
export interface VwMethodPerformanceComparisonRecord {
	element?: TableReadRecord["element"]
	genericMethod?: TableReadRecord["genericMethod"]
	labCode?: TableReadRecord["labCode"]
	batchCount?: TableReadRecord["batchCount"]
	totalQC?: TableReadRecord["totalQC"]
	standardCount?: TableReadRecord["standardCount"]
	avgZScore?: TableReadRecord["avgZScore"]
	stDevZScore?: TableReadRecord["stDevZScore"]
	overallfailureratePct?: TableReadRecord["overallfailureratePct"]
	standardfailureratePct?: TableReadRecord["standardfailureratePct"]
	blankfailureratePct?: TableReadRecord["blankfailureratePct"]
	avgDetectionLimit?: TableReadRecord["avgDetectionLimit"]
	firstSample?: TableReadRecord["firstSample"]
	lastSample?: TableReadRecord["lastSample"]
}

/**
 * Insert record (casing transformed) for the "dbo.vw_MethodPerformanceComparison" table.
 */
export interface VwMethodPerformanceComparisonInsertRecord {
	/**
	 * @maxLen: 50
	 */
	element?: TableInsertRecord["element"]
	/**
	 * @maxLen: 50
	 */
	genericMethod?: TableInsertRecord["genericMethod"]
	/**
	 * @maxLen: 20
	 */
	labCode?: TableInsertRecord["labCode"]
	batchCount?: TableInsertRecord["batchCount"]
	totalQC?: TableInsertRecord["totalQC"]
	standardCount?: TableInsertRecord["standardCount"]
	avgZScore?: TableInsertRecord["avgZScore"]
	stDevZScore?: TableInsertRecord["stDevZScore"]
	overallfailureratePct?: TableInsertRecord["overallfailureratePct"]
	standardfailureratePct?: TableInsertRecord["standardfailureratePct"]
	blankfailureratePct?: TableInsertRecord["blankfailureratePct"]
	avgDetectionLimit?: TableInsertRecord["avgDetectionLimit"]
	firstSample?: TableInsertRecord["firstSample"]
	lastSample?: TableInsertRecord["lastSample"]
}

/**
 * Updatable record (casing transformed) for the "dbo.vw_MethodPerformanceComparison" table.
 */
export type VwMethodPerformanceComparisonUpdateRecord = Partial<VwMethodPerformanceComparisonInsertRecord>;
