// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.FractureStyle" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const FractureStyleTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	FractureStyleId: z.any(),
});

/**
 * The base record type for the "dbo.FractureStyle" table.
 * This type represents the raw database record without case transforms.
 */
export type FractureStyleBaseRecord = z.output<typeof FractureStyleTableBaseSchema>;

/**
 * Read transform for the "dbo.FractureStyle" table.
 * Maps database fields to app case properties.
 */
export function transformFractureStyleBaseRecord(data: FractureStyleBaseRecord): {
	code: FractureStyleBaseRecord["Code"]
	description: FractureStyleBaseRecord["Description"]
	sortOrder: FractureStyleBaseRecord["SortOrder"]
	isDefaultInd: FractureStyleBaseRecord["IsDefaultInd"]
	activeInd: FractureStyleBaseRecord["ActiveInd"]
	createdOnDt: FractureStyleBaseRecord["CreatedOnDt"]
	createdBy: FractureStyleBaseRecord["CreatedBy"]
	modifiedOnDt?: FractureStyleBaseRecord["ModifiedOnDt"]
	modifiedBy?: FractureStyleBaseRecord["ModifiedBy"]
	rv: FractureStyleBaseRecord["rv"]
	fractureStyleId: FractureStyleBaseRecord["FractureStyleId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		fractureStyleId: data.FractureStyleId,
	};
}

/**
 * Read schema for the "dbo.FractureStyle" table (after casing transform).
 */
export const FractureStyleTableSchema = FractureStyleTableBaseSchema.transform(transformFractureStyleBaseRecord);

/**
 * Base insert/write schema for the "dbo.FractureStyle" table (no casing transforms).
 */
export const FractureStyleTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	fractureStyleId: z.any().optional(),
});

/**
 * The base record type for the "dbo.FractureStyle" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type FractureStyleInsertBaseRecord = z.output<typeof FractureStyleTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.FractureStyle" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type FractureStyleUpdateBaseRecord = Partial<FractureStyleInsertBaseRecord>;

/**
 * Insert transform for the "dbo.FractureStyle" table.
 * Maps app cased properties to database fields.
 */
export function transformFractureStyleInsertBaseRecord(data: FractureStyleInsertBaseRecord): {
	Code: FractureStyleInsertBaseRecord["code"]
	Description: FractureStyleInsertBaseRecord["description"]
	SortOrder?: FractureStyleInsertBaseRecord["sortOrder"]
	IsDefaultInd?: FractureStyleInsertBaseRecord["isDefaultInd"]
	ActiveInd?: FractureStyleInsertBaseRecord["activeInd"]
	CreatedOnDt?: FractureStyleInsertBaseRecord["createdOnDt"]
	CreatedBy?: FractureStyleInsertBaseRecord["createdBy"]
	ModifiedOnDt?: FractureStyleInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: FractureStyleInsertBaseRecord["modifiedBy"]
	rv: FractureStyleInsertBaseRecord["rv"]
	FractureStyleId?: FractureStyleInsertBaseRecord["fractureStyleId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		FractureStyleId: data.fractureStyleId,
	};
}

/**
 * Update transform for the "dbo.FractureStyle" table.
 * Maps app cased properties to database fields.
 */
export function transformFractureStyleUpdateBaseRecord(data: FractureStyleUpdateBaseRecord): {
	Code: FractureStyleUpdateBaseRecord["code"]
	Description: FractureStyleUpdateBaseRecord["description"]
	SortOrder?: FractureStyleUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: FractureStyleUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: FractureStyleUpdateBaseRecord["activeInd"]
	CreatedOnDt?: FractureStyleUpdateBaseRecord["createdOnDt"]
	CreatedBy?: FractureStyleUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: FractureStyleUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: FractureStyleUpdateBaseRecord["modifiedBy"]
	rv: FractureStyleUpdateBaseRecord["rv"]
	FractureStyleId?: FractureStyleUpdateBaseRecord["fractureStyleId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		FractureStyleId: data.fractureStyleId,
	};
}

/**
 * Insert schema for the "dbo.FractureStyle" table (after casing transform).
 */
export const FractureStyleTableInsertSchema = FractureStyleTableInsertBaseSchema.transform(transformFractureStyleInsertBaseRecord);

/**
 * Update schema for the "dbo.FractureStyle" table (after casing transform).
 */
export const FractureStyleTableUpdateSchema = FractureStyleTableInsertBaseSchema.partial().transform(transformFractureStyleUpdateBaseRecord);

type TableInsertRecord = z.input<typeof FractureStyleTableInsertSchema>;
type TableReadRecord = z.output<typeof FractureStyleTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.FractureStyle" table.
 */
export interface FractureStyleRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	fractureStyleId: TableReadRecord["fractureStyleId"]
}

/**
 * Insert record (casing transformed) for the "dbo.FractureStyle" table.
 */
export interface FractureStyleInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	fractureStyleId?: TableInsertRecord["fractureStyleId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.FractureStyle" table.
 */
export type FractureStyleUpdateRecord = Partial<FractureStyleInsertRecord>;
