/**
 * Sample-Specific Column Definition Bundles
 *
 * Reusable column bundles for Sample grid sections.
 * Builds on top of COMMON_COLUMNS and column factories.
 */

import type { ColDef } from "ag-grid-enterprise";
import type { LookupOption } from "./column-factories";
import type { SampleData } from "../validation/sample-schemas";
import { createNumericColumn } from "./column-factories";

/**
 * Sample-specific column bundles
 */
export const SAMPLE_COLUMNS = {
	/**
	 * Sample identification bundle (SampleNm, RodNo)
	 * Core fields that identify a sample
	 */
	identification: (isReadOnly = false): ColDef<SampleData>[] => [
		{
			field: "SampleNm",
			headerName: "Sample ID",
			minWidth: 160,
			width: 160,
			pinned: "left",
			editable: (params) => {
				// Can't edit if loaded from DB (RowStatus > 0)
				if (params.data && params.data.RowStatus > 0) {
					return false;
				}
				return !isReadOnly;
			},
			filter: "agTextColumnFilter",
			cellStyle: (params) => {
				// Gray out if from DB (not editable)
				if (params.data && params.data.RowStatus > 0) {
					return { backgroundColor: "#f5f5f5" };
				}
				return null;
			},
		},
		{
			field: "RodNo",
			headerName: "Rod #",
			minWidth: 80,
			width: 80,
			editable: !isReadOnly,
			cellDataType: "number",
			filter: "agNumberColumnFilter",
		},
	],

	/**
	 * Interval length column (calculated from DepthTo - DepthFrom)
	 * Read-only calculated field
	 */
	intervalLength: (): ColDef<SampleData> => ({
		field: "IntervalLength",
		headerName: "Interval",
		minWidth: 90,
		width: 90,
		editable: false,
		cellDataType: "number",
		cellStyle: { backgroundColor: "#f0f0f0", textAlign: "right" },
		filter: "agNumberColumnFilter",
		valueGetter: (params) => {
			const from = params.data?.DepthFrom;
			const to = params.data?.DepthTo;
			if (typeof from === "number" && typeof to === "number") {
				return to - from;
			}
			return params.data?.IntervalLength || 0;
		},
		valueFormatter: (params) => {
			return params.value != null && params.data?.DepthTo
				? params.value.toFixed(2)
				: "";
		},
	}),

	/**
	 * Sample classification column (read-only, auto-generated by QAQC)
	 * Shows ORIG, BLK, STD, PREPDUP, FDUP
	 */
	classification: (): ColDef<SampleData> => ({
		field: "SampleClassification",
		headerName: "Classification",
		minWidth: 140,
		width: 140,
		editable: false,
		filter: "agTextColumnFilter",
		suppressFillHandle: true,
		cellStyle: { backgroundColor: "#f0f0f0" },
	}),

	/**
	 * QAQC reference column (StandardId for STD/BLK, OriginalSampleNm for duplicates)
	 * Smart column that shows different editor based on classification
	 */
	qaqcReference: (
		standardOptions: LookupOption[],
		standardBlankOptions: LookupOption[],
		isReadOnly = false,
	): ColDef<SampleData> => ({
		headerName: "Reference",
		minWidth: 110,
		width: 110,
		editable: !isReadOnly,
		valueGetter: params =>
			params.data?.StandardId ?? params.data?.OriginalSampleNm,
		cellEditor: "agRichSelectCellEditor",
		cellEditorParams: (params: any) => {
			const classification = params.data?.SampleClassification;
			switch (classification) {
				case "STD":
					return { values: standardOptions.map(opt => opt.value) };
				case "BLK":
					return { values: standardBlankOptions.map(opt => opt.value) };
				default:
					return { values: [] };
			}
		},
		valueSetter: (params) => {
			const classification = params.data?.SampleClassification;
			if (classification === "STD" || classification === "BLK") {
				params.data.StandardId = params.newValue;
			}
			return true;
		},
	}),

	/**
	 * Weight columns bundle (all sample weights in kg)
	 * Consistent formatting and validation
	 */
	weights: (isReadOnly = false): ColDef<SampleData>[] => [
		createNumericColumn("LabSpWeight", "Lab Sp (kg)", isReadOnly, 2, 110),
		createNumericColumn("WitSpWeight", "Wit Sp (kg)", isReadOnly, 2, 110),
		createNumericColumn("LogSpWeight", "Log Sp (kg)", isReadOnly, 2, 110),
		createNumericColumn("SampleWeight", "Sample Wt (kg)", isReadOnly, 2, 130),
		createNumericColumn("FieldSampleWeight", "Field Wt (kg)", isReadOnly, 2, 120),
	],

	/**
	 * Recovery columns bundle
	 * Subjective recovery percentage
	 */
	recovery: (
		recoveryOptions: LookupOption[],
		isReadOnly = false,
	): ColDef<SampleData>[] => [
			{
				field: "SubjectiveRecovery",
				headerName: "Subj Rec (%)",
				minWidth: 120,
				width: 120,
				editable: !isReadOnly,
				cellEditor: "agRichSelectCellEditor",
				cellEditorParams: {
					values: recoveryOptions.map(opt => opt.value),
				},
				filter: "agSetColumnFilter",
				filterParams: {
					excelMode: "windows",
					values: recoveryOptions.map(opt => opt.value),
				},
				valueFormatter: (params) => {
					const option = recoveryOptions.find(opt => opt.value === params.value);
					return option ? option.label : params.value || "";
				},
			},
		],
};

/**
 * Helper to create sample classification filter values
 */
export const SAMPLE_CLASSIFICATION_VALUES = [
	"ORIG", // Original sample
	"BLK", // Blank
	"STD", // Standard
	"PREPDUP", // Preparation duplicate
	"FDUP", // Field duplicate
];

/**
 * Helper to check if sample is a QAQC sample
 */
export function isQaqcSample(sample: SampleData | undefined): boolean {
	if (!sample?.SampleClassification)
		return false;
	return ["BLK", "STD", "PREPDUP", "FDUP"].includes(sample.SampleClassification);
}

/**
 * Helper to check if sample is a regular (non-QAQC) sample
 */
export function isRegularSample(sample: SampleData | undefined): boolean {
	return !isQaqcSample(sample);
}
