// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.PtMagSusLog" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const PtMagSusLogTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	PtMagSusLogId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	Organization: z.string(),
	/**
	 * dataType: uniqueidentifier
	 */
	PtLoggingEventId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	SampleType: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Reading1_SI: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Reading2_SI: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Reading3_SI: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	Ave_Reading_SI: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Instrument: z.string(),
	/**
	 * dataType: nvarchar
	 */
	InstrumentFactorCode: z.string(),
	/**
	 * dataType: decimal
	 */
	MagSus_SI: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ReadBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	ReadDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	DataSource: z.string(),
	/**
	 * dataType: binary
	 */
	migrationRv: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	MigrationId: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ReportIncludeInd: z.any(),
	/**
	 * dataType: tinyint
	 */
	ValidationStatus: z.number(),
	/**
	 * dataType: nvarchar
	 */
	ValidationErrors: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: tinyint
	 */
	RowStatus: z.number(),
	/**
	 * dataType: uniqueidentifier
	 */
	SupersededById: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.PtMagSusLog" table.
 * This type represents the raw database record without case transforms.
 */
export type PtMagSusLogBaseRecord = z.output<typeof PtMagSusLogTableBaseSchema>;

/**
 * Read transform for the "dbo.PtMagSusLog" table.
 * Maps database fields to app case properties.
 */
export function transformPtMagSusLogBaseRecord(data: PtMagSusLogBaseRecord): {
	ptMagSusLogId: PtMagSusLogBaseRecord["PtMagSusLogId"]
	organization: PtMagSusLogBaseRecord["Organization"]
	ptLoggingEventId: PtMagSusLogBaseRecord["PtLoggingEventId"]
	sampleType?: PtMagSusLogBaseRecord["SampleType"]
	reading1Si?: PtMagSusLogBaseRecord["Reading1_SI"]
	reading2Si?: PtMagSusLogBaseRecord["Reading2_SI"]
	reading3Si?: PtMagSusLogBaseRecord["Reading3_SI"]
	aveReadingSi?: PtMagSusLogBaseRecord["Ave_Reading_SI"]
	instrument: PtMagSusLogBaseRecord["Instrument"]
	instrumentFactorCode: PtMagSusLogBaseRecord["InstrumentFactorCode"]
	magsusSi?: PtMagSusLogBaseRecord["MagSus_SI"]
	readBy?: PtMagSusLogBaseRecord["ReadBy"]
	readDt?: PtMagSusLogBaseRecord["ReadDt"]
	dataSource: PtMagSusLogBaseRecord["DataSource"]
	migrationRv?: PtMagSusLogBaseRecord["migrationRv"]
	migrationId?: PtMagSusLogBaseRecord["MigrationId"]
	reportIncludeInd: PtMagSusLogBaseRecord["ReportIncludeInd"]
	validationStatus: PtMagSusLogBaseRecord["ValidationStatus"]
	validationErrors?: PtMagSusLogBaseRecord["ValidationErrors"]
	rowStatus: PtMagSusLogBaseRecord["RowStatus"]
	supersededById?: PtMagSusLogBaseRecord["SupersededById"]
	activeInd: PtMagSusLogBaseRecord["ActiveInd"]
	createdOnDt: PtMagSusLogBaseRecord["CreatedOnDt"]
	createdBy: PtMagSusLogBaseRecord["CreatedBy"]
	modifiedOnDt?: PtMagSusLogBaseRecord["ModifiedOnDt"]
	modifiedBy?: PtMagSusLogBaseRecord["ModifiedBy"]
	rv: PtMagSusLogBaseRecord["rv"]
} {
	return {
		ptMagSusLogId: data.PtMagSusLogId,
		organization: data.Organization,
		ptLoggingEventId: data.PtLoggingEventId,
		sampleType: data.SampleType,
		reading1Si: data.Reading1_SI,
		reading2Si: data.Reading2_SI,
		reading3Si: data.Reading3_SI,
		aveReadingSi: data.Ave_Reading_SI,
		instrument: data.Instrument,
		instrumentFactorCode: data.InstrumentFactorCode,
		magsusSi: data.MagSus_SI,
		readBy: data.ReadBy,
		readDt: data.ReadDt,
		dataSource: data.DataSource,
		migrationRv: data.migrationRv,
		migrationId: data.MigrationId,
		reportIncludeInd: data.ReportIncludeInd,
		validationStatus: data.ValidationStatus,
		validationErrors: data.ValidationErrors,
		rowStatus: data.RowStatus,
		supersededById: data.SupersededById,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.PtMagSusLog" table (after casing transform).
 */
export const PtMagSusLogTableSchema = PtMagSusLogTableBaseSchema.transform(transformPtMagSusLogBaseRecord);

/**
 * Base insert/write schema for the "dbo.PtMagSusLog" table (no casing transforms).
 */
export const PtMagSusLogTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	ptMagSusLogId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	organization: z.string().max(30),
	/**
	 * dataType: uniqueidentifier
	 */
	ptLoggingEventId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	sampleType: z.string().max(50).nullable().optional(),
	/**
	 * dataType: decimal
	 */
	reading1Si: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	reading2Si: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	reading3Si: z.number().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	aveReadingSi: z.number().nullable().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (N'NR')
	 */
	instrument: z.string().max(50).optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (N'NR')
	 */
	instrumentFactorCode: z.string().max(50).optional(),
	/**
	 * dataType: decimal
	 */
	magsusSi: z.number().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	readBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	readDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	dataSource: z.string().max(255),
	/**
	 * dataType: binary
	 */
	migrationRv: z.any().nullable().optional(),
	/**
	 * dataType: int
	 */
	migrationId: z.number().int().nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	reportIncludeInd: z.any().optional(),
	/**
	 * dataType: tinyint
	 * defaultValue: ((0))
	 */
	validationStatus: z.number().int().optional(),
	/**
	 * dataType: nvarchar
	 */
	validationErrors: z.string().max(4000).nullable().optional(),
	/**
	 * dataType: tinyint
	 * defaultValue: ((0))
	 */
	rowStatus: z.number().int().optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	supersededById: z.any().nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.PtMagSusLog" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type PtMagSusLogInsertBaseRecord = z.output<typeof PtMagSusLogTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.PtMagSusLog" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type PtMagSusLogUpdateBaseRecord = Partial<PtMagSusLogInsertBaseRecord>;

/**
 * Insert transform for the "dbo.PtMagSusLog" table.
 * Maps app cased properties to database fields.
 */
export function transformPtMagSusLogInsertBaseRecord(data: PtMagSusLogInsertBaseRecord): {
	PtMagSusLogId?: PtMagSusLogInsertBaseRecord["ptMagSusLogId"]
	Organization: PtMagSusLogInsertBaseRecord["organization"]
	PtLoggingEventId: PtMagSusLogInsertBaseRecord["ptLoggingEventId"]
	SampleType?: PtMagSusLogInsertBaseRecord["sampleType"]
	Reading1_SI?: PtMagSusLogInsertBaseRecord["reading1Si"]
	Reading2_SI?: PtMagSusLogInsertBaseRecord["reading2Si"]
	Reading3_SI?: PtMagSusLogInsertBaseRecord["reading3Si"]
	Ave_Reading_SI?: PtMagSusLogInsertBaseRecord["aveReadingSi"]
	Instrument?: PtMagSusLogInsertBaseRecord["instrument"]
	InstrumentFactorCode?: PtMagSusLogInsertBaseRecord["instrumentFactorCode"]
	MagSus_SI?: PtMagSusLogInsertBaseRecord["magsusSi"]
	ReadBy?: PtMagSusLogInsertBaseRecord["readBy"]
	ReadDt?: PtMagSusLogInsertBaseRecord["readDt"]
	DataSource: PtMagSusLogInsertBaseRecord["dataSource"]
	migrationRv?: PtMagSusLogInsertBaseRecord["migrationRv"]
	MigrationId?: PtMagSusLogInsertBaseRecord["migrationId"]
	ReportIncludeInd?: PtMagSusLogInsertBaseRecord["reportIncludeInd"]
	ValidationStatus?: PtMagSusLogInsertBaseRecord["validationStatus"]
	ValidationErrors?: PtMagSusLogInsertBaseRecord["validationErrors"]
	RowStatus?: PtMagSusLogInsertBaseRecord["rowStatus"]
	SupersededById?: PtMagSusLogInsertBaseRecord["supersededById"]
	ActiveInd?: PtMagSusLogInsertBaseRecord["activeInd"]
	CreatedOnDt?: PtMagSusLogInsertBaseRecord["createdOnDt"]
	CreatedBy?: PtMagSusLogInsertBaseRecord["createdBy"]
	ModifiedOnDt?: PtMagSusLogInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: PtMagSusLogInsertBaseRecord["modifiedBy"]
	rv: PtMagSusLogInsertBaseRecord["rv"]
} {
	return {
		PtMagSusLogId: data.ptMagSusLogId,
		Organization: data.organization,
		PtLoggingEventId: data.ptLoggingEventId,
		SampleType: data.sampleType,
		Reading1_SI: data.reading1Si,
		Reading2_SI: data.reading2Si,
		Reading3_SI: data.reading3Si,
		Ave_Reading_SI: data.aveReadingSi,
		Instrument: data.instrument,
		InstrumentFactorCode: data.instrumentFactorCode,
		MagSus_SI: data.magsusSi,
		ReadBy: data.readBy,
		ReadDt: data.readDt,
		DataSource: data.dataSource,
		migrationRv: data.migrationRv,
		MigrationId: data.migrationId,
		ReportIncludeInd: data.reportIncludeInd,
		ValidationStatus: data.validationStatus,
		ValidationErrors: data.validationErrors,
		RowStatus: data.rowStatus,
		SupersededById: data.supersededById,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.PtMagSusLog" table.
 * Maps app cased properties to database fields.
 */
export function transformPtMagSusLogUpdateBaseRecord(data: PtMagSusLogUpdateBaseRecord): {
	PtMagSusLogId?: PtMagSusLogUpdateBaseRecord["ptMagSusLogId"]
	Organization: PtMagSusLogUpdateBaseRecord["organization"]
	PtLoggingEventId: PtMagSusLogUpdateBaseRecord["ptLoggingEventId"]
	SampleType?: PtMagSusLogUpdateBaseRecord["sampleType"]
	Reading1_SI?: PtMagSusLogUpdateBaseRecord["reading1Si"]
	Reading2_SI?: PtMagSusLogUpdateBaseRecord["reading2Si"]
	Reading3_SI?: PtMagSusLogUpdateBaseRecord["reading3Si"]
	Ave_Reading_SI?: PtMagSusLogUpdateBaseRecord["aveReadingSi"]
	Instrument?: PtMagSusLogUpdateBaseRecord["instrument"]
	InstrumentFactorCode?: PtMagSusLogUpdateBaseRecord["instrumentFactorCode"]
	MagSus_SI?: PtMagSusLogUpdateBaseRecord["magsusSi"]
	ReadBy?: PtMagSusLogUpdateBaseRecord["readBy"]
	ReadDt?: PtMagSusLogUpdateBaseRecord["readDt"]
	DataSource: PtMagSusLogUpdateBaseRecord["dataSource"]
	migrationRv?: PtMagSusLogUpdateBaseRecord["migrationRv"]
	MigrationId?: PtMagSusLogUpdateBaseRecord["migrationId"]
	ReportIncludeInd?: PtMagSusLogUpdateBaseRecord["reportIncludeInd"]
	ValidationStatus?: PtMagSusLogUpdateBaseRecord["validationStatus"]
	ValidationErrors?: PtMagSusLogUpdateBaseRecord["validationErrors"]
	RowStatus?: PtMagSusLogUpdateBaseRecord["rowStatus"]
	SupersededById?: PtMagSusLogUpdateBaseRecord["supersededById"]
	ActiveInd?: PtMagSusLogUpdateBaseRecord["activeInd"]
	CreatedOnDt?: PtMagSusLogUpdateBaseRecord["createdOnDt"]
	CreatedBy?: PtMagSusLogUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: PtMagSusLogUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: PtMagSusLogUpdateBaseRecord["modifiedBy"]
	rv: PtMagSusLogUpdateBaseRecord["rv"]
} {
	return {
		PtMagSusLogId: data.ptMagSusLogId,
		Organization: data.organization,
		PtLoggingEventId: data.ptLoggingEventId,
		SampleType: data.sampleType,
		Reading1_SI: data.reading1Si,
		Reading2_SI: data.reading2Si,
		Reading3_SI: data.reading3Si,
		Ave_Reading_SI: data.aveReadingSi,
		Instrument: data.instrument,
		InstrumentFactorCode: data.instrumentFactorCode,
		MagSus_SI: data.magsusSi,
		ReadBy: data.readBy,
		ReadDt: data.readDt,
		DataSource: data.dataSource,
		migrationRv: data.migrationRv,
		MigrationId: data.migrationId,
		ReportIncludeInd: data.reportIncludeInd,
		ValidationStatus: data.validationStatus,
		ValidationErrors: data.validationErrors,
		RowStatus: data.rowStatus,
		SupersededById: data.supersededById,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.PtMagSusLog" table (after casing transform).
 */
export const PtMagSusLogTableInsertSchema = PtMagSusLogTableInsertBaseSchema.transform(transformPtMagSusLogInsertBaseRecord);

/**
 * Update schema for the "dbo.PtMagSusLog" table (after casing transform).
 */
export const PtMagSusLogTableUpdateSchema = PtMagSusLogTableInsertBaseSchema.partial().transform(transformPtMagSusLogUpdateBaseRecord);

type TableInsertRecord = z.input<typeof PtMagSusLogTableInsertSchema>;
type TableReadRecord = z.output<typeof PtMagSusLogTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.PtMagSusLog" table.
 */
export interface PtMagSusLogRecord {
	ptMagSusLogId: TableReadRecord["ptMagSusLogId"]
	organization: TableReadRecord["organization"]
	ptLoggingEventId: TableReadRecord["ptLoggingEventId"]
	sampleType?: TableReadRecord["sampleType"]
	reading1Si?: TableReadRecord["reading1Si"]
	reading2Si?: TableReadRecord["reading2Si"]
	reading3Si?: TableReadRecord["reading3Si"]
	aveReadingSi?: TableReadRecord["aveReadingSi"]
	instrument: TableReadRecord["instrument"]
	instrumentFactorCode: TableReadRecord["instrumentFactorCode"]
	magsusSi?: TableReadRecord["magsusSi"]
	readBy?: TableReadRecord["readBy"]
	readDt?: TableReadRecord["readDt"]
	dataSource: TableReadRecord["dataSource"]
	migrationRv?: TableReadRecord["migrationRv"]
	migrationId?: TableReadRecord["migrationId"]
	reportIncludeInd: TableReadRecord["reportIncludeInd"]
	validationStatus: TableReadRecord["validationStatus"]
	validationErrors?: TableReadRecord["validationErrors"]
	rowStatus: TableReadRecord["rowStatus"]
	supersededById?: TableReadRecord["supersededById"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.PtMagSusLog" table.
 */
export interface PtMagSusLogInsertRecord {
	/**
	 * @default: (newid())
	 */
	ptMagSusLogId?: TableInsertRecord["ptMagSusLogId"]
	/**
	 * @maxLen: 30
	 */
	organization: TableInsertRecord["organization"]
	ptLoggingEventId: TableInsertRecord["ptLoggingEventId"]
	/**
	 * @maxLen: 50
	 */
	sampleType?: TableInsertRecord["sampleType"]
	reading1Si?: TableInsertRecord["reading1Si"]
	reading2Si?: TableInsertRecord["reading2Si"]
	reading3Si?: TableInsertRecord["reading3Si"]
	aveReadingSi?: TableInsertRecord["aveReadingSi"]
	/**
	 * @maxLen: 50
	 * @default: (N'NR')
	 */
	instrument?: TableInsertRecord["instrument"]
	/**
	 * @maxLen: 50
	 * @default: (N'NR')
	 */
	instrumentFactorCode?: TableInsertRecord["instrumentFactorCode"]
	magsusSi?: TableInsertRecord["magsusSi"]
	/**
	 * @maxLen: 50
	 */
	readBy?: TableInsertRecord["readBy"]
	readDt?: TableInsertRecord["readDt"]
	/**
	 * @maxLen: 255
	 */
	dataSource: TableInsertRecord["dataSource"]
	/**
	 * @maxLen: 8
	 */
	migrationRv?: TableInsertRecord["migrationRv"]
	migrationId?: TableInsertRecord["migrationId"]
	/**
	 * @default: ((0))
	 */
	reportIncludeInd?: TableInsertRecord["reportIncludeInd"]
	/**
	 * @default: ((0))
	 */
	validationStatus?: TableInsertRecord["validationStatus"]
	/**
	 * @maxLen: 4000
	 */
	validationErrors?: TableInsertRecord["validationErrors"]
	/**
	 * @default: ((0))
	 */
	rowStatus?: TableInsertRecord["rowStatus"]
	supersededById?: TableInsertRecord["supersededById"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.PtMagSusLog" table.
 */
export type PtMagSusLogUpdateRecord = Partial<PtMagSusLogInsertRecord>;
