// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.AssayMethodGeneric" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const AssayMethodGenericTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	AssayMethodGenericId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	GenericMethod: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	DataSource: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.AssayMethodGeneric" table.
 * This type represents the raw database record without case transforms.
 */
export type AssayMethodGenericBaseRecord = z.output<typeof AssayMethodGenericTableBaseSchema>;

/**
 * Read transform for the "dbo.AssayMethodGeneric" table.
 * Maps database fields to app case properties.
 */
export function transformAssayMethodGenericBaseRecord(data: AssayMethodGenericBaseRecord): {
	assayMethodGenericId: AssayMethodGenericBaseRecord["AssayMethodGenericId"]
	genericMethod: AssayMethodGenericBaseRecord["GenericMethod"]
	description?: AssayMethodGenericBaseRecord["Description"]
	dataSource: AssayMethodGenericBaseRecord["DataSource"]
	createdOnDt: AssayMethodGenericBaseRecord["CreatedOnDt"]
	createdBy: AssayMethodGenericBaseRecord["CreatedBy"]
	modifiedOnDt?: AssayMethodGenericBaseRecord["ModifiedOnDt"]
	modifiedBy?: AssayMethodGenericBaseRecord["ModifiedBy"]
	rv: AssayMethodGenericBaseRecord["rv"]
} {
	return {
		assayMethodGenericId: data.AssayMethodGenericId,
		genericMethod: data.GenericMethod,
		description: data.Description,
		dataSource: data.DataSource,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.AssayMethodGeneric" table (after casing transform).
 */
export const AssayMethodGenericTableSchema = AssayMethodGenericTableBaseSchema.transform(transformAssayMethodGenericBaseRecord);

/**
 * Base insert/write schema for the "dbo.AssayMethodGeneric" table (no casing transforms).
 */
export const AssayMethodGenericTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	assayMethodGenericId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	genericMethod: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	dataSource: z.string().max(255),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.AssayMethodGeneric" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type AssayMethodGenericInsertBaseRecord = z.output<typeof AssayMethodGenericTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.AssayMethodGeneric" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type AssayMethodGenericUpdateBaseRecord = Partial<AssayMethodGenericInsertBaseRecord>;

/**
 * Insert transform for the "dbo.AssayMethodGeneric" table.
 * Maps app cased properties to database fields.
 */
export function transformAssayMethodGenericInsertBaseRecord(data: AssayMethodGenericInsertBaseRecord): {
	AssayMethodGenericId?: AssayMethodGenericInsertBaseRecord["assayMethodGenericId"]
	GenericMethod: AssayMethodGenericInsertBaseRecord["genericMethod"]
	Description?: AssayMethodGenericInsertBaseRecord["description"]
	DataSource: AssayMethodGenericInsertBaseRecord["dataSource"]
	CreatedOnDt?: AssayMethodGenericInsertBaseRecord["createdOnDt"]
	CreatedBy?: AssayMethodGenericInsertBaseRecord["createdBy"]
	ModifiedOnDt?: AssayMethodGenericInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: AssayMethodGenericInsertBaseRecord["modifiedBy"]
	rv: AssayMethodGenericInsertBaseRecord["rv"]
} {
	return {
		AssayMethodGenericId: data.assayMethodGenericId,
		GenericMethod: data.genericMethod,
		Description: data.description,
		DataSource: data.dataSource,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.AssayMethodGeneric" table.
 * Maps app cased properties to database fields.
 */
export function transformAssayMethodGenericUpdateBaseRecord(data: AssayMethodGenericUpdateBaseRecord): {
	AssayMethodGenericId?: AssayMethodGenericUpdateBaseRecord["assayMethodGenericId"]
	GenericMethod: AssayMethodGenericUpdateBaseRecord["genericMethod"]
	Description?: AssayMethodGenericUpdateBaseRecord["description"]
	DataSource: AssayMethodGenericUpdateBaseRecord["dataSource"]
	CreatedOnDt?: AssayMethodGenericUpdateBaseRecord["createdOnDt"]
	CreatedBy?: AssayMethodGenericUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: AssayMethodGenericUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: AssayMethodGenericUpdateBaseRecord["modifiedBy"]
	rv: AssayMethodGenericUpdateBaseRecord["rv"]
} {
	return {
		AssayMethodGenericId: data.assayMethodGenericId,
		GenericMethod: data.genericMethod,
		Description: data.description,
		DataSource: data.dataSource,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.AssayMethodGeneric" table (after casing transform).
 */
export const AssayMethodGenericTableInsertSchema = AssayMethodGenericTableInsertBaseSchema.transform(transformAssayMethodGenericInsertBaseRecord);

/**
 * Update schema for the "dbo.AssayMethodGeneric" table (after casing transform).
 */
export const AssayMethodGenericTableUpdateSchema = AssayMethodGenericTableInsertBaseSchema.partial().transform(transformAssayMethodGenericUpdateBaseRecord);

type TableInsertRecord = z.input<typeof AssayMethodGenericTableInsertSchema>;
type TableReadRecord = z.output<typeof AssayMethodGenericTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.AssayMethodGeneric" table.
 */
export interface AssayMethodGenericRecord {
	assayMethodGenericId: TableReadRecord["assayMethodGenericId"]
	genericMethod: TableReadRecord["genericMethod"]
	description?: TableReadRecord["description"]
	dataSource: TableReadRecord["dataSource"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.AssayMethodGeneric" table.
 */
export interface AssayMethodGenericInsertRecord {
	/**
	 * @default: (newid())
	 */
	assayMethodGenericId?: TableInsertRecord["assayMethodGenericId"]
	/**
	 * @maxLen: 50
	 */
	genericMethod: TableInsertRecord["genericMethod"]
	/**
	 * @maxLen: 1000
	 */
	description?: TableInsertRecord["description"]
	/**
	 * @maxLen: 255
	 */
	dataSource: TableInsertRecord["dataSource"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.AssayMethodGeneric" table.
 */
export type AssayMethodGenericUpdateRecord = Partial<AssayMethodGenericInsertRecord>;
