// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.LodeCode" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const LodeCodeTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	LodeCodeId: z.any(),
});

/**
 * The base record type for the "dbo.LodeCode" table.
 * This type represents the raw database record without case transforms.
 */
export type LodeCodeBaseRecord = z.output<typeof LodeCodeTableBaseSchema>;

/**
 * Read transform for the "dbo.LodeCode" table.
 * Maps database fields to app case properties.
 */
export function transformLodeCodeBaseRecord(data: LodeCodeBaseRecord): {
	code: LodeCodeBaseRecord["Code"]
	description: LodeCodeBaseRecord["Description"]
	sortOrder: LodeCodeBaseRecord["SortOrder"]
	isDefaultInd: LodeCodeBaseRecord["IsDefaultInd"]
	activeInd: LodeCodeBaseRecord["ActiveInd"]
	createdOnDt: LodeCodeBaseRecord["CreatedOnDt"]
	createdBy: LodeCodeBaseRecord["CreatedBy"]
	modifiedOnDt?: LodeCodeBaseRecord["ModifiedOnDt"]
	modifiedBy?: LodeCodeBaseRecord["ModifiedBy"]
	rv: LodeCodeBaseRecord["rv"]
	lodeCodeId: LodeCodeBaseRecord["LodeCodeId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		lodeCodeId: data.LodeCodeId,
	};
}

/**
 * Read schema for the "dbo.LodeCode" table (after casing transform).
 */
export const LodeCodeTableSchema = LodeCodeTableBaseSchema.transform(transformLodeCodeBaseRecord);

/**
 * Base insert/write schema for the "dbo.LodeCode" table (no casing transforms).
 */
export const LodeCodeTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	lodeCodeId: z.any().optional(),
});

/**
 * The base record type for the "dbo.LodeCode" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type LodeCodeInsertBaseRecord = z.output<typeof LodeCodeTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.LodeCode" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type LodeCodeUpdateBaseRecord = Partial<LodeCodeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.LodeCode" table.
 * Maps app cased properties to database fields.
 */
export function transformLodeCodeInsertBaseRecord(data: LodeCodeInsertBaseRecord): {
	Code: LodeCodeInsertBaseRecord["code"]
	Description: LodeCodeInsertBaseRecord["description"]
	SortOrder?: LodeCodeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: LodeCodeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: LodeCodeInsertBaseRecord["activeInd"]
	CreatedOnDt?: LodeCodeInsertBaseRecord["createdOnDt"]
	CreatedBy?: LodeCodeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: LodeCodeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: LodeCodeInsertBaseRecord["modifiedBy"]
	rv: LodeCodeInsertBaseRecord["rv"]
	LodeCodeId?: LodeCodeInsertBaseRecord["lodeCodeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		LodeCodeId: data.lodeCodeId,
	};
}

/**
 * Update transform for the "dbo.LodeCode" table.
 * Maps app cased properties to database fields.
 */
export function transformLodeCodeUpdateBaseRecord(data: LodeCodeUpdateBaseRecord): {
	Code: LodeCodeUpdateBaseRecord["code"]
	Description: LodeCodeUpdateBaseRecord["description"]
	SortOrder?: LodeCodeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: LodeCodeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: LodeCodeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: LodeCodeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: LodeCodeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: LodeCodeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: LodeCodeUpdateBaseRecord["modifiedBy"]
	rv: LodeCodeUpdateBaseRecord["rv"]
	LodeCodeId?: LodeCodeUpdateBaseRecord["lodeCodeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		LodeCodeId: data.lodeCodeId,
	};
}

/**
 * Insert schema for the "dbo.LodeCode" table (after casing transform).
 */
export const LodeCodeTableInsertSchema = LodeCodeTableInsertBaseSchema.transform(transformLodeCodeInsertBaseRecord);

/**
 * Update schema for the "dbo.LodeCode" table (after casing transform).
 */
export const LodeCodeTableUpdateSchema = LodeCodeTableInsertBaseSchema.partial().transform(transformLodeCodeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof LodeCodeTableInsertSchema>;
type TableReadRecord = z.output<typeof LodeCodeTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.LodeCode" table.
 */
export interface LodeCodeRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	lodeCodeId: TableReadRecord["lodeCodeId"]
}

/**
 * Insert record (casing transformed) for the "dbo.LodeCode" table.
 */
export interface LodeCodeInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	lodeCodeId?: TableInsertRecord["lodeCodeId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.LodeCode" table.
 */
export type LodeCodeUpdateRecord = Partial<LodeCodeInsertRecord>;
