// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.YoungingIndicator" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const YoungingIndicatorTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	YoungingIndicatorId: z.any(),
});

/**
 * The base record type for the "dbo.YoungingIndicator" table.
 * This type represents the raw database record without case transforms.
 */
export type YoungingIndicatorBaseRecord = z.output<typeof YoungingIndicatorTableBaseSchema>;

/**
 * Read transform for the "dbo.YoungingIndicator" table.
 * Maps database fields to app case properties.
 */
export function transformYoungingIndicatorBaseRecord(data: YoungingIndicatorBaseRecord): {
	code: YoungingIndicatorBaseRecord["Code"]
	description: YoungingIndicatorBaseRecord["Description"]
	sortOrder: YoungingIndicatorBaseRecord["SortOrder"]
	isDefaultInd: YoungingIndicatorBaseRecord["IsDefaultInd"]
	activeInd: YoungingIndicatorBaseRecord["ActiveInd"]
	createdOnDt: YoungingIndicatorBaseRecord["CreatedOnDt"]
	createdBy: YoungingIndicatorBaseRecord["CreatedBy"]
	modifiedOnDt?: YoungingIndicatorBaseRecord["ModifiedOnDt"]
	modifiedBy?: YoungingIndicatorBaseRecord["ModifiedBy"]
	rv: YoungingIndicatorBaseRecord["rv"]
	youngingIndicatorId: YoungingIndicatorBaseRecord["YoungingIndicatorId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		youngingIndicatorId: data.YoungingIndicatorId,
	};
}

/**
 * Read schema for the "dbo.YoungingIndicator" table (after casing transform).
 */
export const YoungingIndicatorTableSchema = YoungingIndicatorTableBaseSchema.transform(transformYoungingIndicatorBaseRecord);

/**
 * Base insert/write schema for the "dbo.YoungingIndicator" table (no casing transforms).
 */
export const YoungingIndicatorTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	youngingIndicatorId: z.any().optional(),
});

/**
 * The base record type for the "dbo.YoungingIndicator" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type YoungingIndicatorInsertBaseRecord = z.output<typeof YoungingIndicatorTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.YoungingIndicator" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type YoungingIndicatorUpdateBaseRecord = Partial<YoungingIndicatorInsertBaseRecord>;

/**
 * Insert transform for the "dbo.YoungingIndicator" table.
 * Maps app cased properties to database fields.
 */
export function transformYoungingIndicatorInsertBaseRecord(data: YoungingIndicatorInsertBaseRecord): {
	Code: YoungingIndicatorInsertBaseRecord["code"]
	Description: YoungingIndicatorInsertBaseRecord["description"]
	SortOrder?: YoungingIndicatorInsertBaseRecord["sortOrder"]
	IsDefaultInd?: YoungingIndicatorInsertBaseRecord["isDefaultInd"]
	ActiveInd?: YoungingIndicatorInsertBaseRecord["activeInd"]
	CreatedOnDt?: YoungingIndicatorInsertBaseRecord["createdOnDt"]
	CreatedBy?: YoungingIndicatorInsertBaseRecord["createdBy"]
	ModifiedOnDt?: YoungingIndicatorInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: YoungingIndicatorInsertBaseRecord["modifiedBy"]
	rv: YoungingIndicatorInsertBaseRecord["rv"]
	YoungingIndicatorId?: YoungingIndicatorInsertBaseRecord["youngingIndicatorId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		YoungingIndicatorId: data.youngingIndicatorId,
	};
}

/**
 * Update transform for the "dbo.YoungingIndicator" table.
 * Maps app cased properties to database fields.
 */
export function transformYoungingIndicatorUpdateBaseRecord(data: YoungingIndicatorUpdateBaseRecord): {
	Code: YoungingIndicatorUpdateBaseRecord["code"]
	Description: YoungingIndicatorUpdateBaseRecord["description"]
	SortOrder?: YoungingIndicatorUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: YoungingIndicatorUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: YoungingIndicatorUpdateBaseRecord["activeInd"]
	CreatedOnDt?: YoungingIndicatorUpdateBaseRecord["createdOnDt"]
	CreatedBy?: YoungingIndicatorUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: YoungingIndicatorUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: YoungingIndicatorUpdateBaseRecord["modifiedBy"]
	rv: YoungingIndicatorUpdateBaseRecord["rv"]
	YoungingIndicatorId?: YoungingIndicatorUpdateBaseRecord["youngingIndicatorId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		YoungingIndicatorId: data.youngingIndicatorId,
	};
}

/**
 * Insert schema for the "dbo.YoungingIndicator" table (after casing transform).
 */
export const YoungingIndicatorTableInsertSchema = YoungingIndicatorTableInsertBaseSchema.transform(transformYoungingIndicatorInsertBaseRecord);

/**
 * Update schema for the "dbo.YoungingIndicator" table (after casing transform).
 */
export const YoungingIndicatorTableUpdateSchema = YoungingIndicatorTableInsertBaseSchema.partial().transform(transformYoungingIndicatorUpdateBaseRecord);

type TableInsertRecord = z.input<typeof YoungingIndicatorTableInsertSchema>;
type TableReadRecord = z.output<typeof YoungingIndicatorTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.YoungingIndicator" table.
 */
export interface YoungingIndicatorRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	youngingIndicatorId: TableReadRecord["youngingIndicatorId"]
}

/**
 * Insert record (casing transformed) for the "dbo.YoungingIndicator" table.
 */
export interface YoungingIndicatorInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	youngingIndicatorId?: TableInsertRecord["youngingIndicatorId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.YoungingIndicator" table.
 */
export type YoungingIndicatorUpdateRecord = Partial<YoungingIndicatorInsertRecord>;
