// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.XRFSampleQC" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const XRFSampleQCTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Organization: z.string(),
	/**
	 * dataType: uniqueidentifier
	 */
	SampleId: z.any(),
	/**
	 * dataType: uniqueidentifier
	 */
	OriginalSampleId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	QCClassification: z.string(),
	/**
	 * dataType: uniqueidentifier
	 */
	CollarId: z.any(),
	/**
	 * dataType: decimal
	 */
	DepthFrom: z.number(),
	/**
	 * dataType: decimal
	 */
	DepthTo: z.number(),
	/**
	 * dataType: decimal
	 */
	IntervalLength: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: smallint
	 */
	Priority: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	SampleType: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	SampleMethod: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	SampledBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	SampledDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	LoggedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	DataSource: z.string(),
	/**
	 * dataType: bit
	 */
	ReportIncludeInd: z.any(),
	/**
	 * dataType: tinyint
	 */
	ValidationStatus: z.number(),
	/**
	 * dataType: nvarchar
	 */
	ValidationErrors: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: tinyint
	 */
	RowStatus: z.number(),
	/**
	 * dataType: uniqueidentifier
	 */
	SupersededById: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.XRFSampleQC" table.
 * This type represents the raw database record without case transforms.
 */
export type XrfsampleQcBaseRecord = z.output<typeof XRFSampleQCTableBaseSchema>;

/**
 * Read transform for the "dbo.XRFSampleQC" table.
 * Maps database fields to app case properties.
 */
export function transformXrfsampleQcBaseRecord(data: XrfsampleQcBaseRecord): {
	organization: XrfsampleQcBaseRecord["Organization"]
	sampleId: XrfsampleQcBaseRecord["SampleId"]
	originalSampleId: XrfsampleQcBaseRecord["OriginalSampleId"]
	qCClassification: XrfsampleQcBaseRecord["QCClassification"]
	collarId: XrfsampleQcBaseRecord["CollarId"]
	depthFrom: XrfsampleQcBaseRecord["DepthFrom"]
	depthTo: XrfsampleQcBaseRecord["DepthTo"]
	intervalLength?: XrfsampleQcBaseRecord["IntervalLength"]
	priority?: XrfsampleQcBaseRecord["Priority"]
	sampleType?: XrfsampleQcBaseRecord["SampleType"]
	sampleMethod?: XrfsampleQcBaseRecord["SampleMethod"]
	sampledBy?: XrfsampleQcBaseRecord["SampledBy"]
	sampledDt?: XrfsampleQcBaseRecord["SampledDt"]
	loggedBy?: XrfsampleQcBaseRecord["LoggedBy"]
	dataSource: XrfsampleQcBaseRecord["DataSource"]
	reportIncludeInd: XrfsampleQcBaseRecord["ReportIncludeInd"]
	validationStatus: XrfsampleQcBaseRecord["ValidationStatus"]
	validationErrors?: XrfsampleQcBaseRecord["ValidationErrors"]
	rowStatus: XrfsampleQcBaseRecord["RowStatus"]
	supersededById?: XrfsampleQcBaseRecord["SupersededById"]
	activeInd: XrfsampleQcBaseRecord["ActiveInd"]
	createdOnDt: XrfsampleQcBaseRecord["CreatedOnDt"]
	createdBy: XrfsampleQcBaseRecord["CreatedBy"]
	modifiedOnDt?: XrfsampleQcBaseRecord["ModifiedOnDt"]
	modifiedBy?: XrfsampleQcBaseRecord["ModifiedBy"]
	rv: XrfsampleQcBaseRecord["rv"]
} {
	return {
		organization: data.Organization,
		sampleId: data.SampleId,
		originalSampleId: data.OriginalSampleId,
		qCClassification: data.QCClassification,
		collarId: data.CollarId,
		depthFrom: data.DepthFrom,
		depthTo: data.DepthTo,
		intervalLength: data.IntervalLength,
		priority: data.Priority,
		sampleType: data.SampleType,
		sampleMethod: data.SampleMethod,
		sampledBy: data.SampledBy,
		sampledDt: data.SampledDt,
		loggedBy: data.LoggedBy,
		dataSource: data.DataSource,
		reportIncludeInd: data.ReportIncludeInd,
		validationStatus: data.ValidationStatus,
		validationErrors: data.ValidationErrors,
		rowStatus: data.RowStatus,
		supersededById: data.SupersededById,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.XRFSampleQC" table (after casing transform).
 */
export const XRFSampleQCTableSchema = XRFSampleQCTableBaseSchema.transform(transformXrfsampleQcBaseRecord);

/**
 * Base insert/write schema for the "dbo.XRFSampleQC" table (no casing transforms).
 */
export const XRFSampleQCTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	organization: z.string().max(30),
	/**
	 * dataType: uniqueidentifier
	 */
	sampleId: z.any(),
	/**
	 * dataType: uniqueidentifier
	 */
	originalSampleId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	qCClassification: z.string().max(50),
	/**
	 * dataType: uniqueidentifier
	 */
	collarId: z.any(),
	/**
	 * dataType: decimal
	 */
	depthFrom: z.number(),
	/**
	 * dataType: decimal
	 */
	depthTo: z.number(),
	/**
	 * dataType: decimal
	 */
	intervalLength: z.number().nullable().optional(),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	priority: z.number().int().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	sampleType: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	sampleMethod: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	sampledBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	sampledDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	loggedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	dataSource: z.string().max(255),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	reportIncludeInd: z.any().optional(),
	/**
	 * dataType: tinyint
	 * defaultValue: ((0))
	 */
	validationStatus: z.number().int().optional(),
	/**
	 * dataType: nvarchar
	 */
	validationErrors: z.string().max(4000).nullable().optional(),
	/**
	 * dataType: tinyint
	 * defaultValue: ((0))
	 */
	rowStatus: z.number().int().optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	supersededById: z.any().nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.XRFSampleQC" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type XrfsampleQcInsertBaseRecord = z.output<typeof XRFSampleQCTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.XRFSampleQC" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type XrfsampleQcUpdateBaseRecord = Partial<XrfsampleQcInsertBaseRecord>;

/**
 * Insert transform for the "dbo.XRFSampleQC" table.
 * Maps app cased properties to database fields.
 */
export function transformXrfsampleQcInsertBaseRecord(data: XrfsampleQcInsertBaseRecord): {
	Organization: XrfsampleQcInsertBaseRecord["organization"]
	SampleId: XrfsampleQcInsertBaseRecord["sampleId"]
	OriginalSampleId: XrfsampleQcInsertBaseRecord["originalSampleId"]
	QCClassification: XrfsampleQcInsertBaseRecord["qCClassification"]
	CollarId: XrfsampleQcInsertBaseRecord["collarId"]
	DepthFrom: XrfsampleQcInsertBaseRecord["depthFrom"]
	DepthTo: XrfsampleQcInsertBaseRecord["depthTo"]
	IntervalLength?: XrfsampleQcInsertBaseRecord["intervalLength"]
	Priority?: XrfsampleQcInsertBaseRecord["priority"]
	SampleType?: XrfsampleQcInsertBaseRecord["sampleType"]
	SampleMethod?: XrfsampleQcInsertBaseRecord["sampleMethod"]
	SampledBy?: XrfsampleQcInsertBaseRecord["sampledBy"]
	SampledDt?: XrfsampleQcInsertBaseRecord["sampledDt"]
	LoggedBy?: XrfsampleQcInsertBaseRecord["loggedBy"]
	DataSource: XrfsampleQcInsertBaseRecord["dataSource"]
	ReportIncludeInd?: XrfsampleQcInsertBaseRecord["reportIncludeInd"]
	ValidationStatus?: XrfsampleQcInsertBaseRecord["validationStatus"]
	ValidationErrors?: XrfsampleQcInsertBaseRecord["validationErrors"]
	RowStatus?: XrfsampleQcInsertBaseRecord["rowStatus"]
	SupersededById?: XrfsampleQcInsertBaseRecord["supersededById"]
	ActiveInd?: XrfsampleQcInsertBaseRecord["activeInd"]
	CreatedOnDt?: XrfsampleQcInsertBaseRecord["createdOnDt"]
	CreatedBy?: XrfsampleQcInsertBaseRecord["createdBy"]
	ModifiedOnDt?: XrfsampleQcInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: XrfsampleQcInsertBaseRecord["modifiedBy"]
	rv: XrfsampleQcInsertBaseRecord["rv"]
} {
	return {
		Organization: data.organization,
		SampleId: data.sampleId,
		OriginalSampleId: data.originalSampleId,
		QCClassification: data.qCClassification,
		CollarId: data.collarId,
		DepthFrom: data.depthFrom,
		DepthTo: data.depthTo,
		IntervalLength: data.intervalLength,
		Priority: data.priority,
		SampleType: data.sampleType,
		SampleMethod: data.sampleMethod,
		SampledBy: data.sampledBy,
		SampledDt: data.sampledDt,
		LoggedBy: data.loggedBy,
		DataSource: data.dataSource,
		ReportIncludeInd: data.reportIncludeInd,
		ValidationStatus: data.validationStatus,
		ValidationErrors: data.validationErrors,
		RowStatus: data.rowStatus,
		SupersededById: data.supersededById,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.XRFSampleQC" table.
 * Maps app cased properties to database fields.
 */
export function transformXrfsampleQcUpdateBaseRecord(data: XrfsampleQcUpdateBaseRecord): {
	Organization: XrfsampleQcUpdateBaseRecord["organization"]
	SampleId: XrfsampleQcUpdateBaseRecord["sampleId"]
	OriginalSampleId: XrfsampleQcUpdateBaseRecord["originalSampleId"]
	QCClassification: XrfsampleQcUpdateBaseRecord["qCClassification"]
	CollarId: XrfsampleQcUpdateBaseRecord["collarId"]
	DepthFrom: XrfsampleQcUpdateBaseRecord["depthFrom"]
	DepthTo: XrfsampleQcUpdateBaseRecord["depthTo"]
	IntervalLength?: XrfsampleQcUpdateBaseRecord["intervalLength"]
	Priority?: XrfsampleQcUpdateBaseRecord["priority"]
	SampleType?: XrfsampleQcUpdateBaseRecord["sampleType"]
	SampleMethod?: XrfsampleQcUpdateBaseRecord["sampleMethod"]
	SampledBy?: XrfsampleQcUpdateBaseRecord["sampledBy"]
	SampledDt?: XrfsampleQcUpdateBaseRecord["sampledDt"]
	LoggedBy?: XrfsampleQcUpdateBaseRecord["loggedBy"]
	DataSource: XrfsampleQcUpdateBaseRecord["dataSource"]
	ReportIncludeInd?: XrfsampleQcUpdateBaseRecord["reportIncludeInd"]
	ValidationStatus?: XrfsampleQcUpdateBaseRecord["validationStatus"]
	ValidationErrors?: XrfsampleQcUpdateBaseRecord["validationErrors"]
	RowStatus?: XrfsampleQcUpdateBaseRecord["rowStatus"]
	SupersededById?: XrfsampleQcUpdateBaseRecord["supersededById"]
	ActiveInd?: XrfsampleQcUpdateBaseRecord["activeInd"]
	CreatedOnDt?: XrfsampleQcUpdateBaseRecord["createdOnDt"]
	CreatedBy?: XrfsampleQcUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: XrfsampleQcUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: XrfsampleQcUpdateBaseRecord["modifiedBy"]
	rv: XrfsampleQcUpdateBaseRecord["rv"]
} {
	return {
		Organization: data.organization,
		SampleId: data.sampleId,
		OriginalSampleId: data.originalSampleId,
		QCClassification: data.qCClassification,
		CollarId: data.collarId,
		DepthFrom: data.depthFrom,
		DepthTo: data.depthTo,
		IntervalLength: data.intervalLength,
		Priority: data.priority,
		SampleType: data.sampleType,
		SampleMethod: data.sampleMethod,
		SampledBy: data.sampledBy,
		SampledDt: data.sampledDt,
		LoggedBy: data.loggedBy,
		DataSource: data.dataSource,
		ReportIncludeInd: data.reportIncludeInd,
		ValidationStatus: data.validationStatus,
		ValidationErrors: data.validationErrors,
		RowStatus: data.rowStatus,
		SupersededById: data.supersededById,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.XRFSampleQC" table (after casing transform).
 */
export const XRFSampleQCTableInsertSchema = XRFSampleQCTableInsertBaseSchema.transform(transformXrfsampleQcInsertBaseRecord);

/**
 * Update schema for the "dbo.XRFSampleQC" table (after casing transform).
 */
export const XRFSampleQCTableUpdateSchema = XRFSampleQCTableInsertBaseSchema.partial().transform(transformXrfsampleQcUpdateBaseRecord);

type TableInsertRecord = z.input<typeof XRFSampleQCTableInsertSchema>;
type TableReadRecord = z.output<typeof XRFSampleQCTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.XRFSampleQC" table.
 */
export interface XrfsampleQcRecord {
	organization: TableReadRecord["organization"]
	sampleId: TableReadRecord["sampleId"]
	originalSampleId: TableReadRecord["originalSampleId"]
	qCClassification: TableReadRecord["qCClassification"]
	collarId: TableReadRecord["collarId"]
	depthFrom: TableReadRecord["depthFrom"]
	depthTo: TableReadRecord["depthTo"]
	intervalLength?: TableReadRecord["intervalLength"]
	priority?: TableReadRecord["priority"]
	sampleType?: TableReadRecord["sampleType"]
	sampleMethod?: TableReadRecord["sampleMethod"]
	sampledBy?: TableReadRecord["sampledBy"]
	sampledDt?: TableReadRecord["sampledDt"]
	loggedBy?: TableReadRecord["loggedBy"]
	dataSource: TableReadRecord["dataSource"]
	reportIncludeInd: TableReadRecord["reportIncludeInd"]
	validationStatus: TableReadRecord["validationStatus"]
	validationErrors?: TableReadRecord["validationErrors"]
	rowStatus: TableReadRecord["rowStatus"]
	supersededById?: TableReadRecord["supersededById"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.XRFSampleQC" table.
 */
export interface XrfsampleQcInsertRecord {
	/**
	 * @maxLen: 30
	 */
	organization: TableInsertRecord["organization"]
	sampleId: TableInsertRecord["sampleId"]
	originalSampleId: TableInsertRecord["originalSampleId"]
	/**
	 * @maxLen: 50
	 */
	qCClassification: TableInsertRecord["qCClassification"]
	collarId: TableInsertRecord["collarId"]
	depthFrom: TableInsertRecord["depthFrom"]
	depthTo: TableInsertRecord["depthTo"]
	intervalLength?: TableInsertRecord["intervalLength"]
	/**
	 * @default: ((0))
	 */
	priority?: TableInsertRecord["priority"]
	/**
	 * @maxLen: 50
	 */
	sampleType?: TableInsertRecord["sampleType"]
	/**
	 * @maxLen: 50
	 */
	sampleMethod?: TableInsertRecord["sampleMethod"]
	/**
	 * @maxLen: 50
	 */
	sampledBy?: TableInsertRecord["sampledBy"]
	sampledDt?: TableInsertRecord["sampledDt"]
	/**
	 * @maxLen: 50
	 */
	loggedBy?: TableInsertRecord["loggedBy"]
	/**
	 * @maxLen: 255
	 */
	dataSource: TableInsertRecord["dataSource"]
	/**
	 * @default: ((0))
	 */
	reportIncludeInd?: TableInsertRecord["reportIncludeInd"]
	/**
	 * @default: ((0))
	 */
	validationStatus?: TableInsertRecord["validationStatus"]
	/**
	 * @maxLen: 4000
	 */
	validationErrors?: TableInsertRecord["validationErrors"]
	/**
	 * @default: ((0))
	 */
	rowStatus?: TableInsertRecord["rowStatus"]
	supersededById?: TableInsertRecord["supersededById"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.XRFSampleQC" table.
 */
export type XrfsampleQcUpdateRecord = Partial<XrfsampleQcInsertRecord>;
