// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.StructContinuity" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const StructContinuityTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	StructContinuityId: z.any(),
});

/**
 * The base record type for the "dbo.StructContinuity" table.
 * This type represents the raw database record without case transforms.
 */
export type StructContinuityBaseRecord = z.output<typeof StructContinuityTableBaseSchema>;

/**
 * Read transform for the "dbo.StructContinuity" table.
 * Maps database fields to app case properties.
 */
export function transformStructContinuityBaseRecord(data: StructContinuityBaseRecord): {
	code: StructContinuityBaseRecord["Code"]
	description: StructContinuityBaseRecord["Description"]
	sortOrder: StructContinuityBaseRecord["SortOrder"]
	isDefaultInd: StructContinuityBaseRecord["IsDefaultInd"]
	activeInd: StructContinuityBaseRecord["ActiveInd"]
	createdOnDt: StructContinuityBaseRecord["CreatedOnDt"]
	createdBy: StructContinuityBaseRecord["CreatedBy"]
	modifiedOnDt?: StructContinuityBaseRecord["ModifiedOnDt"]
	modifiedBy?: StructContinuityBaseRecord["ModifiedBy"]
	rv: StructContinuityBaseRecord["rv"]
	structContinuityId: StructContinuityBaseRecord["StructContinuityId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		structContinuityId: data.StructContinuityId,
	};
}

/**
 * Read schema for the "dbo.StructContinuity" table (after casing transform).
 */
export const StructContinuityTableSchema = StructContinuityTableBaseSchema.transform(transformStructContinuityBaseRecord);

/**
 * Base insert/write schema for the "dbo.StructContinuity" table (no casing transforms).
 */
export const StructContinuityTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	structContinuityId: z.any().optional(),
});

/**
 * The base record type for the "dbo.StructContinuity" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type StructContinuityInsertBaseRecord = z.output<typeof StructContinuityTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.StructContinuity" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type StructContinuityUpdateBaseRecord = Partial<StructContinuityInsertBaseRecord>;

/**
 * Insert transform for the "dbo.StructContinuity" table.
 * Maps app cased properties to database fields.
 */
export function transformStructContinuityInsertBaseRecord(data: StructContinuityInsertBaseRecord): {
	Code: StructContinuityInsertBaseRecord["code"]
	Description: StructContinuityInsertBaseRecord["description"]
	SortOrder?: StructContinuityInsertBaseRecord["sortOrder"]
	IsDefaultInd?: StructContinuityInsertBaseRecord["isDefaultInd"]
	ActiveInd?: StructContinuityInsertBaseRecord["activeInd"]
	CreatedOnDt?: StructContinuityInsertBaseRecord["createdOnDt"]
	CreatedBy?: StructContinuityInsertBaseRecord["createdBy"]
	ModifiedOnDt?: StructContinuityInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: StructContinuityInsertBaseRecord["modifiedBy"]
	rv: StructContinuityInsertBaseRecord["rv"]
	StructContinuityId?: StructContinuityInsertBaseRecord["structContinuityId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		StructContinuityId: data.structContinuityId,
	};
}

/**
 * Update transform for the "dbo.StructContinuity" table.
 * Maps app cased properties to database fields.
 */
export function transformStructContinuityUpdateBaseRecord(data: StructContinuityUpdateBaseRecord): {
	Code: StructContinuityUpdateBaseRecord["code"]
	Description: StructContinuityUpdateBaseRecord["description"]
	SortOrder?: StructContinuityUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: StructContinuityUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: StructContinuityUpdateBaseRecord["activeInd"]
	CreatedOnDt?: StructContinuityUpdateBaseRecord["createdOnDt"]
	CreatedBy?: StructContinuityUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: StructContinuityUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: StructContinuityUpdateBaseRecord["modifiedBy"]
	rv: StructContinuityUpdateBaseRecord["rv"]
	StructContinuityId?: StructContinuityUpdateBaseRecord["structContinuityId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		StructContinuityId: data.structContinuityId,
	};
}

/**
 * Insert schema for the "dbo.StructContinuity" table (after casing transform).
 */
export const StructContinuityTableInsertSchema = StructContinuityTableInsertBaseSchema.transform(transformStructContinuityInsertBaseRecord);

/**
 * Update schema for the "dbo.StructContinuity" table (after casing transform).
 */
export const StructContinuityTableUpdateSchema = StructContinuityTableInsertBaseSchema.partial().transform(transformStructContinuityUpdateBaseRecord);

type TableInsertRecord = z.input<typeof StructContinuityTableInsertSchema>;
type TableReadRecord = z.output<typeof StructContinuityTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.StructContinuity" table.
 */
export interface StructContinuityRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	structContinuityId: TableReadRecord["structContinuityId"]
}

/**
 * Insert record (casing transformed) for the "dbo.StructContinuity" table.
 */
export interface StructContinuityInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	structContinuityId?: TableInsertRecord["structContinuityId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.StructContinuity" table.
 */
export type StructContinuityUpdateRecord = Partial<StructContinuityInsertRecord>;
