// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.StructPlaneType" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const StructPlaneTypeTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	StructPlaneTypeId: z.any(),
});

/**
 * The base record type for the "dbo.StructPlaneType" table.
 * This type represents the raw database record without case transforms.
 */
export type StructPlaneTypeBaseRecord = z.output<typeof StructPlaneTypeTableBaseSchema>;

/**
 * Read transform for the "dbo.StructPlaneType" table.
 * Maps database fields to app case properties.
 */
export function transformStructPlaneTypeBaseRecord(data: StructPlaneTypeBaseRecord): {
	code: StructPlaneTypeBaseRecord["Code"]
	description: StructPlaneTypeBaseRecord["Description"]
	sortOrder: StructPlaneTypeBaseRecord["SortOrder"]
	isDefaultInd: StructPlaneTypeBaseRecord["IsDefaultInd"]
	activeInd: StructPlaneTypeBaseRecord["ActiveInd"]
	createdOnDt: StructPlaneTypeBaseRecord["CreatedOnDt"]
	createdBy: StructPlaneTypeBaseRecord["CreatedBy"]
	modifiedOnDt?: StructPlaneTypeBaseRecord["ModifiedOnDt"]
	modifiedBy?: StructPlaneTypeBaseRecord["ModifiedBy"]
	rv: StructPlaneTypeBaseRecord["rv"]
	structPlaneTypeId: StructPlaneTypeBaseRecord["StructPlaneTypeId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		structPlaneTypeId: data.StructPlaneTypeId,
	};
}

/**
 * Read schema for the "dbo.StructPlaneType" table (after casing transform).
 */
export const StructPlaneTypeTableSchema = StructPlaneTypeTableBaseSchema.transform(transformStructPlaneTypeBaseRecord);

/**
 * Base insert/write schema for the "dbo.StructPlaneType" table (no casing transforms).
 */
export const StructPlaneTypeTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	structPlaneTypeId: z.any().optional(),
});

/**
 * The base record type for the "dbo.StructPlaneType" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type StructPlaneTypeInsertBaseRecord = z.output<typeof StructPlaneTypeTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.StructPlaneType" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type StructPlaneTypeUpdateBaseRecord = Partial<StructPlaneTypeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.StructPlaneType" table.
 * Maps app cased properties to database fields.
 */
export function transformStructPlaneTypeInsertBaseRecord(data: StructPlaneTypeInsertBaseRecord): {
	Code: StructPlaneTypeInsertBaseRecord["code"]
	Description: StructPlaneTypeInsertBaseRecord["description"]
	SortOrder?: StructPlaneTypeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: StructPlaneTypeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: StructPlaneTypeInsertBaseRecord["activeInd"]
	CreatedOnDt?: StructPlaneTypeInsertBaseRecord["createdOnDt"]
	CreatedBy?: StructPlaneTypeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: StructPlaneTypeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: StructPlaneTypeInsertBaseRecord["modifiedBy"]
	rv: StructPlaneTypeInsertBaseRecord["rv"]
	StructPlaneTypeId?: StructPlaneTypeInsertBaseRecord["structPlaneTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		StructPlaneTypeId: data.structPlaneTypeId,
	};
}

/**
 * Update transform for the "dbo.StructPlaneType" table.
 * Maps app cased properties to database fields.
 */
export function transformStructPlaneTypeUpdateBaseRecord(data: StructPlaneTypeUpdateBaseRecord): {
	Code: StructPlaneTypeUpdateBaseRecord["code"]
	Description: StructPlaneTypeUpdateBaseRecord["description"]
	SortOrder?: StructPlaneTypeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: StructPlaneTypeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: StructPlaneTypeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: StructPlaneTypeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: StructPlaneTypeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: StructPlaneTypeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: StructPlaneTypeUpdateBaseRecord["modifiedBy"]
	rv: StructPlaneTypeUpdateBaseRecord["rv"]
	StructPlaneTypeId?: StructPlaneTypeUpdateBaseRecord["structPlaneTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		StructPlaneTypeId: data.structPlaneTypeId,
	};
}

/**
 * Insert schema for the "dbo.StructPlaneType" table (after casing transform).
 */
export const StructPlaneTypeTableInsertSchema = StructPlaneTypeTableInsertBaseSchema.transform(transformStructPlaneTypeInsertBaseRecord);

/**
 * Update schema for the "dbo.StructPlaneType" table (after casing transform).
 */
export const StructPlaneTypeTableUpdateSchema = StructPlaneTypeTableInsertBaseSchema.partial().transform(transformStructPlaneTypeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof StructPlaneTypeTableInsertSchema>;
type TableReadRecord = z.output<typeof StructPlaneTypeTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.StructPlaneType" table.
 */
export interface StructPlaneTypeRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	structPlaneTypeId: TableReadRecord["structPlaneTypeId"]
}

/**
 * Insert record (casing transformed) for the "dbo.StructPlaneType" table.
 */
export interface StructPlaneTypeInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	structPlaneTypeId?: TableInsertRecord["structPlaneTypeId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.StructPlaneType" table.
 */
export type StructPlaneTypeUpdateRecord = Partial<StructPlaneTypeInsertRecord>;
