// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.ParageneticStage" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const ParageneticStageTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	ParageneticStageId: z.any(),
});

/**
 * The base record type for the "dbo.ParageneticStage" table.
 * This type represents the raw database record without case transforms.
 */
export type ParageneticStageBaseRecord = z.output<typeof ParageneticStageTableBaseSchema>;

/**
 * Read transform for the "dbo.ParageneticStage" table.
 * Maps database fields to app case properties.
 */
export function transformParageneticStageBaseRecord(data: ParageneticStageBaseRecord): {
	code: ParageneticStageBaseRecord["Code"]
	description: ParageneticStageBaseRecord["Description"]
	sortOrder: ParageneticStageBaseRecord["SortOrder"]
	isDefaultInd: ParageneticStageBaseRecord["IsDefaultInd"]
	activeInd: ParageneticStageBaseRecord["ActiveInd"]
	createdOnDt: ParageneticStageBaseRecord["CreatedOnDt"]
	createdBy: ParageneticStageBaseRecord["CreatedBy"]
	modifiedOnDt?: ParageneticStageBaseRecord["ModifiedOnDt"]
	modifiedBy?: ParageneticStageBaseRecord["ModifiedBy"]
	rv: ParageneticStageBaseRecord["rv"]
	parageneticStageId: ParageneticStageBaseRecord["ParageneticStageId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		parageneticStageId: data.ParageneticStageId,
	};
}

/**
 * Read schema for the "dbo.ParageneticStage" table (after casing transform).
 */
export const ParageneticStageTableSchema = ParageneticStageTableBaseSchema.transform(transformParageneticStageBaseRecord);

/**
 * Base insert/write schema for the "dbo.ParageneticStage" table (no casing transforms).
 */
export const ParageneticStageTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	parageneticStageId: z.any().optional(),
});

/**
 * The base record type for the "dbo.ParageneticStage" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type ParageneticStageInsertBaseRecord = z.output<typeof ParageneticStageTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.ParageneticStage" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type ParageneticStageUpdateBaseRecord = Partial<ParageneticStageInsertBaseRecord>;

/**
 * Insert transform for the "dbo.ParageneticStage" table.
 * Maps app cased properties to database fields.
 */
export function transformParageneticStageInsertBaseRecord(data: ParageneticStageInsertBaseRecord): {
	Code: ParageneticStageInsertBaseRecord["code"]
	Description: ParageneticStageInsertBaseRecord["description"]
	SortOrder?: ParageneticStageInsertBaseRecord["sortOrder"]
	IsDefaultInd?: ParageneticStageInsertBaseRecord["isDefaultInd"]
	ActiveInd?: ParageneticStageInsertBaseRecord["activeInd"]
	CreatedOnDt?: ParageneticStageInsertBaseRecord["createdOnDt"]
	CreatedBy?: ParageneticStageInsertBaseRecord["createdBy"]
	ModifiedOnDt?: ParageneticStageInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: ParageneticStageInsertBaseRecord["modifiedBy"]
	rv: ParageneticStageInsertBaseRecord["rv"]
	ParageneticStageId?: ParageneticStageInsertBaseRecord["parageneticStageId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		ParageneticStageId: data.parageneticStageId,
	};
}

/**
 * Update transform for the "dbo.ParageneticStage" table.
 * Maps app cased properties to database fields.
 */
export function transformParageneticStageUpdateBaseRecord(data: ParageneticStageUpdateBaseRecord): {
	Code: ParageneticStageUpdateBaseRecord["code"]
	Description: ParageneticStageUpdateBaseRecord["description"]
	SortOrder?: ParageneticStageUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: ParageneticStageUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: ParageneticStageUpdateBaseRecord["activeInd"]
	CreatedOnDt?: ParageneticStageUpdateBaseRecord["createdOnDt"]
	CreatedBy?: ParageneticStageUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: ParageneticStageUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: ParageneticStageUpdateBaseRecord["modifiedBy"]
	rv: ParageneticStageUpdateBaseRecord["rv"]
	ParageneticStageId?: ParageneticStageUpdateBaseRecord["parageneticStageId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		ParageneticStageId: data.parageneticStageId,
	};
}

/**
 * Insert schema for the "dbo.ParageneticStage" table (after casing transform).
 */
export const ParageneticStageTableInsertSchema = ParageneticStageTableInsertBaseSchema.transform(transformParageneticStageInsertBaseRecord);

/**
 * Update schema for the "dbo.ParageneticStage" table (after casing transform).
 */
export const ParageneticStageTableUpdateSchema = ParageneticStageTableInsertBaseSchema.partial().transform(transformParageneticStageUpdateBaseRecord);

type TableInsertRecord = z.input<typeof ParageneticStageTableInsertSchema>;
type TableReadRecord = z.output<typeof ParageneticStageTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.ParageneticStage" table.
 */
export interface ParageneticStageRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	parageneticStageId: TableReadRecord["parageneticStageId"]
}

/**
 * Insert record (casing transformed) for the "dbo.ParageneticStage" table.
 */
export interface ParageneticStageInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	parageneticStageId?: TableInsertRecord["parageneticStageId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.ParageneticStage" table.
 */
export type ParageneticStageUpdateRecord = Partial<ParageneticStageInsertRecord>;
