/**
 * AllSamples Mock Data Generator
 */

export function generateAllSamplesMock() {
	return [
		{
			id: "sample-001",
			SampleId: "mock-sample-001",
			CollarId: "mock-collar-001",
			SampleNumber: "FKD064-001",
			DepthFrom: 0.00,
			DepthTo: 1.00,
			SampleType: "Core",
			SampleMethod: "Half Core",
			Comments: "Standard geological sample",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "sample-002",
			SampleId: "mock-sample-002",
			CollarId: "mock-collar-001",
			SampleNumber: "FKD064-002",
			DepthFrom: 1.00,
			DepthTo: 2.00,
			SampleType: "Core",
			SampleMethod: "Half Core",
			Comments: "",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "sample-003",
			SampleId: "mock-sample-003",
			CollarId: "mock-collar-001",
			SampleNumber: "FKD064-003",
			DepthFrom: 2.00,
			DepthTo: 3.00,
			SampleType: "Core",
			SampleMethod: "Half Core",
			Comments: "",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "sample-004",
			SampleId: "mock-sample-004",
			CollarId: "mock-collar-001",
			SampleNumber: "FKD064-STD-001",
			DepthFrom: 3.00,
			DepthTo: 3.00,
			SampleType: "QAQC",
			SampleMethod: "Standard",
			Comments: "STD-02 insertion",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "sample-005",
			SampleId: "mock-sample-005",
			CollarId: "mock-collar-001",
			SampleNumber: "FKD064-004",
			DepthFrom: 3.00,
			DepthTo: 4.00,
			SampleType: "Core",
			SampleMethod: "Half Core",
			Comments: "",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "sample-006",
			SampleId: "mock-sample-006",
			CollarId: "mock-collar-001",
			SampleNumber: "FKD064-005",
			DepthFrom: 4.00,
			DepthTo: 5.00,
			SampleType: "Core",
			SampleMethod: "Half Core",
			Comments: "Visible sulfides",
			RowStatus: 0,
			ActiveInd: true,
		},
	];
}
