/**
 * GeologyCombinedLog Mock Data Generator
 */

export function generateGeologyCombinedLogMock() {
	return [
		{
			id: "geo-001",
			GeologyCombinedLogId: "mock-geo-001",
			CollarId: "mock-collar-001",
			DepthFrom: 0.00,
			DepthTo: 22.40,
			PrimaryLithology: "OVERBURDEN",
			Colour: "ORANGE/RED",
			Weathering: "OXIDIZED",
			GrainSize: "FINE",
			Structure: "MASSIVE",
			AlterationAlbite: 0,
			AlterationBiotite: 0,
			AlterationSericite: 1,
			AlterationSilica: 0,
			VeinMode: "",
			VeinPercent: 0,
			Comments: "Weathered overburden layer",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "geo-002",
			GeologyCombinedLogId: "mock-geo-002",
			CollarId: "mock-collar-001",
			DepthFrom: 22.40,
			DepthTo: 45.80,
			PrimaryLithology: "BASALT",
			Colour: "DK GREY",
			Weathering: "MODERATE",
			GrainSize: "MED",
			Structure: "SHEARED",
			AlterationAlbite: 2,
			AlterationBiotite: 0,
			AlterationSericite: 4,
			AlterationSilica: 1,
			VeinMode: "Quartz",
			VeinPercent: 15,
			Comments: "Sheared basalt with quartz veining",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "geo-003",
			GeologyCombinedLogId: "mock-geo-003",
			CollarId: "mock-collar-001",
			DepthFrom: 45.80,
			DepthTo: 68.20,
			PrimaryLithology: "QUARTZ VEIN",
			Colour: "WHITE",
			Weathering: "FRESH",
			GrainSize: "COARSE",
			Structure: "BRECCIATED",
			AlterationAlbite: 1,
			AlterationBiotite: 0,
			AlterationSericite: 3,
			AlterationSilica: 5,
			VeinMode: "Quartz-Carbonate",
			VeinPercent: 80,
			Comments: "Major quartz vein with brecciation. Visible sulfides.",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "geo-004",
			GeologyCombinedLogId: "mock-geo-004",
			CollarId: "mock-collar-001",
			DepthFrom: 68.20,
			DepthTo: 95.50,
			PrimaryLithology: "GRANITE",
			Colour: "LT GREY",
			Weathering: "FRESH",
			GrainSize: "COARSE",
			Structure: "MASSIVE",
			AlterationAlbite: 3,
			AlterationBiotite: 2,
			AlterationSericite: 1,
			AlterationSilica: 0,
			VeinMode: "Feldspar",
			VeinPercent: 5,
			Comments: "Fresh granite intrusion",
			RowStatus: 0,
			ActiveInd: true,
		},
		{
			id: "geo-005",
			GeologyCombinedLogId: "mock-geo-005",
			CollarId: "mock-collar-001",
			DepthFrom: 95.50,
			DepthTo: 120.00,
			PrimaryLithology: "SCHIST",
			Colour: "DK GREEN",
			Weathering: "MODERATE",
			GrainSize: "FINE",
			Structure: "FOLIATED",
			AlterationAlbite: 1,
			AlterationBiotite: 4,
			AlterationSericite: 2,
			AlterationSilica: 1,
			VeinMode: "Chlorite",
			VeinPercent: 10,
			Comments: "Chlorite-rich schist with strong foliation",
			RowStatus: 0,
			ActiveInd: true,
		},
	];
}
