// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.AssayElementGroup" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const AssayElementGroupTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	AssayElementGroupId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	ElementGroup: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.AssayElementGroup" table.
 * This type represents the raw database record without case transforms.
 */
export type AssayElementGroupBaseRecord = z.output<typeof AssayElementGroupTableBaseSchema>;

/**
 * Read transform for the "dbo.AssayElementGroup" table.
 * Maps database fields to app case properties.
 */
export function transformAssayElementGroupBaseRecord(data: AssayElementGroupBaseRecord): {
	assayElementGroupId: AssayElementGroupBaseRecord["AssayElementGroupId"]
	elementGroup: AssayElementGroupBaseRecord["ElementGroup"]
	sortOrder: AssayElementGroupBaseRecord["SortOrder"]
	isDefaultInd: AssayElementGroupBaseRecord["IsDefaultInd"]
	activeInd: AssayElementGroupBaseRecord["ActiveInd"]
	createdOnDt: AssayElementGroupBaseRecord["CreatedOnDt"]
	createdBy: AssayElementGroupBaseRecord["CreatedBy"]
	modifiedOnDt?: AssayElementGroupBaseRecord["ModifiedOnDt"]
	modifiedBy?: AssayElementGroupBaseRecord["ModifiedBy"]
	rv: AssayElementGroupBaseRecord["rv"]
} {
	return {
		assayElementGroupId: data.AssayElementGroupId,
		elementGroup: data.ElementGroup,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.AssayElementGroup" table (after casing transform).
 */
export const AssayElementGroupTableSchema = AssayElementGroupTableBaseSchema.transform(transformAssayElementGroupBaseRecord);

/**
 * Base insert/write schema for the "dbo.AssayElementGroup" table (no casing transforms).
 */
export const AssayElementGroupTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	assayElementGroupId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	elementGroup: z.string().max(50),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.AssayElementGroup" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type AssayElementGroupInsertBaseRecord = z.output<typeof AssayElementGroupTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.AssayElementGroup" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type AssayElementGroupUpdateBaseRecord = Partial<AssayElementGroupInsertBaseRecord>;

/**
 * Insert transform for the "dbo.AssayElementGroup" table.
 * Maps app cased properties to database fields.
 */
export function transformAssayElementGroupInsertBaseRecord(data: AssayElementGroupInsertBaseRecord): {
	AssayElementGroupId?: AssayElementGroupInsertBaseRecord["assayElementGroupId"]
	ElementGroup: AssayElementGroupInsertBaseRecord["elementGroup"]
	SortOrder?: AssayElementGroupInsertBaseRecord["sortOrder"]
	IsDefaultInd?: AssayElementGroupInsertBaseRecord["isDefaultInd"]
	ActiveInd?: AssayElementGroupInsertBaseRecord["activeInd"]
	CreatedOnDt?: AssayElementGroupInsertBaseRecord["createdOnDt"]
	CreatedBy?: AssayElementGroupInsertBaseRecord["createdBy"]
	ModifiedOnDt?: AssayElementGroupInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: AssayElementGroupInsertBaseRecord["modifiedBy"]
	rv: AssayElementGroupInsertBaseRecord["rv"]
} {
	return {
		AssayElementGroupId: data.assayElementGroupId,
		ElementGroup: data.elementGroup,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.AssayElementGroup" table.
 * Maps app cased properties to database fields.
 */
export function transformAssayElementGroupUpdateBaseRecord(data: AssayElementGroupUpdateBaseRecord): {
	AssayElementGroupId?: AssayElementGroupUpdateBaseRecord["assayElementGroupId"]
	ElementGroup: AssayElementGroupUpdateBaseRecord["elementGroup"]
	SortOrder?: AssayElementGroupUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: AssayElementGroupUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: AssayElementGroupUpdateBaseRecord["activeInd"]
	CreatedOnDt?: AssayElementGroupUpdateBaseRecord["createdOnDt"]
	CreatedBy?: AssayElementGroupUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: AssayElementGroupUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: AssayElementGroupUpdateBaseRecord["modifiedBy"]
	rv: AssayElementGroupUpdateBaseRecord["rv"]
} {
	return {
		AssayElementGroupId: data.assayElementGroupId,
		ElementGroup: data.elementGroup,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.AssayElementGroup" table (after casing transform).
 */
export const AssayElementGroupTableInsertSchema = AssayElementGroupTableInsertBaseSchema.transform(transformAssayElementGroupInsertBaseRecord);

/**
 * Update schema for the "dbo.AssayElementGroup" table (after casing transform).
 */
export const AssayElementGroupTableUpdateSchema = AssayElementGroupTableInsertBaseSchema.partial().transform(transformAssayElementGroupUpdateBaseRecord);

type TableInsertRecord = z.input<typeof AssayElementGroupTableInsertSchema>;
type TableReadRecord = z.output<typeof AssayElementGroupTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.AssayElementGroup" table.
 */
export interface AssayElementGroupRecord {
	assayElementGroupId: TableReadRecord["assayElementGroupId"]
	elementGroup: TableReadRecord["elementGroup"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.AssayElementGroup" table.
 */
export interface AssayElementGroupInsertRecord {
	/**
	 * @default: (newid())
	 */
	assayElementGroupId?: TableInsertRecord["assayElementGroupId"]
	/**
	 * @maxLen: 50
	 */
	elementGroup: TableInsertRecord["elementGroup"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.AssayElementGroup" table.
 */
export type AssayElementGroupUpdateRecord = Partial<AssayElementGroupInsertRecord>;
