// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.MinStyle" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const MinStyleTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	MinStyleId: z.any(),
});

/**
 * The base record type for the "dbo.MinStyle" table.
 * This type represents the raw database record without case transforms.
 */
export type MinStyleBaseRecord = z.output<typeof MinStyleTableBaseSchema>;

/**
 * Read transform for the "dbo.MinStyle" table.
 * Maps database fields to app case properties.
 */
export function transformMinStyleBaseRecord(data: MinStyleBaseRecord): {
	code: MinStyleBaseRecord["Code"]
	description: MinStyleBaseRecord["Description"]
	sortOrder: MinStyleBaseRecord["SortOrder"]
	isDefaultInd: MinStyleBaseRecord["IsDefaultInd"]
	activeInd: MinStyleBaseRecord["ActiveInd"]
	createdOnDt: MinStyleBaseRecord["CreatedOnDt"]
	createdBy: MinStyleBaseRecord["CreatedBy"]
	modifiedOnDt?: MinStyleBaseRecord["ModifiedOnDt"]
	modifiedBy?: MinStyleBaseRecord["ModifiedBy"]
	rv: MinStyleBaseRecord["rv"]
	minStyleId: MinStyleBaseRecord["MinStyleId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		minStyleId: data.MinStyleId,
	};
}

/**
 * Read schema for the "dbo.MinStyle" table (after casing transform).
 */
export const MinStyleTableSchema = MinStyleTableBaseSchema.transform(transformMinStyleBaseRecord);

/**
 * Base insert/write schema for the "dbo.MinStyle" table (no casing transforms).
 */
export const MinStyleTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	minStyleId: z.any().optional(),
});

/**
 * The base record type for the "dbo.MinStyle" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type MinStyleInsertBaseRecord = z.output<typeof MinStyleTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.MinStyle" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type MinStyleUpdateBaseRecord = Partial<MinStyleInsertBaseRecord>;

/**
 * Insert transform for the "dbo.MinStyle" table.
 * Maps app cased properties to database fields.
 */
export function transformMinStyleInsertBaseRecord(data: MinStyleInsertBaseRecord): {
	Code: MinStyleInsertBaseRecord["code"]
	Description: MinStyleInsertBaseRecord["description"]
	SortOrder?: MinStyleInsertBaseRecord["sortOrder"]
	IsDefaultInd?: MinStyleInsertBaseRecord["isDefaultInd"]
	ActiveInd?: MinStyleInsertBaseRecord["activeInd"]
	CreatedOnDt?: MinStyleInsertBaseRecord["createdOnDt"]
	CreatedBy?: MinStyleInsertBaseRecord["createdBy"]
	ModifiedOnDt?: MinStyleInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: MinStyleInsertBaseRecord["modifiedBy"]
	rv: MinStyleInsertBaseRecord["rv"]
	MinStyleId?: MinStyleInsertBaseRecord["minStyleId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		MinStyleId: data.minStyleId,
	};
}

/**
 * Update transform for the "dbo.MinStyle" table.
 * Maps app cased properties to database fields.
 */
export function transformMinStyleUpdateBaseRecord(data: MinStyleUpdateBaseRecord): {
	Code: MinStyleUpdateBaseRecord["code"]
	Description: MinStyleUpdateBaseRecord["description"]
	SortOrder?: MinStyleUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: MinStyleUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: MinStyleUpdateBaseRecord["activeInd"]
	CreatedOnDt?: MinStyleUpdateBaseRecord["createdOnDt"]
	CreatedBy?: MinStyleUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: MinStyleUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: MinStyleUpdateBaseRecord["modifiedBy"]
	rv: MinStyleUpdateBaseRecord["rv"]
	MinStyleId?: MinStyleUpdateBaseRecord["minStyleId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		MinStyleId: data.minStyleId,
	};
}

/**
 * Insert schema for the "dbo.MinStyle" table (after casing transform).
 */
export const MinStyleTableInsertSchema = MinStyleTableInsertBaseSchema.transform(transformMinStyleInsertBaseRecord);

/**
 * Update schema for the "dbo.MinStyle" table (after casing transform).
 */
export const MinStyleTableUpdateSchema = MinStyleTableInsertBaseSchema.partial().transform(transformMinStyleUpdateBaseRecord);

type TableInsertRecord = z.input<typeof MinStyleTableInsertSchema>;
type TableReadRecord = z.output<typeof MinStyleTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.MinStyle" table.
 */
export interface MinStyleRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	minStyleId: TableReadRecord["minStyleId"]
}

/**
 * Insert record (casing transformed) for the "dbo.MinStyle" table.
 */
export interface MinStyleInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	minStyleId?: TableInsertRecord["minStyleId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.MinStyle" table.
 */
export type MinStyleUpdateRecord = Partial<MinStyleInsertRecord>;
