// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.MovementSense" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const MovementSenseTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	MovementSenseId: z.any(),
});

/**
 * The base record type for the "dbo.MovementSense" table.
 * This type represents the raw database record without case transforms.
 */
export type MovementSenseBaseRecord = z.output<typeof MovementSenseTableBaseSchema>;

/**
 * Read transform for the "dbo.MovementSense" table.
 * Maps database fields to app case properties.
 */
export function transformMovementSenseBaseRecord(data: MovementSenseBaseRecord): {
	code: MovementSenseBaseRecord["Code"]
	description: MovementSenseBaseRecord["Description"]
	sortOrder: MovementSenseBaseRecord["SortOrder"]
	isDefaultInd: MovementSenseBaseRecord["IsDefaultInd"]
	activeInd: MovementSenseBaseRecord["ActiveInd"]
	createdOnDt: MovementSenseBaseRecord["CreatedOnDt"]
	createdBy: MovementSenseBaseRecord["CreatedBy"]
	modifiedOnDt?: MovementSenseBaseRecord["ModifiedOnDt"]
	modifiedBy?: MovementSenseBaseRecord["ModifiedBy"]
	rv: MovementSenseBaseRecord["rv"]
	movementSenseId: MovementSenseBaseRecord["MovementSenseId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		movementSenseId: data.MovementSenseId,
	};
}

/**
 * Read schema for the "dbo.MovementSense" table (after casing transform).
 */
export const MovementSenseTableSchema = MovementSenseTableBaseSchema.transform(transformMovementSenseBaseRecord);

/**
 * Base insert/write schema for the "dbo.MovementSense" table (no casing transforms).
 */
export const MovementSenseTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	movementSenseId: z.any().optional(),
});

/**
 * The base record type for the "dbo.MovementSense" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type MovementSenseInsertBaseRecord = z.output<typeof MovementSenseTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.MovementSense" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type MovementSenseUpdateBaseRecord = Partial<MovementSenseInsertBaseRecord>;

/**
 * Insert transform for the "dbo.MovementSense" table.
 * Maps app cased properties to database fields.
 */
export function transformMovementSenseInsertBaseRecord(data: MovementSenseInsertBaseRecord): {
	Code: MovementSenseInsertBaseRecord["code"]
	Description: MovementSenseInsertBaseRecord["description"]
	SortOrder?: MovementSenseInsertBaseRecord["sortOrder"]
	IsDefaultInd?: MovementSenseInsertBaseRecord["isDefaultInd"]
	ActiveInd?: MovementSenseInsertBaseRecord["activeInd"]
	CreatedOnDt?: MovementSenseInsertBaseRecord["createdOnDt"]
	CreatedBy?: MovementSenseInsertBaseRecord["createdBy"]
	ModifiedOnDt?: MovementSenseInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: MovementSenseInsertBaseRecord["modifiedBy"]
	rv: MovementSenseInsertBaseRecord["rv"]
	MovementSenseId?: MovementSenseInsertBaseRecord["movementSenseId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		MovementSenseId: data.movementSenseId,
	};
}

/**
 * Update transform for the "dbo.MovementSense" table.
 * Maps app cased properties to database fields.
 */
export function transformMovementSenseUpdateBaseRecord(data: MovementSenseUpdateBaseRecord): {
	Code: MovementSenseUpdateBaseRecord["code"]
	Description: MovementSenseUpdateBaseRecord["description"]
	SortOrder?: MovementSenseUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: MovementSenseUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: MovementSenseUpdateBaseRecord["activeInd"]
	CreatedOnDt?: MovementSenseUpdateBaseRecord["createdOnDt"]
	CreatedBy?: MovementSenseUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: MovementSenseUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: MovementSenseUpdateBaseRecord["modifiedBy"]
	rv: MovementSenseUpdateBaseRecord["rv"]
	MovementSenseId?: MovementSenseUpdateBaseRecord["movementSenseId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		MovementSenseId: data.movementSenseId,
	};
}

/**
 * Insert schema for the "dbo.MovementSense" table (after casing transform).
 */
export const MovementSenseTableInsertSchema = MovementSenseTableInsertBaseSchema.transform(transformMovementSenseInsertBaseRecord);

/**
 * Update schema for the "dbo.MovementSense" table (after casing transform).
 */
export const MovementSenseTableUpdateSchema = MovementSenseTableInsertBaseSchema.partial().transform(transformMovementSenseUpdateBaseRecord);

type TableInsertRecord = z.input<typeof MovementSenseTableInsertSchema>;
type TableReadRecord = z.output<typeof MovementSenseTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.MovementSense" table.
 */
export interface MovementSenseRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	movementSenseId: TableReadRecord["movementSenseId"]
}

/**
 * Insert record (casing transformed) for the "dbo.MovementSense" table.
 */
export interface MovementSenseInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	movementSenseId?: TableInsertRecord["movementSenseId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.MovementSense" table.
 */
export type MovementSenseUpdateRecord = Partial<MovementSenseInsertRecord>;
