// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.AuditLog" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const AuditLogTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	AuditLogId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	Organization: z.string(),
	/**
	 * dataType: uniqueidentifier
	 */
	EntityId: z.any(),
	/**
	 * dataType: tinyint
	 */
	EntityTypeId: z.number(),
	/**
	 * dataType: nvarchar
	 */
	Action: z.string(),
	/**
	 * dataType: nvarchar
	 */
	ActionBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ActionOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	JsonData: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
});

/**
 * The base record type for the "dbo.AuditLog" table.
 * This type represents the raw database record without case transforms.
 */
export type AuditLogBaseRecord = z.output<typeof AuditLogTableBaseSchema>;

/**
 * Read transform for the "dbo.AuditLog" table.
 * Maps database fields to app case properties.
 */
export function transformAuditLogBaseRecord(data: AuditLogBaseRecord): {
	auditLogId: AuditLogBaseRecord["AuditLogId"]
	organization: AuditLogBaseRecord["Organization"]
	entityId: AuditLogBaseRecord["EntityId"]
	entityTypeId: AuditLogBaseRecord["EntityTypeId"]
	action: AuditLogBaseRecord["Action"]
	actionBy: AuditLogBaseRecord["ActionBy"]
	actionOnDt: AuditLogBaseRecord["ActionOnDt"]
	jsonData?: AuditLogBaseRecord["JsonData"]
	activeInd: AuditLogBaseRecord["ActiveInd"]
	createdOnDt: AuditLogBaseRecord["CreatedOnDt"]
	createdBy: AuditLogBaseRecord["CreatedBy"]
	modifiedOnDt?: AuditLogBaseRecord["ModifiedOnDt"]
	modifiedBy?: AuditLogBaseRecord["ModifiedBy"]
} {
	return {
		auditLogId: data.AuditLogId,
		organization: data.Organization,
		entityId: data.EntityId,
		entityTypeId: data.EntityTypeId,
		action: data.Action,
		actionBy: data.ActionBy,
		actionOnDt: data.ActionOnDt,
		jsonData: data.JsonData,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
	};
}

/**
 * Read schema for the "dbo.AuditLog" table (after casing transform).
 */
export const AuditLogTableSchema = AuditLogTableBaseSchema.transform(transformAuditLogBaseRecord);

/**
 * Base insert/write schema for the "dbo.AuditLog" table (no casing transforms).
 */
export const AuditLogTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	auditLogId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	organization: z.string().max(30),
	/**
	 * dataType: uniqueidentifier
	 */
	entityId: z.any(),
	/**
	 * dataType: tinyint
	 */
	entityTypeId: z.number().int(),
	/**
	 * dataType: nvarchar
	 */
	action: z.string().max(50),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](50),coalesce(session_context(N'UserNm'),suser_sname())))
	 */
	actionBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	actionOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	jsonData: z.string().max(-1).nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](50),coalesce(session_context(N'UserNm'),suser_sname())))
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
});

/**
 * The base record type for the "dbo.AuditLog" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type AuditLogInsertBaseRecord = z.output<typeof AuditLogTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.AuditLog" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type AuditLogUpdateBaseRecord = Partial<AuditLogInsertBaseRecord>;

/**
 * Insert transform for the "dbo.AuditLog" table.
 * Maps app cased properties to database fields.
 */
export function transformAuditLogInsertBaseRecord(data: AuditLogInsertBaseRecord): {
	AuditLogId?: AuditLogInsertBaseRecord["auditLogId"]
	Organization: AuditLogInsertBaseRecord["organization"]
	EntityId: AuditLogInsertBaseRecord["entityId"]
	EntityTypeId: AuditLogInsertBaseRecord["entityTypeId"]
	Action: AuditLogInsertBaseRecord["action"]
	ActionBy?: AuditLogInsertBaseRecord["actionBy"]
	ActionOnDt?: AuditLogInsertBaseRecord["actionOnDt"]
	JsonData?: AuditLogInsertBaseRecord["jsonData"]
	ActiveInd?: AuditLogInsertBaseRecord["activeInd"]
	CreatedOnDt?: AuditLogInsertBaseRecord["createdOnDt"]
	CreatedBy?: AuditLogInsertBaseRecord["createdBy"]
	ModifiedOnDt?: AuditLogInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: AuditLogInsertBaseRecord["modifiedBy"]
} {
	return {
		AuditLogId: data.auditLogId,
		Organization: data.organization,
		EntityId: data.entityId,
		EntityTypeId: data.entityTypeId,
		Action: data.action,
		ActionBy: data.actionBy,
		ActionOnDt: data.actionOnDt,
		JsonData: data.jsonData,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
	};
}

/**
 * Update transform for the "dbo.AuditLog" table.
 * Maps app cased properties to database fields.
 */
export function transformAuditLogUpdateBaseRecord(data: AuditLogUpdateBaseRecord): {
	AuditLogId?: AuditLogUpdateBaseRecord["auditLogId"]
	Organization: AuditLogUpdateBaseRecord["organization"]
	EntityId: AuditLogUpdateBaseRecord["entityId"]
	EntityTypeId: AuditLogUpdateBaseRecord["entityTypeId"]
	Action: AuditLogUpdateBaseRecord["action"]
	ActionBy?: AuditLogUpdateBaseRecord["actionBy"]
	ActionOnDt?: AuditLogUpdateBaseRecord["actionOnDt"]
	JsonData?: AuditLogUpdateBaseRecord["jsonData"]
	ActiveInd?: AuditLogUpdateBaseRecord["activeInd"]
	CreatedOnDt?: AuditLogUpdateBaseRecord["createdOnDt"]
	CreatedBy?: AuditLogUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: AuditLogUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: AuditLogUpdateBaseRecord["modifiedBy"]
} {
	return {
		AuditLogId: data.auditLogId,
		Organization: data.organization,
		EntityId: data.entityId,
		EntityTypeId: data.entityTypeId,
		Action: data.action,
		ActionBy: data.actionBy,
		ActionOnDt: data.actionOnDt,
		JsonData: data.jsonData,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
	};
}

/**
 * Insert schema for the "dbo.AuditLog" table (after casing transform).
 */
export const AuditLogTableInsertSchema = AuditLogTableInsertBaseSchema.transform(transformAuditLogInsertBaseRecord);

/**
 * Update schema for the "dbo.AuditLog" table (after casing transform).
 */
export const AuditLogTableUpdateSchema = AuditLogTableInsertBaseSchema.partial().transform(transformAuditLogUpdateBaseRecord);

type TableInsertRecord = z.input<typeof AuditLogTableInsertSchema>;
type TableReadRecord = z.output<typeof AuditLogTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.AuditLog" table.
 */
export interface AuditLogRecord {
	auditLogId: TableReadRecord["auditLogId"]
	organization: TableReadRecord["organization"]
	entityId: TableReadRecord["entityId"]
	entityTypeId: TableReadRecord["entityTypeId"]
	action: TableReadRecord["action"]
	actionBy: TableReadRecord["actionBy"]
	actionOnDt: TableReadRecord["actionOnDt"]
	jsonData?: TableReadRecord["jsonData"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
}

/**
 * Insert record (casing transformed) for the "dbo.AuditLog" table.
 */
export interface AuditLogInsertRecord {
	/**
	 * @default: (newid())
	 */
	auditLogId?: TableInsertRecord["auditLogId"]
	/**
	 * @maxLen: 30
	 */
	organization: TableInsertRecord["organization"]
	entityId: TableInsertRecord["entityId"]
	entityTypeId: TableInsertRecord["entityTypeId"]
	/**
	 * @maxLen: 50
	 */
	action: TableInsertRecord["action"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](50),coalesce(session_context(N'UserNm'),suser_sname())))
	 */
	actionBy?: TableInsertRecord["actionBy"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	actionOnDt?: TableInsertRecord["actionOnDt"]
	/**
	 * @maxLen: -1
	 */
	jsonData?: TableInsertRecord["jsonData"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](50),coalesce(session_context(N'UserNm'),suser_sname())))
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
}

/**
 * Updatable record (casing transformed) for the "dbo.AuditLog" table.
 */
export type AuditLogUpdateRecord = Partial<AuditLogInsertRecord>;
