// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.SubjRec" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const SubjRecTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	SubjRecId: z.any(),
});

/**
 * The base record type for the "dbo.SubjRec" table.
 * This type represents the raw database record without case transforms.
 */
export type SubjRecBaseRecord = z.output<typeof SubjRecTableBaseSchema>;

/**
 * Read transform for the "dbo.SubjRec" table.
 * Maps database fields to app case properties.
 */
export function transformSubjRecBaseRecord(data: SubjRecBaseRecord): {
	code: SubjRecBaseRecord["Code"]
	description: SubjRecBaseRecord["Description"]
	sortOrder: SubjRecBaseRecord["SortOrder"]
	isDefaultInd: SubjRecBaseRecord["IsDefaultInd"]
	activeInd: SubjRecBaseRecord["ActiveInd"]
	createdOnDt: SubjRecBaseRecord["CreatedOnDt"]
	createdBy: SubjRecBaseRecord["CreatedBy"]
	modifiedOnDt?: SubjRecBaseRecord["ModifiedOnDt"]
	modifiedBy?: SubjRecBaseRecord["ModifiedBy"]
	rv: SubjRecBaseRecord["rv"]
	subjRecId: SubjRecBaseRecord["SubjRecId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		subjRecId: data.SubjRecId,
	};
}

/**
 * Read schema for the "dbo.SubjRec" table (after casing transform).
 */
export const SubjRecTableSchema = SubjRecTableBaseSchema.transform(transformSubjRecBaseRecord);

/**
 * Base insert/write schema for the "dbo.SubjRec" table (no casing transforms).
 */
export const SubjRecTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	subjRecId: z.any().optional(),
});

/**
 * The base record type for the "dbo.SubjRec" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type SubjRecInsertBaseRecord = z.output<typeof SubjRecTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.SubjRec" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type SubjRecUpdateBaseRecord = Partial<SubjRecInsertBaseRecord>;

/**
 * Insert transform for the "dbo.SubjRec" table.
 * Maps app cased properties to database fields.
 */
export function transformSubjRecInsertBaseRecord(data: SubjRecInsertBaseRecord): {
	Code: SubjRecInsertBaseRecord["code"]
	Description: SubjRecInsertBaseRecord["description"]
	SortOrder?: SubjRecInsertBaseRecord["sortOrder"]
	IsDefaultInd?: SubjRecInsertBaseRecord["isDefaultInd"]
	ActiveInd?: SubjRecInsertBaseRecord["activeInd"]
	CreatedOnDt?: SubjRecInsertBaseRecord["createdOnDt"]
	CreatedBy?: SubjRecInsertBaseRecord["createdBy"]
	ModifiedOnDt?: SubjRecInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: SubjRecInsertBaseRecord["modifiedBy"]
	rv: SubjRecInsertBaseRecord["rv"]
	SubjRecId?: SubjRecInsertBaseRecord["subjRecId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		SubjRecId: data.subjRecId,
	};
}

/**
 * Update transform for the "dbo.SubjRec" table.
 * Maps app cased properties to database fields.
 */
export function transformSubjRecUpdateBaseRecord(data: SubjRecUpdateBaseRecord): {
	Code: SubjRecUpdateBaseRecord["code"]
	Description: SubjRecUpdateBaseRecord["description"]
	SortOrder?: SubjRecUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: SubjRecUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: SubjRecUpdateBaseRecord["activeInd"]
	CreatedOnDt?: SubjRecUpdateBaseRecord["createdOnDt"]
	CreatedBy?: SubjRecUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: SubjRecUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: SubjRecUpdateBaseRecord["modifiedBy"]
	rv: SubjRecUpdateBaseRecord["rv"]
	SubjRecId?: SubjRecUpdateBaseRecord["subjRecId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		SubjRecId: data.subjRecId,
	};
}

/**
 * Insert schema for the "dbo.SubjRec" table (after casing transform).
 */
export const SubjRecTableInsertSchema = SubjRecTableInsertBaseSchema.transform(transformSubjRecInsertBaseRecord);

/**
 * Update schema for the "dbo.SubjRec" table (after casing transform).
 */
export const SubjRecTableUpdateSchema = SubjRecTableInsertBaseSchema.partial().transform(transformSubjRecUpdateBaseRecord);

type TableInsertRecord = z.input<typeof SubjRecTableInsertSchema>;
type TableReadRecord = z.output<typeof SubjRecTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.SubjRec" table.
 */
export interface SubjRecRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	subjRecId: TableReadRecord["subjRecId"]
}

/**
 * Insert record (casing transformed) for the "dbo.SubjRec" table.
 */
export interface SubjRecInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	subjRecId?: TableInsertRecord["subjRecId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.SubjRec" table.
 */
export type SubjRecUpdateRecord = Partial<SubjRecInsertRecord>;
