// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.LeaseStatus" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const LeaseStatusTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	LeaseStatusId: z.any(),
});

/**
 * The base record type for the "dbo.LeaseStatus" table.
 * This type represents the raw database record without case transforms.
 */
export type LeaseStatusBaseRecord = z.output<typeof LeaseStatusTableBaseSchema>;

/**
 * Read transform for the "dbo.LeaseStatus" table.
 * Maps database fields to app case properties.
 */
export function transformLeaseStatusBaseRecord(data: LeaseStatusBaseRecord): {
	code: LeaseStatusBaseRecord["Code"]
	description: LeaseStatusBaseRecord["Description"]
	sortOrder: LeaseStatusBaseRecord["SortOrder"]
	isDefaultInd: LeaseStatusBaseRecord["IsDefaultInd"]
	activeInd: LeaseStatusBaseRecord["ActiveInd"]
	createdOnDt: LeaseStatusBaseRecord["CreatedOnDt"]
	createdBy: LeaseStatusBaseRecord["CreatedBy"]
	modifiedOnDt?: LeaseStatusBaseRecord["ModifiedOnDt"]
	modifiedBy?: LeaseStatusBaseRecord["ModifiedBy"]
	rv: LeaseStatusBaseRecord["rv"]
	leaseStatusId: LeaseStatusBaseRecord["LeaseStatusId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		leaseStatusId: data.LeaseStatusId,
	};
}

/**
 * Read schema for the "dbo.LeaseStatus" table (after casing transform).
 */
export const LeaseStatusTableSchema = LeaseStatusTableBaseSchema.transform(transformLeaseStatusBaseRecord);

/**
 * Base insert/write schema for the "dbo.LeaseStatus" table (no casing transforms).
 */
export const LeaseStatusTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	leaseStatusId: z.any().optional(),
});

/**
 * The base record type for the "dbo.LeaseStatus" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type LeaseStatusInsertBaseRecord = z.output<typeof LeaseStatusTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.LeaseStatus" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type LeaseStatusUpdateBaseRecord = Partial<LeaseStatusInsertBaseRecord>;

/**
 * Insert transform for the "dbo.LeaseStatus" table.
 * Maps app cased properties to database fields.
 */
export function transformLeaseStatusInsertBaseRecord(data: LeaseStatusInsertBaseRecord): {
	Code: LeaseStatusInsertBaseRecord["code"]
	Description: LeaseStatusInsertBaseRecord["description"]
	SortOrder?: LeaseStatusInsertBaseRecord["sortOrder"]
	IsDefaultInd?: LeaseStatusInsertBaseRecord["isDefaultInd"]
	ActiveInd?: LeaseStatusInsertBaseRecord["activeInd"]
	CreatedOnDt?: LeaseStatusInsertBaseRecord["createdOnDt"]
	CreatedBy?: LeaseStatusInsertBaseRecord["createdBy"]
	ModifiedOnDt?: LeaseStatusInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: LeaseStatusInsertBaseRecord["modifiedBy"]
	rv: LeaseStatusInsertBaseRecord["rv"]
	LeaseStatusId?: LeaseStatusInsertBaseRecord["leaseStatusId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		LeaseStatusId: data.leaseStatusId,
	};
}

/**
 * Update transform for the "dbo.LeaseStatus" table.
 * Maps app cased properties to database fields.
 */
export function transformLeaseStatusUpdateBaseRecord(data: LeaseStatusUpdateBaseRecord): {
	Code: LeaseStatusUpdateBaseRecord["code"]
	Description: LeaseStatusUpdateBaseRecord["description"]
	SortOrder?: LeaseStatusUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: LeaseStatusUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: LeaseStatusUpdateBaseRecord["activeInd"]
	CreatedOnDt?: LeaseStatusUpdateBaseRecord["createdOnDt"]
	CreatedBy?: LeaseStatusUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: LeaseStatusUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: LeaseStatusUpdateBaseRecord["modifiedBy"]
	rv: LeaseStatusUpdateBaseRecord["rv"]
	LeaseStatusId?: LeaseStatusUpdateBaseRecord["leaseStatusId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		LeaseStatusId: data.leaseStatusId,
	};
}

/**
 * Insert schema for the "dbo.LeaseStatus" table (after casing transform).
 */
export const LeaseStatusTableInsertSchema = LeaseStatusTableInsertBaseSchema.transform(transformLeaseStatusInsertBaseRecord);

/**
 * Update schema for the "dbo.LeaseStatus" table (after casing transform).
 */
export const LeaseStatusTableUpdateSchema = LeaseStatusTableInsertBaseSchema.partial().transform(transformLeaseStatusUpdateBaseRecord);

type TableInsertRecord = z.input<typeof LeaseStatusTableInsertSchema>;
type TableReadRecord = z.output<typeof LeaseStatusTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.LeaseStatus" table.
 */
export interface LeaseStatusRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	leaseStatusId: TableReadRecord["leaseStatusId"]
}

/**
 * Insert record (casing transformed) for the "dbo.LeaseStatus" table.
 */
export interface LeaseStatusInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	leaseStatusId?: TableInsertRecord["leaseStatusId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.LeaseStatus" table.
 */
export type LeaseStatusUpdateRecord = Partial<LeaseStatusInsertRecord>;
