// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.Phase" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const PhaseTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	PhaseId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	Phase: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Project: z.string(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: int
	 */
	SortOrder: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.Phase" table.
 * This type represents the raw database record without case transforms.
 */
export type PhaseBaseRecord = z.output<typeof PhaseTableBaseSchema>;

/**
 * Read transform for the "dbo.Phase" table.
 * Maps database fields to app case properties.
 */
export function transformPhaseBaseRecord(data: PhaseBaseRecord): {
	phaseId: PhaseBaseRecord["PhaseId"]
	phase: PhaseBaseRecord["Phase"]
	description?: PhaseBaseRecord["Description"]
	project: PhaseBaseRecord["Project"]
	activeInd: PhaseBaseRecord["ActiveInd"]
	sortOrder?: PhaseBaseRecord["SortOrder"]
	createdOnDt: PhaseBaseRecord["CreatedOnDt"]
	createdBy: PhaseBaseRecord["CreatedBy"]
	modifiedOnDt?: PhaseBaseRecord["ModifiedOnDt"]
	modifiedBy?: PhaseBaseRecord["ModifiedBy"]
	rv: PhaseBaseRecord["rv"]
} {
	return {
		phaseId: data.PhaseId,
		phase: data.Phase,
		description: data.Description,
		project: data.Project,
		activeInd: data.ActiveInd,
		sortOrder: data.SortOrder,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.Phase" table (after casing transform).
 */
export const PhaseTableSchema = PhaseTableBaseSchema.transform(transformPhaseBaseRecord);

/**
 * Base insert/write schema for the "dbo.Phase" table (no casing transforms).
 */
export const PhaseTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	phaseId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	phase: z.string().max(30),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(-1).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	project: z.string().max(100),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: int
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.Phase" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type PhaseInsertBaseRecord = z.output<typeof PhaseTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.Phase" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type PhaseUpdateBaseRecord = Partial<PhaseInsertBaseRecord>;

/**
 * Insert transform for the "dbo.Phase" table.
 * Maps app cased properties to database fields.
 */
export function transformPhaseInsertBaseRecord(data: PhaseInsertBaseRecord): {
	PhaseId?: PhaseInsertBaseRecord["phaseId"]
	Phase: PhaseInsertBaseRecord["phase"]
	Description?: PhaseInsertBaseRecord["description"]
	Project: PhaseInsertBaseRecord["project"]
	ActiveInd?: PhaseInsertBaseRecord["activeInd"]
	SortOrder?: PhaseInsertBaseRecord["sortOrder"]
	CreatedOnDt?: PhaseInsertBaseRecord["createdOnDt"]
	CreatedBy?: PhaseInsertBaseRecord["createdBy"]
	ModifiedOnDt?: PhaseInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: PhaseInsertBaseRecord["modifiedBy"]
	rv: PhaseInsertBaseRecord["rv"]
} {
	return {
		PhaseId: data.phaseId,
		Phase: data.phase,
		Description: data.description,
		Project: data.project,
		ActiveInd: data.activeInd,
		SortOrder: data.sortOrder,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.Phase" table.
 * Maps app cased properties to database fields.
 */
export function transformPhaseUpdateBaseRecord(data: PhaseUpdateBaseRecord): {
	PhaseId?: PhaseUpdateBaseRecord["phaseId"]
	Phase: PhaseUpdateBaseRecord["phase"]
	Description?: PhaseUpdateBaseRecord["description"]
	Project: PhaseUpdateBaseRecord["project"]
	ActiveInd?: PhaseUpdateBaseRecord["activeInd"]
	SortOrder?: PhaseUpdateBaseRecord["sortOrder"]
	CreatedOnDt?: PhaseUpdateBaseRecord["createdOnDt"]
	CreatedBy?: PhaseUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: PhaseUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: PhaseUpdateBaseRecord["modifiedBy"]
	rv: PhaseUpdateBaseRecord["rv"]
} {
	return {
		PhaseId: data.phaseId,
		Phase: data.phase,
		Description: data.description,
		Project: data.project,
		ActiveInd: data.activeInd,
		SortOrder: data.sortOrder,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.Phase" table (after casing transform).
 */
export const PhaseTableInsertSchema = PhaseTableInsertBaseSchema.transform(transformPhaseInsertBaseRecord);

/**
 * Update schema for the "dbo.Phase" table (after casing transform).
 */
export const PhaseTableUpdateSchema = PhaseTableInsertBaseSchema.partial().transform(transformPhaseUpdateBaseRecord);

type TableInsertRecord = z.input<typeof PhaseTableInsertSchema>;
type TableReadRecord = z.output<typeof PhaseTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.Phase" table.
 */
export interface PhaseRecord {
	phaseId: TableReadRecord["phaseId"]
	phase: TableReadRecord["phase"]
	description?: TableReadRecord["description"]
	project: TableReadRecord["project"]
	activeInd: TableReadRecord["activeInd"]
	sortOrder?: TableReadRecord["sortOrder"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.Phase" table.
 */
export interface PhaseInsertRecord {
	/**
	 * @default: (newid())
	 */
	phaseId?: TableInsertRecord["phaseId"]
	/**
	 * @maxLen: 30
	 */
	phase: TableInsertRecord["phase"]
	/**
	 * @maxLen: -1
	 */
	description?: TableInsertRecord["description"]
	/**
	 * @maxLen: 100
	 */
	project: TableInsertRecord["project"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.Phase" table.
 */
export type PhaseUpdateRecord = Partial<PhaseInsertRecord>;
