// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.vw_InsertionFrequencySummary" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const VwInsertionfrequencysummaryTableBaseSchema = z.object({
	/**
	 * dataType: int
	 */
	Organization: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	Target: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	Year: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	LabCode: z.string(),
	/**
	 * dataType: int
	 */
	OrigCount: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	QCCount: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: decimal
	 */
	QAQC_Insertion_Ratio: z.number().nullable().transform(value => value ?? undefined).optional(),
});

/**
 * The base record type for the "dbo.vw_InsertionFrequencySummary" table.
 * This type represents the raw database record without case transforms.
 */
export type VwInsertionFrequencySummaryBaseRecord = z.output<typeof VwInsertionfrequencysummaryTableBaseSchema>;

/**
 * Read transform for the "dbo.vw_InsertionFrequencySummary" table.
 * Maps database fields to app case properties.
 */
export function transformVwInsertionFrequencySummaryBaseRecord(data: VwInsertionFrequencySummaryBaseRecord): {
	organization?: VwInsertionFrequencySummaryBaseRecord["Organization"]
	target?: VwInsertionFrequencySummaryBaseRecord["Target"]
	year?: VwInsertionFrequencySummaryBaseRecord["Year"]
	labCode: VwInsertionFrequencySummaryBaseRecord["LabCode"]
	origCount?: VwInsertionFrequencySummaryBaseRecord["OrigCount"]
	qCCount?: VwInsertionFrequencySummaryBaseRecord["QCCount"]
	qaqcInsertionRatio?: VwInsertionFrequencySummaryBaseRecord["QAQC_Insertion_Ratio"]
} {
	return {
		organization: data.Organization,
		target: data.Target,
		year: data.Year,
		labCode: data.LabCode,
		origCount: data.OrigCount,
		qCCount: data.QCCount,
		qaqcInsertionRatio: data.QAQC_Insertion_Ratio,
	};
}

/**
 * Read schema for the "dbo.vw_InsertionFrequencySummary" table (after casing transform).
 */
export const VwInsertionfrequencysummaryTableSchema = VwInsertionfrequencysummaryTableBaseSchema.transform(transformVwInsertionFrequencySummaryBaseRecord);

/**
 * Base insert/write schema for the "dbo.vw_InsertionFrequencySummary" table (no casing transforms).
 */
export const VwInsertionfrequencysummaryTableInsertBaseSchema = z.object({
	/**
	 * dataType: int
	 */
	organization: z.number().int().nullable().optional(),
	/**
	 * dataType: int
	 */
	target: z.number().int().nullable().optional(),
	/**
	 * dataType: int
	 */
	year: z.number().int().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	labCode: z.string().max(20),
	/**
	 * dataType: int
	 */
	origCount: z.number().int().nullable().optional(),
	/**
	 * dataType: int
	 */
	qCCount: z.number().int().nullable().optional(),
	/**
	 * dataType: decimal
	 */
	qaqcInsertionRatio: z.number().nullable().optional(),
});

/**
 * The base record type for the "dbo.vw_InsertionFrequencySummary" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type VwInsertionFrequencySummaryInsertBaseRecord = z.output<typeof VwInsertionfrequencysummaryTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.vw_InsertionFrequencySummary" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type VwInsertionFrequencySummaryUpdateBaseRecord = Partial<VwInsertionFrequencySummaryInsertBaseRecord>;

/**
 * Insert transform for the "dbo.vw_InsertionFrequencySummary" table.
 * Maps app cased properties to database fields.
 */
export function transformVwInsertionFrequencySummaryInsertBaseRecord(data: VwInsertionFrequencySummaryInsertBaseRecord): {
	Organization?: VwInsertionFrequencySummaryInsertBaseRecord["organization"]
	Target?: VwInsertionFrequencySummaryInsertBaseRecord["target"]
	Year?: VwInsertionFrequencySummaryInsertBaseRecord["year"]
	LabCode: VwInsertionFrequencySummaryInsertBaseRecord["labCode"]
	OrigCount?: VwInsertionFrequencySummaryInsertBaseRecord["origCount"]
	QCCount?: VwInsertionFrequencySummaryInsertBaseRecord["qCCount"]
	QAQC_Insertion_Ratio?: VwInsertionFrequencySummaryInsertBaseRecord["qaqcInsertionRatio"]
} {
	return {
		Organization: data.organization,
		Target: data.target,
		Year: data.year,
		LabCode: data.labCode,
		OrigCount: data.origCount,
		QCCount: data.qCCount,
		QAQC_Insertion_Ratio: data.qaqcInsertionRatio,
	};
}

/**
 * Update transform for the "dbo.vw_InsertionFrequencySummary" table.
 * Maps app cased properties to database fields.
 */
export function transformVwInsertionFrequencySummaryUpdateBaseRecord(data: VwInsertionFrequencySummaryUpdateBaseRecord): {
	Organization?: VwInsertionFrequencySummaryUpdateBaseRecord["organization"]
	Target?: VwInsertionFrequencySummaryUpdateBaseRecord["target"]
	Year?: VwInsertionFrequencySummaryUpdateBaseRecord["year"]
	LabCode: VwInsertionFrequencySummaryUpdateBaseRecord["labCode"]
	OrigCount?: VwInsertionFrequencySummaryUpdateBaseRecord["origCount"]
	QCCount?: VwInsertionFrequencySummaryUpdateBaseRecord["qCCount"]
	QAQC_Insertion_Ratio?: VwInsertionFrequencySummaryUpdateBaseRecord["qaqcInsertionRatio"]
} {
	return {
		Organization: data.organization,
		Target: data.target,
		Year: data.year,
		LabCode: data.labCode,
		OrigCount: data.origCount,
		QCCount: data.qCCount,
		QAQC_Insertion_Ratio: data.qaqcInsertionRatio,
	};
}

/**
 * Insert schema for the "dbo.vw_InsertionFrequencySummary" table (after casing transform).
 */
export const VwInsertionfrequencysummaryTableInsertSchema = VwInsertionfrequencysummaryTableInsertBaseSchema.transform(transformVwInsertionFrequencySummaryInsertBaseRecord);

/**
 * Update schema for the "dbo.vw_InsertionFrequencySummary" table (after casing transform).
 */
export const VwInsertionfrequencysummaryTableUpdateSchema = VwInsertionfrequencysummaryTableInsertBaseSchema.partial().transform(transformVwInsertionFrequencySummaryUpdateBaseRecord);

type TableInsertRecord = z.input<typeof VwInsertionfrequencysummaryTableInsertSchema>;
type TableReadRecord = z.output<typeof VwInsertionfrequencysummaryTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.vw_InsertionFrequencySummary" table.
 */
export interface VwInsertionFrequencySummaryRecord {
	organization?: TableReadRecord["organization"]
	target?: TableReadRecord["target"]
	year?: TableReadRecord["year"]
	labCode: TableReadRecord["labCode"]
	origCount?: TableReadRecord["origCount"]
	qCCount?: TableReadRecord["qCCount"]
	qaqcInsertionRatio?: TableReadRecord["qaqcInsertionRatio"]
}

/**
 * Insert record (casing transformed) for the "dbo.vw_InsertionFrequencySummary" table.
 */
export interface VwInsertionFrequencySummaryInsertRecord {
	organization?: TableInsertRecord["organization"]
	target?: TableInsertRecord["target"]
	year?: TableInsertRecord["year"]
	/**
	 * @maxLen: 20
	 */
	labCode: TableInsertRecord["labCode"]
	origCount?: TableInsertRecord["origCount"]
	qCCount?: TableInsertRecord["qCCount"]
	qaqcInsertionRatio?: TableInsertRecord["qaqcInsertionRatio"]
}

/**
 * Updatable record (casing transformed) for the "dbo.vw_InsertionFrequencySummary" table.
 */
export type VwInsertionFrequencySummaryUpdateRecord = Partial<VwInsertionFrequencySummaryInsertRecord>;
