// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.Instrument" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const InstrumentTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: nvarchar
	 */
	InstrumentType: z.string(),
	/**
	 * dataType: int
	 */
	Priority: z.number(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	InstrumentId: z.any(),
});

/**
 * The base record type for the "dbo.Instrument" table.
 * This type represents the raw database record without case transforms.
 */
export type InstrumentBaseRecord = z.output<typeof InstrumentTableBaseSchema>;

/**
 * Read transform for the "dbo.Instrument" table.
 * Maps database fields to app case properties.
 */
export function transformInstrumentBaseRecord(data: InstrumentBaseRecord): {
	code: InstrumentBaseRecord["Code"]
	description: InstrumentBaseRecord["Description"]
	instrumentType: InstrumentBaseRecord["InstrumentType"]
	priority: InstrumentBaseRecord["Priority"]
	sortOrder: InstrumentBaseRecord["SortOrder"]
	isDefaultInd: InstrumentBaseRecord["IsDefaultInd"]
	activeInd: InstrumentBaseRecord["ActiveInd"]
	createdOnDt: InstrumentBaseRecord["CreatedOnDt"]
	createdBy: InstrumentBaseRecord["CreatedBy"]
	modifiedOnDt?: InstrumentBaseRecord["ModifiedOnDt"]
	modifiedBy?: InstrumentBaseRecord["ModifiedBy"]
	rv: InstrumentBaseRecord["rv"]
	instrumentId: InstrumentBaseRecord["InstrumentId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		instrumentType: data.InstrumentType,
		priority: data.Priority,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		instrumentId: data.InstrumentId,
	};
}

/**
 * Read schema for the "dbo.Instrument" table (after casing transform).
 */
export const InstrumentTableSchema = InstrumentTableBaseSchema.transform(transformInstrumentBaseRecord);

/**
 * Base insert/write schema for the "dbo.Instrument" table (no casing transforms).
 */
export const InstrumentTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: nvarchar
	 * defaultValue: (N'NR')
	 */
	instrumentType: z.string().max(50).optional(),
	/**
	 * dataType: int
	 */
	priority: z.number().int(),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	instrumentId: z.any().optional(),
});

/**
 * The base record type for the "dbo.Instrument" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type InstrumentInsertBaseRecord = z.output<typeof InstrumentTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.Instrument" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type InstrumentUpdateBaseRecord = Partial<InstrumentInsertBaseRecord>;

/**
 * Insert transform for the "dbo.Instrument" table.
 * Maps app cased properties to database fields.
 */
export function transformInstrumentInsertBaseRecord(data: InstrumentInsertBaseRecord): {
	Code: InstrumentInsertBaseRecord["code"]
	Description: InstrumentInsertBaseRecord["description"]
	InstrumentType?: InstrumentInsertBaseRecord["instrumentType"]
	Priority: InstrumentInsertBaseRecord["priority"]
	SortOrder?: InstrumentInsertBaseRecord["sortOrder"]
	IsDefaultInd?: InstrumentInsertBaseRecord["isDefaultInd"]
	ActiveInd?: InstrumentInsertBaseRecord["activeInd"]
	CreatedOnDt?: InstrumentInsertBaseRecord["createdOnDt"]
	CreatedBy?: InstrumentInsertBaseRecord["createdBy"]
	ModifiedOnDt?: InstrumentInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: InstrumentInsertBaseRecord["modifiedBy"]
	rv: InstrumentInsertBaseRecord["rv"]
	InstrumentId?: InstrumentInsertBaseRecord["instrumentId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		InstrumentType: data.instrumentType,
		Priority: data.priority,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		InstrumentId: data.instrumentId,
	};
}

/**
 * Update transform for the "dbo.Instrument" table.
 * Maps app cased properties to database fields.
 */
export function transformInstrumentUpdateBaseRecord(data: InstrumentUpdateBaseRecord): {
	Code: InstrumentUpdateBaseRecord["code"]
	Description: InstrumentUpdateBaseRecord["description"]
	InstrumentType?: InstrumentUpdateBaseRecord["instrumentType"]
	Priority: InstrumentUpdateBaseRecord["priority"]
	SortOrder?: InstrumentUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: InstrumentUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: InstrumentUpdateBaseRecord["activeInd"]
	CreatedOnDt?: InstrumentUpdateBaseRecord["createdOnDt"]
	CreatedBy?: InstrumentUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: InstrumentUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: InstrumentUpdateBaseRecord["modifiedBy"]
	rv: InstrumentUpdateBaseRecord["rv"]
	InstrumentId?: InstrumentUpdateBaseRecord["instrumentId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		InstrumentType: data.instrumentType,
		Priority: data.priority,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		InstrumentId: data.instrumentId,
	};
}

/**
 * Insert schema for the "dbo.Instrument" table (after casing transform).
 */
export const InstrumentTableInsertSchema = InstrumentTableInsertBaseSchema.transform(transformInstrumentInsertBaseRecord);

/**
 * Update schema for the "dbo.Instrument" table (after casing transform).
 */
export const InstrumentTableUpdateSchema = InstrumentTableInsertBaseSchema.partial().transform(transformInstrumentUpdateBaseRecord);

type TableInsertRecord = z.input<typeof InstrumentTableInsertSchema>;
type TableReadRecord = z.output<typeof InstrumentTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.Instrument" table.
 */
export interface InstrumentRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	instrumentType: TableReadRecord["instrumentType"]
	priority: TableReadRecord["priority"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	instrumentId: TableReadRecord["instrumentId"]
}

/**
 * Insert record (casing transformed) for the "dbo.Instrument" table.
 */
export interface InstrumentInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @maxLen: 50
	 * @default: (N'NR')
	 */
	instrumentType?: TableInsertRecord["instrumentType"]
	priority: TableInsertRecord["priority"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	instrumentId?: TableInsertRecord["instrumentId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.Instrument" table.
 */
export type InstrumentUpdateRecord = Partial<InstrumentInsertRecord>;
