// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.GeotStrengthTestType" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const GeotStrengthTestTypeTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	GeotStrengthTestTypeId: z.any(),
});

/**
 * The base record type for the "dbo.GeotStrengthTestType" table.
 * This type represents the raw database record without case transforms.
 */
export type GeotStrengthTestTypeBaseRecord = z.output<typeof GeotStrengthTestTypeTableBaseSchema>;

/**
 * Read transform for the "dbo.GeotStrengthTestType" table.
 * Maps database fields to app case properties.
 */
export function transformGeotStrengthTestTypeBaseRecord(data: GeotStrengthTestTypeBaseRecord): {
	code: GeotStrengthTestTypeBaseRecord["Code"]
	description: GeotStrengthTestTypeBaseRecord["Description"]
	sortOrder: GeotStrengthTestTypeBaseRecord["SortOrder"]
	isDefaultInd: GeotStrengthTestTypeBaseRecord["IsDefaultInd"]
	activeInd: GeotStrengthTestTypeBaseRecord["ActiveInd"]
	createdOnDt: GeotStrengthTestTypeBaseRecord["CreatedOnDt"]
	createdBy: GeotStrengthTestTypeBaseRecord["CreatedBy"]
	modifiedOnDt?: GeotStrengthTestTypeBaseRecord["ModifiedOnDt"]
	modifiedBy?: GeotStrengthTestTypeBaseRecord["ModifiedBy"]
	rv: GeotStrengthTestTypeBaseRecord["rv"]
	geotStrengthTestTypeId: GeotStrengthTestTypeBaseRecord["GeotStrengthTestTypeId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		geotStrengthTestTypeId: data.GeotStrengthTestTypeId,
	};
}

/**
 * Read schema for the "dbo.GeotStrengthTestType" table (after casing transform).
 */
export const GeotStrengthTestTypeTableSchema = GeotStrengthTestTypeTableBaseSchema.transform(transformGeotStrengthTestTypeBaseRecord);

/**
 * Base insert/write schema for the "dbo.GeotStrengthTestType" table (no casing transforms).
 */
export const GeotStrengthTestTypeTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	geotStrengthTestTypeId: z.any().optional(),
});

/**
 * The base record type for the "dbo.GeotStrengthTestType" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type GeotStrengthTestTypeInsertBaseRecord = z.output<typeof GeotStrengthTestTypeTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.GeotStrengthTestType" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type GeotStrengthTestTypeUpdateBaseRecord = Partial<GeotStrengthTestTypeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.GeotStrengthTestType" table.
 * Maps app cased properties to database fields.
 */
export function transformGeotStrengthTestTypeInsertBaseRecord(data: GeotStrengthTestTypeInsertBaseRecord): {
	Code: GeotStrengthTestTypeInsertBaseRecord["code"]
	Description: GeotStrengthTestTypeInsertBaseRecord["description"]
	SortOrder?: GeotStrengthTestTypeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: GeotStrengthTestTypeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: GeotStrengthTestTypeInsertBaseRecord["activeInd"]
	CreatedOnDt?: GeotStrengthTestTypeInsertBaseRecord["createdOnDt"]
	CreatedBy?: GeotStrengthTestTypeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: GeotStrengthTestTypeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: GeotStrengthTestTypeInsertBaseRecord["modifiedBy"]
	rv: GeotStrengthTestTypeInsertBaseRecord["rv"]
	GeotStrengthTestTypeId?: GeotStrengthTestTypeInsertBaseRecord["geotStrengthTestTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		GeotStrengthTestTypeId: data.geotStrengthTestTypeId,
	};
}

/**
 * Update transform for the "dbo.GeotStrengthTestType" table.
 * Maps app cased properties to database fields.
 */
export function transformGeotStrengthTestTypeUpdateBaseRecord(data: GeotStrengthTestTypeUpdateBaseRecord): {
	Code: GeotStrengthTestTypeUpdateBaseRecord["code"]
	Description: GeotStrengthTestTypeUpdateBaseRecord["description"]
	SortOrder?: GeotStrengthTestTypeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: GeotStrengthTestTypeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: GeotStrengthTestTypeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: GeotStrengthTestTypeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: GeotStrengthTestTypeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: GeotStrengthTestTypeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: GeotStrengthTestTypeUpdateBaseRecord["modifiedBy"]
	rv: GeotStrengthTestTypeUpdateBaseRecord["rv"]
	GeotStrengthTestTypeId?: GeotStrengthTestTypeUpdateBaseRecord["geotStrengthTestTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		GeotStrengthTestTypeId: data.geotStrengthTestTypeId,
	};
}

/**
 * Insert schema for the "dbo.GeotStrengthTestType" table (after casing transform).
 */
export const GeotStrengthTestTypeTableInsertSchema = GeotStrengthTestTypeTableInsertBaseSchema.transform(transformGeotStrengthTestTypeInsertBaseRecord);

/**
 * Update schema for the "dbo.GeotStrengthTestType" table (after casing transform).
 */
export const GeotStrengthTestTypeTableUpdateSchema = GeotStrengthTestTypeTableInsertBaseSchema.partial().transform(transformGeotStrengthTestTypeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof GeotStrengthTestTypeTableInsertSchema>;
type TableReadRecord = z.output<typeof GeotStrengthTestTypeTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.GeotStrengthTestType" table.
 */
export interface GeotStrengthTestTypeRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	geotStrengthTestTypeId: TableReadRecord["geotStrengthTestTypeId"]
}

/**
 * Insert record (casing transformed) for the "dbo.GeotStrengthTestType" table.
 */
export interface GeotStrengthTestTypeInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	geotStrengthTestTypeId?: TableInsertRecord["geotStrengthTestTypeId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.GeotStrengthTestType" table.
 */
export type GeotStrengthTestTypeUpdateRecord = Partial<GeotStrengthTestTypeInsertRecord>;
