// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.XRFBagType" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const XRFBagTypeTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	XRFBagTypeId: z.any(),
});

/**
 * The base record type for the "dbo.XRFBagType" table.
 * This type represents the raw database record without case transforms.
 */
export type XrfbagTypeBaseRecord = z.output<typeof XRFBagTypeTableBaseSchema>;

/**
 * Read transform for the "dbo.XRFBagType" table.
 * Maps database fields to app case properties.
 */
export function transformXrfbagTypeBaseRecord(data: XrfbagTypeBaseRecord): {
	code: XrfbagTypeBaseRecord["Code"]
	description: XrfbagTypeBaseRecord["Description"]
	sortOrder: XrfbagTypeBaseRecord["SortOrder"]
	isDefaultInd: XrfbagTypeBaseRecord["IsDefaultInd"]
	activeInd: XrfbagTypeBaseRecord["ActiveInd"]
	createdOnDt: XrfbagTypeBaseRecord["CreatedOnDt"]
	createdBy: XrfbagTypeBaseRecord["CreatedBy"]
	modifiedOnDt?: XrfbagTypeBaseRecord["ModifiedOnDt"]
	modifiedBy?: XrfbagTypeBaseRecord["ModifiedBy"]
	rv: XrfbagTypeBaseRecord["rv"]
	xRFBagTypeId: XrfbagTypeBaseRecord["XRFBagTypeId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		xRFBagTypeId: data.XRFBagTypeId,
	};
}

/**
 * Read schema for the "dbo.XRFBagType" table (after casing transform).
 */
export const XRFBagTypeTableSchema = XRFBagTypeTableBaseSchema.transform(transformXrfbagTypeBaseRecord);

/**
 * Base insert/write schema for the "dbo.XRFBagType" table (no casing transforms).
 */
export const XRFBagTypeTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	xRFBagTypeId: z.any().optional(),
});

/**
 * The base record type for the "dbo.XRFBagType" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type XrfbagTypeInsertBaseRecord = z.output<typeof XRFBagTypeTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.XRFBagType" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type XrfbagTypeUpdateBaseRecord = Partial<XrfbagTypeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.XRFBagType" table.
 * Maps app cased properties to database fields.
 */
export function transformXrfbagTypeInsertBaseRecord(data: XrfbagTypeInsertBaseRecord): {
	Code: XrfbagTypeInsertBaseRecord["code"]
	Description: XrfbagTypeInsertBaseRecord["description"]
	SortOrder?: XrfbagTypeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: XrfbagTypeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: XrfbagTypeInsertBaseRecord["activeInd"]
	CreatedOnDt?: XrfbagTypeInsertBaseRecord["createdOnDt"]
	CreatedBy?: XrfbagTypeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: XrfbagTypeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: XrfbagTypeInsertBaseRecord["modifiedBy"]
	rv: XrfbagTypeInsertBaseRecord["rv"]
	XRFBagTypeId?: XrfbagTypeInsertBaseRecord["xRFBagTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		XRFBagTypeId: data.xRFBagTypeId,
	};
}

/**
 * Update transform for the "dbo.XRFBagType" table.
 * Maps app cased properties to database fields.
 */
export function transformXrfbagTypeUpdateBaseRecord(data: XrfbagTypeUpdateBaseRecord): {
	Code: XrfbagTypeUpdateBaseRecord["code"]
	Description: XrfbagTypeUpdateBaseRecord["description"]
	SortOrder?: XrfbagTypeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: XrfbagTypeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: XrfbagTypeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: XrfbagTypeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: XrfbagTypeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: XrfbagTypeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: XrfbagTypeUpdateBaseRecord["modifiedBy"]
	rv: XrfbagTypeUpdateBaseRecord["rv"]
	XRFBagTypeId?: XrfbagTypeUpdateBaseRecord["xRFBagTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		XRFBagTypeId: data.xRFBagTypeId,
	};
}

/**
 * Insert schema for the "dbo.XRFBagType" table (after casing transform).
 */
export const XRFBagTypeTableInsertSchema = XRFBagTypeTableInsertBaseSchema.transform(transformXrfbagTypeInsertBaseRecord);

/**
 * Update schema for the "dbo.XRFBagType" table (after casing transform).
 */
export const XRFBagTypeTableUpdateSchema = XRFBagTypeTableInsertBaseSchema.partial().transform(transformXrfbagTypeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof XRFBagTypeTableInsertSchema>;
type TableReadRecord = z.output<typeof XRFBagTypeTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.XRFBagType" table.
 */
export interface XrfbagTypeRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	xRFBagTypeId: TableReadRecord["xRFBagTypeId"]
}

/**
 * Insert record (casing transformed) for the "dbo.XRFBagType" table.
 */
export interface XrfbagTypeInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	xRFBagTypeId?: TableInsertRecord["xRFBagTypeId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.XRFBagType" table.
 */
export type XrfbagTypeUpdateRecord = Partial<XrfbagTypeInsertRecord>;
