// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.Config" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const ConfigTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	ConfigId: z.any(),
	/**
	 * dataType: int
	 */
	MineId: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ConfigTypeCd: z.string(),
	/**
	 * dataType: nvarchar
	 */
	ConfigTypeValue: z.string(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.Config" table.
 * This type represents the raw database record without case transforms.
 */
export type ConfigBaseRecord = z.output<typeof ConfigTableBaseSchema>;

/**
 * Read transform for the "dbo.Config" table.
 * Maps database fields to app case properties.
 */
export function transformConfigBaseRecord(data: ConfigBaseRecord): {
	configId: ConfigBaseRecord["ConfigId"]
	mineId?: ConfigBaseRecord["MineId"]
	configTypeCd: ConfigBaseRecord["ConfigTypeCd"]
	configTypeValue: ConfigBaseRecord["ConfigTypeValue"]
	activeInd: ConfigBaseRecord["ActiveInd"]
	createdOnDt: ConfigBaseRecord["CreatedOnDt"]
	createdBy: ConfigBaseRecord["CreatedBy"]
	modifiedOnDt?: ConfigBaseRecord["ModifiedOnDt"]
	modifiedBy?: ConfigBaseRecord["ModifiedBy"]
	rv: ConfigBaseRecord["rv"]
} {
	return {
		configId: data.ConfigId,
		mineId: data.MineId,
		configTypeCd: data.ConfigTypeCd,
		configTypeValue: data.ConfigTypeValue,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.Config" table (after casing transform).
 */
export const ConfigTableSchema = ConfigTableBaseSchema.transform(transformConfigBaseRecord);

/**
 * Base insert/write schema for the "dbo.Config" table (no casing transforms).
 */
export const ConfigTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	configId: z.any().optional(),
	/**
	 * dataType: int
	 */
	mineId: z.number().int().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	configTypeCd: z.string().max(15),
	/**
	 * dataType: nvarchar
	 */
	configTypeValue: z.string().max(100),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](100),coalesce(session_context(N'UserNm'),suser_sname())))
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.Config" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type ConfigInsertBaseRecord = z.output<typeof ConfigTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.Config" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type ConfigUpdateBaseRecord = Partial<ConfigInsertBaseRecord>;

/**
 * Insert transform for the "dbo.Config" table.
 * Maps app cased properties to database fields.
 */
export function transformConfigInsertBaseRecord(data: ConfigInsertBaseRecord): {
	ConfigId?: ConfigInsertBaseRecord["configId"]
	MineId?: ConfigInsertBaseRecord["mineId"]
	ConfigTypeCd: ConfigInsertBaseRecord["configTypeCd"]
	ConfigTypeValue: ConfigInsertBaseRecord["configTypeValue"]
	ActiveInd?: ConfigInsertBaseRecord["activeInd"]
	CreatedOnDt?: ConfigInsertBaseRecord["createdOnDt"]
	CreatedBy?: ConfigInsertBaseRecord["createdBy"]
	ModifiedOnDt?: ConfigInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: ConfigInsertBaseRecord["modifiedBy"]
	rv: ConfigInsertBaseRecord["rv"]
} {
	return {
		ConfigId: data.configId,
		MineId: data.mineId,
		ConfigTypeCd: data.configTypeCd,
		ConfigTypeValue: data.configTypeValue,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.Config" table.
 * Maps app cased properties to database fields.
 */
export function transformConfigUpdateBaseRecord(data: ConfigUpdateBaseRecord): {
	ConfigId?: ConfigUpdateBaseRecord["configId"]
	MineId?: ConfigUpdateBaseRecord["mineId"]
	ConfigTypeCd: ConfigUpdateBaseRecord["configTypeCd"]
	ConfigTypeValue: ConfigUpdateBaseRecord["configTypeValue"]
	ActiveInd?: ConfigUpdateBaseRecord["activeInd"]
	CreatedOnDt?: ConfigUpdateBaseRecord["createdOnDt"]
	CreatedBy?: ConfigUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: ConfigUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: ConfigUpdateBaseRecord["modifiedBy"]
	rv: ConfigUpdateBaseRecord["rv"]
} {
	return {
		ConfigId: data.configId,
		MineId: data.mineId,
		ConfigTypeCd: data.configTypeCd,
		ConfigTypeValue: data.configTypeValue,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.Config" table (after casing transform).
 */
export const ConfigTableInsertSchema = ConfigTableInsertBaseSchema.transform(transformConfigInsertBaseRecord);

/**
 * Update schema for the "dbo.Config" table (after casing transform).
 */
export const ConfigTableUpdateSchema = ConfigTableInsertBaseSchema.partial().transform(transformConfigUpdateBaseRecord);

type TableInsertRecord = z.input<typeof ConfigTableInsertSchema>;
type TableReadRecord = z.output<typeof ConfigTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.Config" table.
 */
export interface ConfigRecord {
	configId: TableReadRecord["configId"]
	mineId?: TableReadRecord["mineId"]
	configTypeCd: TableReadRecord["configTypeCd"]
	configTypeValue: TableReadRecord["configTypeValue"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.Config" table.
 */
export interface ConfigInsertRecord {
	/**
	 * @default: (newid())
	 */
	configId?: TableInsertRecord["configId"]
	mineId?: TableInsertRecord["mineId"]
	/**
	 * @maxLen: 15
	 */
	configTypeCd: TableInsertRecord["configTypeCd"]
	/**
	 * @maxLen: 100
	 */
	configTypeValue: TableInsertRecord["configTypeValue"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](100),coalesce(session_context(N'UserNm'),suser_sname())))
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.Config" table.
 */
export type ConfigUpdateRecord = Partial<ConfigInsertRecord>;
