// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.SurveyMethod" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const SurveyMethodTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: int
	 */
	Priority: z.number(),
	/**
	 * dataType: int
	 */
	RLPriority: z.number().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	Type: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	SurveyMethodId: z.any(),
});

/**
 * The base record type for the "dbo.SurveyMethod" table.
 * This type represents the raw database record without case transforms.
 */
export type SurveyMethodBaseRecord = z.output<typeof SurveyMethodTableBaseSchema>;

/**
 * Read transform for the "dbo.SurveyMethod" table.
 * Maps database fields to app case properties.
 */
export function transformSurveyMethodBaseRecord(data: SurveyMethodBaseRecord): {
	code: SurveyMethodBaseRecord["Code"]
	description: SurveyMethodBaseRecord["Description"]
	priority: SurveyMethodBaseRecord["Priority"]
	rLPriority?: SurveyMethodBaseRecord["RLPriority"]
	type?: SurveyMethodBaseRecord["Type"]
	sortOrder: SurveyMethodBaseRecord["SortOrder"]
	isDefaultInd: SurveyMethodBaseRecord["IsDefaultInd"]
	activeInd: SurveyMethodBaseRecord["ActiveInd"]
	createdOnDt: SurveyMethodBaseRecord["CreatedOnDt"]
	createdBy: SurveyMethodBaseRecord["CreatedBy"]
	modifiedOnDt?: SurveyMethodBaseRecord["ModifiedOnDt"]
	modifiedBy?: SurveyMethodBaseRecord["ModifiedBy"]
	rv: SurveyMethodBaseRecord["rv"]
	surveyMethodId: SurveyMethodBaseRecord["SurveyMethodId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		priority: data.Priority,
		rLPriority: data.RLPriority,
		type: data.Type,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		surveyMethodId: data.SurveyMethodId,
	};
}

/**
 * Read schema for the "dbo.SurveyMethod" table (after casing transform).
 */
export const SurveyMethodTableSchema = SurveyMethodTableBaseSchema.transform(transformSurveyMethodBaseRecord);

/**
 * Base insert/write schema for the "dbo.SurveyMethod" table (no casing transforms).
 */
export const SurveyMethodTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: int
	 * defaultValue: ((0))
	 */
	priority: z.number().int().optional(),
	/**
	 * dataType: int
	 */
	rLPriority: z.number().int().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	type: z.string().max(50).nullable().optional(),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	surveyMethodId: z.any().optional(),
});

/**
 * The base record type for the "dbo.SurveyMethod" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type SurveyMethodInsertBaseRecord = z.output<typeof SurveyMethodTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.SurveyMethod" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type SurveyMethodUpdateBaseRecord = Partial<SurveyMethodInsertBaseRecord>;

/**
 * Insert transform for the "dbo.SurveyMethod" table.
 * Maps app cased properties to database fields.
 */
export function transformSurveyMethodInsertBaseRecord(data: SurveyMethodInsertBaseRecord): {
	Code: SurveyMethodInsertBaseRecord["code"]
	Description: SurveyMethodInsertBaseRecord["description"]
	Priority?: SurveyMethodInsertBaseRecord["priority"]
	RLPriority?: SurveyMethodInsertBaseRecord["rLPriority"]
	Type?: SurveyMethodInsertBaseRecord["type"]
	SortOrder?: SurveyMethodInsertBaseRecord["sortOrder"]
	IsDefaultInd?: SurveyMethodInsertBaseRecord["isDefaultInd"]
	ActiveInd?: SurveyMethodInsertBaseRecord["activeInd"]
	CreatedOnDt?: SurveyMethodInsertBaseRecord["createdOnDt"]
	CreatedBy?: SurveyMethodInsertBaseRecord["createdBy"]
	ModifiedOnDt?: SurveyMethodInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: SurveyMethodInsertBaseRecord["modifiedBy"]
	rv: SurveyMethodInsertBaseRecord["rv"]
	SurveyMethodId?: SurveyMethodInsertBaseRecord["surveyMethodId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		Priority: data.priority,
		RLPriority: data.rLPriority,
		Type: data.type,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		SurveyMethodId: data.surveyMethodId,
	};
}

/**
 * Update transform for the "dbo.SurveyMethod" table.
 * Maps app cased properties to database fields.
 */
export function transformSurveyMethodUpdateBaseRecord(data: SurveyMethodUpdateBaseRecord): {
	Code: SurveyMethodUpdateBaseRecord["code"]
	Description: SurveyMethodUpdateBaseRecord["description"]
	Priority?: SurveyMethodUpdateBaseRecord["priority"]
	RLPriority?: SurveyMethodUpdateBaseRecord["rLPriority"]
	Type?: SurveyMethodUpdateBaseRecord["type"]
	SortOrder?: SurveyMethodUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: SurveyMethodUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: SurveyMethodUpdateBaseRecord["activeInd"]
	CreatedOnDt?: SurveyMethodUpdateBaseRecord["createdOnDt"]
	CreatedBy?: SurveyMethodUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: SurveyMethodUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: SurveyMethodUpdateBaseRecord["modifiedBy"]
	rv: SurveyMethodUpdateBaseRecord["rv"]
	SurveyMethodId?: SurveyMethodUpdateBaseRecord["surveyMethodId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		Priority: data.priority,
		RLPriority: data.rLPriority,
		Type: data.type,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		SurveyMethodId: data.surveyMethodId,
	};
}

/**
 * Insert schema for the "dbo.SurveyMethod" table (after casing transform).
 */
export const SurveyMethodTableInsertSchema = SurveyMethodTableInsertBaseSchema.transform(transformSurveyMethodInsertBaseRecord);

/**
 * Update schema for the "dbo.SurveyMethod" table (after casing transform).
 */
export const SurveyMethodTableUpdateSchema = SurveyMethodTableInsertBaseSchema.partial().transform(transformSurveyMethodUpdateBaseRecord);

type TableInsertRecord = z.input<typeof SurveyMethodTableInsertSchema>;
type TableReadRecord = z.output<typeof SurveyMethodTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.SurveyMethod" table.
 */
export interface SurveyMethodRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	priority: TableReadRecord["priority"]
	rLPriority?: TableReadRecord["rLPriority"]
	type?: TableReadRecord["type"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	surveyMethodId: TableReadRecord["surveyMethodId"]
}

/**
 * Insert record (casing transformed) for the "dbo.SurveyMethod" table.
 */
export interface SurveyMethodInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	priority?: TableInsertRecord["priority"]
	rLPriority?: TableInsertRecord["rLPriority"]
	/**
	 * @maxLen: 50
	 */
	type?: TableInsertRecord["type"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	surveyMethodId?: TableInsertRecord["surveyMethodId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.SurveyMethod" table.
 */
export type SurveyMethodUpdateRecord = Partial<SurveyMethodInsertRecord>;
