// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.GroutType" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const GroutTypeTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	GroutTypeId: z.any(),
});

/**
 * The base record type for the "dbo.GroutType" table.
 * This type represents the raw database record without case transforms.
 */
export type GroutTypeBaseRecord = z.output<typeof GroutTypeTableBaseSchema>;

/**
 * Read transform for the "dbo.GroutType" table.
 * Maps database fields to app case properties.
 */
export function transformGroutTypeBaseRecord(data: GroutTypeBaseRecord): {
	code: GroutTypeBaseRecord["Code"]
	description: GroutTypeBaseRecord["Description"]
	sortOrder: GroutTypeBaseRecord["SortOrder"]
	isDefaultInd: GroutTypeBaseRecord["IsDefaultInd"]
	activeInd: GroutTypeBaseRecord["ActiveInd"]
	createdOnDt: GroutTypeBaseRecord["CreatedOnDt"]
	createdBy: GroutTypeBaseRecord["CreatedBy"]
	modifiedOnDt?: GroutTypeBaseRecord["ModifiedOnDt"]
	modifiedBy?: GroutTypeBaseRecord["ModifiedBy"]
	rv: GroutTypeBaseRecord["rv"]
	groutTypeId: GroutTypeBaseRecord["GroutTypeId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		groutTypeId: data.GroutTypeId,
	};
}

/**
 * Read schema for the "dbo.GroutType" table (after casing transform).
 */
export const GroutTypeTableSchema = GroutTypeTableBaseSchema.transform(transformGroutTypeBaseRecord);

/**
 * Base insert/write schema for the "dbo.GroutType" table (no casing transforms).
 */
export const GroutTypeTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	groutTypeId: z.any().optional(),
});

/**
 * The base record type for the "dbo.GroutType" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type GroutTypeInsertBaseRecord = z.output<typeof GroutTypeTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.GroutType" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type GroutTypeUpdateBaseRecord = Partial<GroutTypeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.GroutType" table.
 * Maps app cased properties to database fields.
 */
export function transformGroutTypeInsertBaseRecord(data: GroutTypeInsertBaseRecord): {
	Code: GroutTypeInsertBaseRecord["code"]
	Description: GroutTypeInsertBaseRecord["description"]
	SortOrder?: GroutTypeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: GroutTypeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: GroutTypeInsertBaseRecord["activeInd"]
	CreatedOnDt?: GroutTypeInsertBaseRecord["createdOnDt"]
	CreatedBy?: GroutTypeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: GroutTypeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: GroutTypeInsertBaseRecord["modifiedBy"]
	rv: GroutTypeInsertBaseRecord["rv"]
	GroutTypeId?: GroutTypeInsertBaseRecord["groutTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		GroutTypeId: data.groutTypeId,
	};
}

/**
 * Update transform for the "dbo.GroutType" table.
 * Maps app cased properties to database fields.
 */
export function transformGroutTypeUpdateBaseRecord(data: GroutTypeUpdateBaseRecord): {
	Code: GroutTypeUpdateBaseRecord["code"]
	Description: GroutTypeUpdateBaseRecord["description"]
	SortOrder?: GroutTypeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: GroutTypeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: GroutTypeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: GroutTypeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: GroutTypeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: GroutTypeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: GroutTypeUpdateBaseRecord["modifiedBy"]
	rv: GroutTypeUpdateBaseRecord["rv"]
	GroutTypeId?: GroutTypeUpdateBaseRecord["groutTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		GroutTypeId: data.groutTypeId,
	};
}

/**
 * Insert schema for the "dbo.GroutType" table (after casing transform).
 */
export const GroutTypeTableInsertSchema = GroutTypeTableInsertBaseSchema.transform(transformGroutTypeInsertBaseRecord);

/**
 * Update schema for the "dbo.GroutType" table (after casing transform).
 */
export const GroutTypeTableUpdateSchema = GroutTypeTableInsertBaseSchema.partial().transform(transformGroutTypeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof GroutTypeTableInsertSchema>;
type TableReadRecord = z.output<typeof GroutTypeTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.GroutType" table.
 */
export interface GroutTypeRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	groutTypeId: TableReadRecord["groutTypeId"]
}

/**
 * Insert record (casing transformed) for the "dbo.GroutType" table.
 */
export interface GroutTypeInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	groutTypeId?: TableInsertRecord["groutTypeId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.GroutType" table.
 */
export type GroutTypeUpdateRecord = Partial<GroutTypeInsertRecord>;
