// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.Company" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const CompanyTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	CompanyId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: nvarchar
	 */
	CompanyType: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.Company" table.
 * This type represents the raw database record without case transforms.
 */
export type CompanyBaseRecord = z.output<typeof CompanyTableBaseSchema>;

/**
 * Read transform for the "dbo.Company" table.
 * Maps database fields to app case properties.
 */
export function transformCompanyBaseRecord(data: CompanyBaseRecord): {
	companyId: CompanyBaseRecord["CompanyId"]
	code: CompanyBaseRecord["Code"]
	description: CompanyBaseRecord["Description"]
	companyType: CompanyBaseRecord["CompanyType"]
	sortOrder: CompanyBaseRecord["SortOrder"]
	isDefaultInd: CompanyBaseRecord["IsDefaultInd"]
	activeInd: CompanyBaseRecord["ActiveInd"]
	createdOnDt: CompanyBaseRecord["CreatedOnDt"]
	createdBy: CompanyBaseRecord["CreatedBy"]
	modifiedOnDt?: CompanyBaseRecord["ModifiedOnDt"]
	modifiedBy?: CompanyBaseRecord["ModifiedBy"]
	rv: CompanyBaseRecord["rv"]
} {
	return {
		companyId: data.CompanyId,
		code: data.Code,
		description: data.Description,
		companyType: data.CompanyType,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.Company" table (after casing transform).
 */
export const CompanyTableSchema = CompanyTableBaseSchema.transform(transformCompanyBaseRecord);

/**
 * Base insert/write schema for the "dbo.Company" table (no casing transforms).
 */
export const CompanyTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	companyId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: nvarchar
	 * defaultValue: (N'NR')
	 */
	companyType: z.string().max(50).optional(),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.Company" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type CompanyInsertBaseRecord = z.output<typeof CompanyTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.Company" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type CompanyUpdateBaseRecord = Partial<CompanyInsertBaseRecord>;

/**
 * Insert transform for the "dbo.Company" table.
 * Maps app cased properties to database fields.
 */
export function transformCompanyInsertBaseRecord(data: CompanyInsertBaseRecord): {
	CompanyId?: CompanyInsertBaseRecord["companyId"]
	Code: CompanyInsertBaseRecord["code"]
	Description: CompanyInsertBaseRecord["description"]
	CompanyType?: CompanyInsertBaseRecord["companyType"]
	SortOrder?: CompanyInsertBaseRecord["sortOrder"]
	IsDefaultInd?: CompanyInsertBaseRecord["isDefaultInd"]
	ActiveInd?: CompanyInsertBaseRecord["activeInd"]
	CreatedOnDt?: CompanyInsertBaseRecord["createdOnDt"]
	CreatedBy?: CompanyInsertBaseRecord["createdBy"]
	ModifiedOnDt?: CompanyInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: CompanyInsertBaseRecord["modifiedBy"]
	rv: CompanyInsertBaseRecord["rv"]
} {
	return {
		CompanyId: data.companyId,
		Code: data.code,
		Description: data.description,
		CompanyType: data.companyType,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.Company" table.
 * Maps app cased properties to database fields.
 */
export function transformCompanyUpdateBaseRecord(data: CompanyUpdateBaseRecord): {
	CompanyId?: CompanyUpdateBaseRecord["companyId"]
	Code: CompanyUpdateBaseRecord["code"]
	Description: CompanyUpdateBaseRecord["description"]
	CompanyType?: CompanyUpdateBaseRecord["companyType"]
	SortOrder?: CompanyUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: CompanyUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: CompanyUpdateBaseRecord["activeInd"]
	CreatedOnDt?: CompanyUpdateBaseRecord["createdOnDt"]
	CreatedBy?: CompanyUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: CompanyUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: CompanyUpdateBaseRecord["modifiedBy"]
	rv: CompanyUpdateBaseRecord["rv"]
} {
	return {
		CompanyId: data.companyId,
		Code: data.code,
		Description: data.description,
		CompanyType: data.companyType,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.Company" table (after casing transform).
 */
export const CompanyTableInsertSchema = CompanyTableInsertBaseSchema.transform(transformCompanyInsertBaseRecord);

/**
 * Update schema for the "dbo.Company" table (after casing transform).
 */
export const CompanyTableUpdateSchema = CompanyTableInsertBaseSchema.partial().transform(transformCompanyUpdateBaseRecord);

type TableInsertRecord = z.input<typeof CompanyTableInsertSchema>;
type TableReadRecord = z.output<typeof CompanyTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.Company" table.
 */
export interface CompanyRecord {
	companyId: TableReadRecord["companyId"]
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	companyType: TableReadRecord["companyType"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.Company" table.
 */
export interface CompanyInsertRecord {
	/**
	 * @default: (newid())
	 */
	companyId?: TableInsertRecord["companyId"]
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @maxLen: 50
	 * @default: (N'NR')
	 */
	companyType?: TableInsertRecord["companyType"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.Company" table.
 */
export type CompanyUpdateRecord = Partial<CompanyInsertRecord>;
