// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.MachineryStatusClassification" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const MachineryStatusClassificationTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	MachineryStatusClassificationId: z.any(),
});

/**
 * The base record type for the "dbo.MachineryStatusClassification" table.
 * This type represents the raw database record without case transforms.
 */
export type MachineryStatusClassificationBaseRecord = z.output<typeof MachineryStatusClassificationTableBaseSchema>;

/**
 * Read transform for the "dbo.MachineryStatusClassification" table.
 * Maps database fields to app case properties.
 */
export function transformMachineryStatusClassificationBaseRecord(data: MachineryStatusClassificationBaseRecord): {
	code: MachineryStatusClassificationBaseRecord["Code"]
	description: MachineryStatusClassificationBaseRecord["Description"]
	sortOrder: MachineryStatusClassificationBaseRecord["SortOrder"]
	isDefaultInd: MachineryStatusClassificationBaseRecord["IsDefaultInd"]
	activeInd: MachineryStatusClassificationBaseRecord["ActiveInd"]
	createdOnDt: MachineryStatusClassificationBaseRecord["CreatedOnDt"]
	createdBy: MachineryStatusClassificationBaseRecord["CreatedBy"]
	modifiedOnDt?: MachineryStatusClassificationBaseRecord["ModifiedOnDt"]
	modifiedBy?: MachineryStatusClassificationBaseRecord["ModifiedBy"]
	rv: MachineryStatusClassificationBaseRecord["rv"]
	machineryStatusClassificationId: MachineryStatusClassificationBaseRecord["MachineryStatusClassificationId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		machineryStatusClassificationId: data.MachineryStatusClassificationId,
	};
}

/**
 * Read schema for the "dbo.MachineryStatusClassification" table (after casing transform).
 */
export const MachineryStatusClassificationTableSchema = MachineryStatusClassificationTableBaseSchema.transform(transformMachineryStatusClassificationBaseRecord);

/**
 * Base insert/write schema for the "dbo.MachineryStatusClassification" table (no casing transforms).
 */
export const MachineryStatusClassificationTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	machineryStatusClassificationId: z.any().optional(),
});

/**
 * The base record type for the "dbo.MachineryStatusClassification" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type MachineryStatusClassificationInsertBaseRecord = z.output<typeof MachineryStatusClassificationTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.MachineryStatusClassification" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type MachineryStatusClassificationUpdateBaseRecord = Partial<MachineryStatusClassificationInsertBaseRecord>;

/**
 * Insert transform for the "dbo.MachineryStatusClassification" table.
 * Maps app cased properties to database fields.
 */
export function transformMachineryStatusClassificationInsertBaseRecord(data: MachineryStatusClassificationInsertBaseRecord): {
	Code: MachineryStatusClassificationInsertBaseRecord["code"]
	Description: MachineryStatusClassificationInsertBaseRecord["description"]
	SortOrder?: MachineryStatusClassificationInsertBaseRecord["sortOrder"]
	IsDefaultInd?: MachineryStatusClassificationInsertBaseRecord["isDefaultInd"]
	ActiveInd?: MachineryStatusClassificationInsertBaseRecord["activeInd"]
	CreatedOnDt?: MachineryStatusClassificationInsertBaseRecord["createdOnDt"]
	CreatedBy?: MachineryStatusClassificationInsertBaseRecord["createdBy"]
	ModifiedOnDt?: MachineryStatusClassificationInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: MachineryStatusClassificationInsertBaseRecord["modifiedBy"]
	rv: MachineryStatusClassificationInsertBaseRecord["rv"]
	MachineryStatusClassificationId?: MachineryStatusClassificationInsertBaseRecord["machineryStatusClassificationId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		MachineryStatusClassificationId: data.machineryStatusClassificationId,
	};
}

/**
 * Update transform for the "dbo.MachineryStatusClassification" table.
 * Maps app cased properties to database fields.
 */
export function transformMachineryStatusClassificationUpdateBaseRecord(data: MachineryStatusClassificationUpdateBaseRecord): {
	Code: MachineryStatusClassificationUpdateBaseRecord["code"]
	Description: MachineryStatusClassificationUpdateBaseRecord["description"]
	SortOrder?: MachineryStatusClassificationUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: MachineryStatusClassificationUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: MachineryStatusClassificationUpdateBaseRecord["activeInd"]
	CreatedOnDt?: MachineryStatusClassificationUpdateBaseRecord["createdOnDt"]
	CreatedBy?: MachineryStatusClassificationUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: MachineryStatusClassificationUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: MachineryStatusClassificationUpdateBaseRecord["modifiedBy"]
	rv: MachineryStatusClassificationUpdateBaseRecord["rv"]
	MachineryStatusClassificationId?: MachineryStatusClassificationUpdateBaseRecord["machineryStatusClassificationId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		MachineryStatusClassificationId: data.machineryStatusClassificationId,
	};
}

/**
 * Insert schema for the "dbo.MachineryStatusClassification" table (after casing transform).
 */
export const MachineryStatusClassificationTableInsertSchema = MachineryStatusClassificationTableInsertBaseSchema.transform(transformMachineryStatusClassificationInsertBaseRecord);

/**
 * Update schema for the "dbo.MachineryStatusClassification" table (after casing transform).
 */
export const MachineryStatusClassificationTableUpdateSchema = MachineryStatusClassificationTableInsertBaseSchema.partial().transform(transformMachineryStatusClassificationUpdateBaseRecord);

type TableInsertRecord = z.input<typeof MachineryStatusClassificationTableInsertSchema>;
type TableReadRecord = z.output<typeof MachineryStatusClassificationTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.MachineryStatusClassification" table.
 */
export interface MachineryStatusClassificationRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	machineryStatusClassificationId: TableReadRecord["machineryStatusClassificationId"]
}

/**
 * Insert record (casing transformed) for the "dbo.MachineryStatusClassification" table.
 */
export interface MachineryStatusClassificationInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	machineryStatusClassificationId?: TableInsertRecord["machineryStatusClassificationId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.MachineryStatusClassification" table.
 */
export type MachineryStatusClassificationUpdateRecord = Partial<MachineryStatusClassificationInsertRecord>;
