// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.GeotRockSupport" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const GeotRockSupportTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	GeotRockSupportId: z.any(),
});

/**
 * The base record type for the "dbo.GeotRockSupport" table.
 * This type represents the raw database record without case transforms.
 */
export type GeotRockSupportBaseRecord = z.output<typeof GeotRockSupportTableBaseSchema>;

/**
 * Read transform for the "dbo.GeotRockSupport" table.
 * Maps database fields to app case properties.
 */
export function transformGeotRockSupportBaseRecord(data: GeotRockSupportBaseRecord): {
	code: GeotRockSupportBaseRecord["Code"]
	description: GeotRockSupportBaseRecord["Description"]
	sortOrder: GeotRockSupportBaseRecord["SortOrder"]
	isDefaultInd: GeotRockSupportBaseRecord["IsDefaultInd"]
	activeInd: GeotRockSupportBaseRecord["ActiveInd"]
	createdOnDt: GeotRockSupportBaseRecord["CreatedOnDt"]
	createdBy: GeotRockSupportBaseRecord["CreatedBy"]
	modifiedOnDt?: GeotRockSupportBaseRecord["ModifiedOnDt"]
	modifiedBy?: GeotRockSupportBaseRecord["ModifiedBy"]
	rv: GeotRockSupportBaseRecord["rv"]
	geotRockSupportId: GeotRockSupportBaseRecord["GeotRockSupportId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		geotRockSupportId: data.GeotRockSupportId,
	};
}

/**
 * Read schema for the "dbo.GeotRockSupport" table (after casing transform).
 */
export const GeotRockSupportTableSchema = GeotRockSupportTableBaseSchema.transform(transformGeotRockSupportBaseRecord);

/**
 * Base insert/write schema for the "dbo.GeotRockSupport" table (no casing transforms).
 */
export const GeotRockSupportTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	geotRockSupportId: z.any().optional(),
});

/**
 * The base record type for the "dbo.GeotRockSupport" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type GeotRockSupportInsertBaseRecord = z.output<typeof GeotRockSupportTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.GeotRockSupport" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type GeotRockSupportUpdateBaseRecord = Partial<GeotRockSupportInsertBaseRecord>;

/**
 * Insert transform for the "dbo.GeotRockSupport" table.
 * Maps app cased properties to database fields.
 */
export function transformGeotRockSupportInsertBaseRecord(data: GeotRockSupportInsertBaseRecord): {
	Code: GeotRockSupportInsertBaseRecord["code"]
	Description: GeotRockSupportInsertBaseRecord["description"]
	SortOrder?: GeotRockSupportInsertBaseRecord["sortOrder"]
	IsDefaultInd?: GeotRockSupportInsertBaseRecord["isDefaultInd"]
	ActiveInd?: GeotRockSupportInsertBaseRecord["activeInd"]
	CreatedOnDt?: GeotRockSupportInsertBaseRecord["createdOnDt"]
	CreatedBy?: GeotRockSupportInsertBaseRecord["createdBy"]
	ModifiedOnDt?: GeotRockSupportInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: GeotRockSupportInsertBaseRecord["modifiedBy"]
	rv: GeotRockSupportInsertBaseRecord["rv"]
	GeotRockSupportId?: GeotRockSupportInsertBaseRecord["geotRockSupportId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		GeotRockSupportId: data.geotRockSupportId,
	};
}

/**
 * Update transform for the "dbo.GeotRockSupport" table.
 * Maps app cased properties to database fields.
 */
export function transformGeotRockSupportUpdateBaseRecord(data: GeotRockSupportUpdateBaseRecord): {
	Code: GeotRockSupportUpdateBaseRecord["code"]
	Description: GeotRockSupportUpdateBaseRecord["description"]
	SortOrder?: GeotRockSupportUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: GeotRockSupportUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: GeotRockSupportUpdateBaseRecord["activeInd"]
	CreatedOnDt?: GeotRockSupportUpdateBaseRecord["createdOnDt"]
	CreatedBy?: GeotRockSupportUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: GeotRockSupportUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: GeotRockSupportUpdateBaseRecord["modifiedBy"]
	rv: GeotRockSupportUpdateBaseRecord["rv"]
	GeotRockSupportId?: GeotRockSupportUpdateBaseRecord["geotRockSupportId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		GeotRockSupportId: data.geotRockSupportId,
	};
}

/**
 * Insert schema for the "dbo.GeotRockSupport" table (after casing transform).
 */
export const GeotRockSupportTableInsertSchema = GeotRockSupportTableInsertBaseSchema.transform(transformGeotRockSupportInsertBaseRecord);

/**
 * Update schema for the "dbo.GeotRockSupport" table (after casing transform).
 */
export const GeotRockSupportTableUpdateSchema = GeotRockSupportTableInsertBaseSchema.partial().transform(transformGeotRockSupportUpdateBaseRecord);

type TableInsertRecord = z.input<typeof GeotRockSupportTableInsertSchema>;
type TableReadRecord = z.output<typeof GeotRockSupportTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.GeotRockSupport" table.
 */
export interface GeotRockSupportRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	geotRockSupportId: TableReadRecord["geotRockSupportId"]
}

/**
 * Insert record (casing transformed) for the "dbo.GeotRockSupport" table.
 */
export interface GeotRockSupportInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	geotRockSupportId?: TableInsertRecord["geotRockSupportId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.GeotRockSupport" table.
 */
export type GeotRockSupportUpdateRecord = Partial<GeotRockSupportInsertRecord>;
