// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.SampleRegister" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const SampleRegisterTableBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 */
	SampleId: z.any(),
	/**
	 * dataType: nvarchar
	 */
	Organization: z.string(),
	/**
	 * dataType: nvarchar
	 */
	SampleNm: z.string(),
	/**
	 * dataType: nvarchar
	 */
	SourceTable: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	IsLab: z.any(),
	/**
	 * dataType: nvarchar
	 */
	ChkType: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	AttributeGroup: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	LastDispatchedDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	LastLabDispatchId: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	DispatchCount: z.number(),
	/**
	 * dataType: nvarchar
	 */
	JsonData: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	DataSource: z.string(),
	/**
	 * dataType: varchar
	 */
	MigrationPreviousNm: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ReportIncludeInd: z.any(),
	/**
	 * dataType: tinyint
	 */
	ValidationStatus: z.number(),
	/**
	 * dataType: nvarchar
	 */
	ValidationErrors: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: tinyint
	 */
	RowStatus: z.number(),
	/**
	 * dataType: uniqueidentifier
	 */
	SupersededById: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
});

/**
 * The base record type for the "dbo.SampleRegister" table.
 * This type represents the raw database record without case transforms.
 */
export type SampleRegisterBaseRecord = z.output<typeof SampleRegisterTableBaseSchema>;

/**
 * Read transform for the "dbo.SampleRegister" table.
 * Maps database fields to app case properties.
 */
export function transformSampleRegisterBaseRecord(data: SampleRegisterBaseRecord): {
	sampleId: SampleRegisterBaseRecord["SampleId"]
	organization: SampleRegisterBaseRecord["Organization"]
	sampleNm: SampleRegisterBaseRecord["SampleNm"]
	sourceTable?: SampleRegisterBaseRecord["SourceTable"]
	isLab: SampleRegisterBaseRecord["IsLab"]
	chkType?: SampleRegisterBaseRecord["ChkType"]
	attributeGroup?: SampleRegisterBaseRecord["AttributeGroup"]
	lastDispatchedDt?: SampleRegisterBaseRecord["LastDispatchedDt"]
	lastLabDispatchId?: SampleRegisterBaseRecord["LastLabDispatchId"]
	dispatchCount: SampleRegisterBaseRecord["DispatchCount"]
	jsonData?: SampleRegisterBaseRecord["JsonData"]
	dataSource: SampleRegisterBaseRecord["DataSource"]
	migrationPreviousNm?: SampleRegisterBaseRecord["MigrationPreviousNm"]
	reportIncludeInd: SampleRegisterBaseRecord["ReportIncludeInd"]
	validationStatus: SampleRegisterBaseRecord["ValidationStatus"]
	validationErrors?: SampleRegisterBaseRecord["ValidationErrors"]
	rowStatus: SampleRegisterBaseRecord["RowStatus"]
	supersededById?: SampleRegisterBaseRecord["SupersededById"]
	activeInd: SampleRegisterBaseRecord["ActiveInd"]
	createdOnDt: SampleRegisterBaseRecord["CreatedOnDt"]
	createdBy: SampleRegisterBaseRecord["CreatedBy"]
	modifiedOnDt?: SampleRegisterBaseRecord["ModifiedOnDt"]
	modifiedBy?: SampleRegisterBaseRecord["ModifiedBy"]
	rv: SampleRegisterBaseRecord["rv"]
} {
	return {
		sampleId: data.SampleId,
		organization: data.Organization,
		sampleNm: data.SampleNm,
		sourceTable: data.SourceTable,
		isLab: data.IsLab,
		chkType: data.ChkType,
		attributeGroup: data.AttributeGroup,
		lastDispatchedDt: data.LastDispatchedDt,
		lastLabDispatchId: data.LastLabDispatchId,
		dispatchCount: data.DispatchCount,
		jsonData: data.JsonData,
		dataSource: data.DataSource,
		migrationPreviousNm: data.MigrationPreviousNm,
		reportIncludeInd: data.ReportIncludeInd,
		validationStatus: data.ValidationStatus,
		validationErrors: data.ValidationErrors,
		rowStatus: data.RowStatus,
		supersededById: data.SupersededById,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
	};
}

/**
 * Read schema for the "dbo.SampleRegister" table (after casing transform).
 */
export const SampleRegisterTableSchema = SampleRegisterTableBaseSchema.transform(transformSampleRegisterBaseRecord);

/**
 * Base insert/write schema for the "dbo.SampleRegister" table (no casing transforms).
 */
export const SampleRegisterTableInsertBaseSchema = z.object({
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	sampleId: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	organization: z.string().max(30),
	/**
	 * dataType: nvarchar
	 */
	sampleNm: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	sourceTable: z.string().max(128).nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isLab: z.any().optional(),
	/**
	 * dataType: nvarchar
	 */
	chkType: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	attributeGroup: z.string().max(50).nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	lastDispatchedDt: z.any().nullable().optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	lastLabDispatchId: z.any().nullable().optional(),
	/**
	 * dataType: int
	 * defaultValue: ((0))
	 */
	dispatchCount: z.number().int().optional(),
	/**
	 * dataType: nvarchar
	 */
	jsonData: z.string().max(-1).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	dataSource: z.string().max(255),
	/**
	 * dataType: varchar
	 */
	migrationPreviousNm: z.string().max(50).nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	reportIncludeInd: z.any().optional(),
	/**
	 * dataType: tinyint
	 * defaultValue: ((0))
	 */
	validationStatus: z.number().int().optional(),
	/**
	 * dataType: nvarchar
	 */
	validationErrors: z.string().max(4000).nullable().optional(),
	/**
	 * dataType: tinyint
	 * defaultValue: ((0))
	 */
	rowStatus: z.number().int().optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	supersededById: z.any().nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
});

/**
 * The base record type for the "dbo.SampleRegister" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type SampleRegisterInsertBaseRecord = z.output<typeof SampleRegisterTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.SampleRegister" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type SampleRegisterUpdateBaseRecord = Partial<SampleRegisterInsertBaseRecord>;

/**
 * Insert transform for the "dbo.SampleRegister" table.
 * Maps app cased properties to database fields.
 */
export function transformSampleRegisterInsertBaseRecord(data: SampleRegisterInsertBaseRecord): {
	SampleId?: SampleRegisterInsertBaseRecord["sampleId"]
	Organization: SampleRegisterInsertBaseRecord["organization"]
	SampleNm: SampleRegisterInsertBaseRecord["sampleNm"]
	SourceTable?: SampleRegisterInsertBaseRecord["sourceTable"]
	IsLab?: SampleRegisterInsertBaseRecord["isLab"]
	ChkType?: SampleRegisterInsertBaseRecord["chkType"]
	AttributeGroup?: SampleRegisterInsertBaseRecord["attributeGroup"]
	LastDispatchedDt?: SampleRegisterInsertBaseRecord["lastDispatchedDt"]
	LastLabDispatchId?: SampleRegisterInsertBaseRecord["lastLabDispatchId"]
	DispatchCount?: SampleRegisterInsertBaseRecord["dispatchCount"]
	JsonData?: SampleRegisterInsertBaseRecord["jsonData"]
	DataSource: SampleRegisterInsertBaseRecord["dataSource"]
	MigrationPreviousNm?: SampleRegisterInsertBaseRecord["migrationPreviousNm"]
	ReportIncludeInd?: SampleRegisterInsertBaseRecord["reportIncludeInd"]
	ValidationStatus?: SampleRegisterInsertBaseRecord["validationStatus"]
	ValidationErrors?: SampleRegisterInsertBaseRecord["validationErrors"]
	RowStatus?: SampleRegisterInsertBaseRecord["rowStatus"]
	SupersededById?: SampleRegisterInsertBaseRecord["supersededById"]
	ActiveInd?: SampleRegisterInsertBaseRecord["activeInd"]
	CreatedOnDt?: SampleRegisterInsertBaseRecord["createdOnDt"]
	CreatedBy?: SampleRegisterInsertBaseRecord["createdBy"]
	ModifiedOnDt?: SampleRegisterInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: SampleRegisterInsertBaseRecord["modifiedBy"]
	rv: SampleRegisterInsertBaseRecord["rv"]
} {
	return {
		SampleId: data.sampleId,
		Organization: data.organization,
		SampleNm: data.sampleNm,
		SourceTable: data.sourceTable,
		IsLab: data.isLab,
		ChkType: data.chkType,
		AttributeGroup: data.attributeGroup,
		LastDispatchedDt: data.lastDispatchedDt,
		LastLabDispatchId: data.lastLabDispatchId,
		DispatchCount: data.dispatchCount,
		JsonData: data.jsonData,
		DataSource: data.dataSource,
		MigrationPreviousNm: data.migrationPreviousNm,
		ReportIncludeInd: data.reportIncludeInd,
		ValidationStatus: data.validationStatus,
		ValidationErrors: data.validationErrors,
		RowStatus: data.rowStatus,
		SupersededById: data.supersededById,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Update transform for the "dbo.SampleRegister" table.
 * Maps app cased properties to database fields.
 */
export function transformSampleRegisterUpdateBaseRecord(data: SampleRegisterUpdateBaseRecord): {
	SampleId?: SampleRegisterUpdateBaseRecord["sampleId"]
	Organization: SampleRegisterUpdateBaseRecord["organization"]
	SampleNm: SampleRegisterUpdateBaseRecord["sampleNm"]
	SourceTable?: SampleRegisterUpdateBaseRecord["sourceTable"]
	IsLab?: SampleRegisterUpdateBaseRecord["isLab"]
	ChkType?: SampleRegisterUpdateBaseRecord["chkType"]
	AttributeGroup?: SampleRegisterUpdateBaseRecord["attributeGroup"]
	LastDispatchedDt?: SampleRegisterUpdateBaseRecord["lastDispatchedDt"]
	LastLabDispatchId?: SampleRegisterUpdateBaseRecord["lastLabDispatchId"]
	DispatchCount?: SampleRegisterUpdateBaseRecord["dispatchCount"]
	JsonData?: SampleRegisterUpdateBaseRecord["jsonData"]
	DataSource: SampleRegisterUpdateBaseRecord["dataSource"]
	MigrationPreviousNm?: SampleRegisterUpdateBaseRecord["migrationPreviousNm"]
	ReportIncludeInd?: SampleRegisterUpdateBaseRecord["reportIncludeInd"]
	ValidationStatus?: SampleRegisterUpdateBaseRecord["validationStatus"]
	ValidationErrors?: SampleRegisterUpdateBaseRecord["validationErrors"]
	RowStatus?: SampleRegisterUpdateBaseRecord["rowStatus"]
	SupersededById?: SampleRegisterUpdateBaseRecord["supersededById"]
	ActiveInd?: SampleRegisterUpdateBaseRecord["activeInd"]
	CreatedOnDt?: SampleRegisterUpdateBaseRecord["createdOnDt"]
	CreatedBy?: SampleRegisterUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: SampleRegisterUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: SampleRegisterUpdateBaseRecord["modifiedBy"]
	rv: SampleRegisterUpdateBaseRecord["rv"]
} {
	return {
		SampleId: data.sampleId,
		Organization: data.organization,
		SampleNm: data.sampleNm,
		SourceTable: data.sourceTable,
		IsLab: data.isLab,
		ChkType: data.chkType,
		AttributeGroup: data.attributeGroup,
		LastDispatchedDt: data.lastDispatchedDt,
		LastLabDispatchId: data.lastLabDispatchId,
		DispatchCount: data.dispatchCount,
		JsonData: data.jsonData,
		DataSource: data.dataSource,
		MigrationPreviousNm: data.migrationPreviousNm,
		ReportIncludeInd: data.reportIncludeInd,
		ValidationStatus: data.validationStatus,
		ValidationErrors: data.validationErrors,
		RowStatus: data.rowStatus,
		SupersededById: data.supersededById,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
	};
}

/**
 * Insert schema for the "dbo.SampleRegister" table (after casing transform).
 */
export const SampleRegisterTableInsertSchema = SampleRegisterTableInsertBaseSchema.transform(transformSampleRegisterInsertBaseRecord);

/**
 * Update schema for the "dbo.SampleRegister" table (after casing transform).
 */
export const SampleRegisterTableUpdateSchema = SampleRegisterTableInsertBaseSchema.partial().transform(transformSampleRegisterUpdateBaseRecord);

type TableInsertRecord = z.input<typeof SampleRegisterTableInsertSchema>;
type TableReadRecord = z.output<typeof SampleRegisterTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.SampleRegister" table.
 */
export interface SampleRegisterRecord {
	sampleId: TableReadRecord["sampleId"]
	organization: TableReadRecord["organization"]
	sampleNm: TableReadRecord["sampleNm"]
	sourceTable?: TableReadRecord["sourceTable"]
	isLab: TableReadRecord["isLab"]
	chkType?: TableReadRecord["chkType"]
	attributeGroup?: TableReadRecord["attributeGroup"]
	lastDispatchedDt?: TableReadRecord["lastDispatchedDt"]
	lastLabDispatchId?: TableReadRecord["lastLabDispatchId"]
	dispatchCount: TableReadRecord["dispatchCount"]
	jsonData?: TableReadRecord["jsonData"]
	dataSource: TableReadRecord["dataSource"]
	migrationPreviousNm?: TableReadRecord["migrationPreviousNm"]
	reportIncludeInd: TableReadRecord["reportIncludeInd"]
	validationStatus: TableReadRecord["validationStatus"]
	validationErrors?: TableReadRecord["validationErrors"]
	rowStatus: TableReadRecord["rowStatus"]
	supersededById?: TableReadRecord["supersededById"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
}

/**
 * Insert record (casing transformed) for the "dbo.SampleRegister" table.
 */
export interface SampleRegisterInsertRecord {
	/**
	 * @default: (newid())
	 */
	sampleId?: TableInsertRecord["sampleId"]
	/**
	 * @maxLen: 30
	 */
	organization: TableInsertRecord["organization"]
	/**
	 * @maxLen: 50
	 */
	sampleNm: TableInsertRecord["sampleNm"]
	/**
	 * @maxLen: 128
	 */
	sourceTable?: TableInsertRecord["sourceTable"]
	/**
	 * @default: ((0))
	 */
	isLab?: TableInsertRecord["isLab"]
	/**
	 * @maxLen: 50
	 */
	chkType?: TableInsertRecord["chkType"]
	/**
	 * @maxLen: 50
	 */
	attributeGroup?: TableInsertRecord["attributeGroup"]
	lastDispatchedDt?: TableInsertRecord["lastDispatchedDt"]
	lastLabDispatchId?: TableInsertRecord["lastLabDispatchId"]
	/**
	 * @default: ((0))
	 */
	dispatchCount?: TableInsertRecord["dispatchCount"]
	/**
	 * @maxLen: -1
	 */
	jsonData?: TableInsertRecord["jsonData"]
	/**
	 * @maxLen: 255
	 */
	dataSource: TableInsertRecord["dataSource"]
	/**
	 * @maxLen: 50
	 */
	migrationPreviousNm?: TableInsertRecord["migrationPreviousNm"]
	/**
	 * @default: ((0))
	 */
	reportIncludeInd?: TableInsertRecord["reportIncludeInd"]
	/**
	 * @default: ((0))
	 */
	validationStatus?: TableInsertRecord["validationStatus"]
	/**
	 * @maxLen: 4000
	 */
	validationErrors?: TableInsertRecord["validationErrors"]
	/**
	 * @default: ((0))
	 */
	rowStatus?: TableInsertRecord["rowStatus"]
	supersededById?: TableInsertRecord["supersededById"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
}

/**
 * Updatable record (casing transformed) for the "dbo.SampleRegister" table.
 */
export type SampleRegisterUpdateRecord = Partial<SampleRegisterInsertRecord>;
