// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.User" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const UserTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	UserNm: z.string(),
	/**
	 * dataType: nvarchar
	 */
	DisplayNm: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Email: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	PasswordHash: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	LastLoginDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: int
	 */
	FailedLoginAttempts: z.number(),
	/**
	 * dataType: bit
	 */
	IsLockedInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	LockedUntilDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	MustChangePasswordInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	LastPasswordChangeDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	UserStatus: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Comments: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: uniqueidentifier
	 */
	UserId: z.any(),
});

/**
 * The base record type for the "dbo.User" table.
 * This type represents the raw database record without case transforms.
 */
export type UserBaseRecord = z.output<typeof UserTableBaseSchema>;

/**
 * Read transform for the "dbo.User" table.
 * Maps database fields to app case properties.
 */
export function transformUserBaseRecord(data: UserBaseRecord): {
	userNm: UserBaseRecord["UserNm"]
	displayNm: UserBaseRecord["DisplayNm"]
	email?: UserBaseRecord["Email"]
	passwordHash?: UserBaseRecord["PasswordHash"]
	lastLoginDt?: UserBaseRecord["LastLoginDt"]
	failedLoginAttempts: UserBaseRecord["FailedLoginAttempts"]
	isLockedInd: UserBaseRecord["IsLockedInd"]
	lockedUntilDt?: UserBaseRecord["LockedUntilDt"]
	mustChangePasswordInd: UserBaseRecord["MustChangePasswordInd"]
	lastPasswordChangeDt?: UserBaseRecord["LastPasswordChangeDt"]
	userStatus: UserBaseRecord["UserStatus"]
	comments?: UserBaseRecord["Comments"]
	activeInd: UserBaseRecord["ActiveInd"]
	createdOnDt: UserBaseRecord["CreatedOnDt"]
	createdBy: UserBaseRecord["CreatedBy"]
	modifiedOnDt?: UserBaseRecord["ModifiedOnDt"]
	modifiedBy?: UserBaseRecord["ModifiedBy"]
	userId: UserBaseRecord["UserId"]
} {
	return {
		userNm: data.UserNm,
		displayNm: data.DisplayNm,
		email: data.Email,
		passwordHash: data.PasswordHash,
		lastLoginDt: data.LastLoginDt,
		failedLoginAttempts: data.FailedLoginAttempts,
		isLockedInd: data.IsLockedInd,
		lockedUntilDt: data.LockedUntilDt,
		mustChangePasswordInd: data.MustChangePasswordInd,
		lastPasswordChangeDt: data.LastPasswordChangeDt,
		userStatus: data.UserStatus,
		comments: data.Comments,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		userId: data.UserId,
	};
}

/**
 * Read schema for the "dbo.User" table (after casing transform).
 */
export const UserTableSchema = UserTableBaseSchema.transform(transformUserBaseRecord);

/**
 * Base insert/write schema for the "dbo.User" table (no casing transforms).
 */
export const UserTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	userNm: z.string().max(128),
	/**
	 * dataType: nvarchar
	 */
	displayNm: z.string().max(256),
	/**
	 * dataType: nvarchar
	 */
	email: z.string().max(256).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	passwordHash: z.string().max(100).nullable().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	lastLoginDt: z.any().nullable().optional(),
	/**
	 * dataType: int
	 * defaultValue: ((0))
	 */
	failedLoginAttempts: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isLockedInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	lockedUntilDt: z.any().nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	mustChangePasswordInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 */
	lastPasswordChangeDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	userStatus: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	comments: z.string().max(-1).nullable().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](100),coalesce(session_context(N'UserNm'),suser_sname())))
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	userId: z.any().optional(),
});

/**
 * The base record type for the "dbo.User" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type UserInsertBaseRecord = z.output<typeof UserTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.User" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type UserUpdateBaseRecord = Partial<UserInsertBaseRecord>;

/**
 * Insert transform for the "dbo.User" table.
 * Maps app cased properties to database fields.
 */
export function transformUserInsertBaseRecord(data: UserInsertBaseRecord): {
	UserNm: UserInsertBaseRecord["userNm"]
	DisplayNm: UserInsertBaseRecord["displayNm"]
	Email?: UserInsertBaseRecord["email"]
	PasswordHash?: UserInsertBaseRecord["passwordHash"]
	LastLoginDt?: UserInsertBaseRecord["lastLoginDt"]
	FailedLoginAttempts?: UserInsertBaseRecord["failedLoginAttempts"]
	IsLockedInd?: UserInsertBaseRecord["isLockedInd"]
	LockedUntilDt?: UserInsertBaseRecord["lockedUntilDt"]
	MustChangePasswordInd?: UserInsertBaseRecord["mustChangePasswordInd"]
	LastPasswordChangeDt?: UserInsertBaseRecord["lastPasswordChangeDt"]
	UserStatus: UserInsertBaseRecord["userStatus"]
	Comments?: UserInsertBaseRecord["comments"]
	ActiveInd?: UserInsertBaseRecord["activeInd"]
	CreatedOnDt?: UserInsertBaseRecord["createdOnDt"]
	CreatedBy?: UserInsertBaseRecord["createdBy"]
	ModifiedOnDt?: UserInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: UserInsertBaseRecord["modifiedBy"]
	UserId?: UserInsertBaseRecord["userId"]
} {
	return {
		UserNm: data.userNm,
		DisplayNm: data.displayNm,
		Email: data.email,
		PasswordHash: data.passwordHash,
		LastLoginDt: data.lastLoginDt,
		FailedLoginAttempts: data.failedLoginAttempts,
		IsLockedInd: data.isLockedInd,
		LockedUntilDt: data.lockedUntilDt,
		MustChangePasswordInd: data.mustChangePasswordInd,
		LastPasswordChangeDt: data.lastPasswordChangeDt,
		UserStatus: data.userStatus,
		Comments: data.comments,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		UserId: data.userId,
	};
}

/**
 * Update transform for the "dbo.User" table.
 * Maps app cased properties to database fields.
 */
export function transformUserUpdateBaseRecord(data: UserUpdateBaseRecord): {
	UserNm: UserUpdateBaseRecord["userNm"]
	DisplayNm: UserUpdateBaseRecord["displayNm"]
	Email?: UserUpdateBaseRecord["email"]
	PasswordHash?: UserUpdateBaseRecord["passwordHash"]
	LastLoginDt?: UserUpdateBaseRecord["lastLoginDt"]
	FailedLoginAttempts?: UserUpdateBaseRecord["failedLoginAttempts"]
	IsLockedInd?: UserUpdateBaseRecord["isLockedInd"]
	LockedUntilDt?: UserUpdateBaseRecord["lockedUntilDt"]
	MustChangePasswordInd?: UserUpdateBaseRecord["mustChangePasswordInd"]
	LastPasswordChangeDt?: UserUpdateBaseRecord["lastPasswordChangeDt"]
	UserStatus: UserUpdateBaseRecord["userStatus"]
	Comments?: UserUpdateBaseRecord["comments"]
	ActiveInd?: UserUpdateBaseRecord["activeInd"]
	CreatedOnDt?: UserUpdateBaseRecord["createdOnDt"]
	CreatedBy?: UserUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: UserUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: UserUpdateBaseRecord["modifiedBy"]
	UserId?: UserUpdateBaseRecord["userId"]
} {
	return {
		UserNm: data.userNm,
		DisplayNm: data.displayNm,
		Email: data.email,
		PasswordHash: data.passwordHash,
		LastLoginDt: data.lastLoginDt,
		FailedLoginAttempts: data.failedLoginAttempts,
		IsLockedInd: data.isLockedInd,
		LockedUntilDt: data.lockedUntilDt,
		MustChangePasswordInd: data.mustChangePasswordInd,
		LastPasswordChangeDt: data.lastPasswordChangeDt,
		UserStatus: data.userStatus,
		Comments: data.comments,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		UserId: data.userId,
	};
}

/**
 * Insert schema for the "dbo.User" table (after casing transform).
 */
export const UserTableInsertSchema = UserTableInsertBaseSchema.transform(transformUserInsertBaseRecord);

/**
 * Update schema for the "dbo.User" table (after casing transform).
 */
export const UserTableUpdateSchema = UserTableInsertBaseSchema.partial().transform(transformUserUpdateBaseRecord);

type TableInsertRecord = z.input<typeof UserTableInsertSchema>;
type TableReadRecord = z.output<typeof UserTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.User" table.
 */
export interface UserRecord {
	userNm: TableReadRecord["userNm"]
	displayNm: TableReadRecord["displayNm"]
	email?: TableReadRecord["email"]
	passwordHash?: TableReadRecord["passwordHash"]
	lastLoginDt?: TableReadRecord["lastLoginDt"]
	failedLoginAttempts: TableReadRecord["failedLoginAttempts"]
	isLockedInd: TableReadRecord["isLockedInd"]
	lockedUntilDt?: TableReadRecord["lockedUntilDt"]
	mustChangePasswordInd: TableReadRecord["mustChangePasswordInd"]
	lastPasswordChangeDt?: TableReadRecord["lastPasswordChangeDt"]
	userStatus: TableReadRecord["userStatus"]
	comments?: TableReadRecord["comments"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	userId: TableReadRecord["userId"]
}

/**
 * Insert record (casing transformed) for the "dbo.User" table.
 */
export interface UserInsertRecord {
	/**
	 * @maxLen: 128
	 */
	userNm: TableInsertRecord["userNm"]
	/**
	 * @maxLen: 256
	 */
	displayNm: TableInsertRecord["displayNm"]
	/**
	 * @maxLen: 256
	 */
	email?: TableInsertRecord["email"]
	/**
	 * @maxLen: 100
	 */
	passwordHash?: TableInsertRecord["passwordHash"]
	lastLoginDt?: TableInsertRecord["lastLoginDt"]
	/**
	 * @default: ((0))
	 */
	failedLoginAttempts?: TableInsertRecord["failedLoginAttempts"]
	/**
	 * @default: ((0))
	 */
	isLockedInd?: TableInsertRecord["isLockedInd"]
	lockedUntilDt?: TableInsertRecord["lockedUntilDt"]
	/**
	 * @default: ((1))
	 */
	mustChangePasswordInd?: TableInsertRecord["mustChangePasswordInd"]
	lastPasswordChangeDt?: TableInsertRecord["lastPasswordChangeDt"]
	/**
	 * @maxLen: 50
	 */
	userStatus: TableInsertRecord["userStatus"]
	/**
	 * @maxLen: -1
	 */
	comments?: TableInsertRecord["comments"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](100),coalesce(session_context(N'UserNm'),suser_sname())))
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	/**
	 * @default: (newid())
	 */
	userId?: TableInsertRecord["userId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.User" table.
 */
export type UserUpdateRecord = Partial<UserInsertRecord>;
