// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.TaskStatus" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const TaskStatusTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	TaskStatusId: z.any(),
});

/**
 * The base record type for the "dbo.TaskStatus" table.
 * This type represents the raw database record without case transforms.
 */
export type TaskStatusBaseRecord = z.output<typeof TaskStatusTableBaseSchema>;

/**
 * Read transform for the "dbo.TaskStatus" table.
 * Maps database fields to app case properties.
 */
export function transformTaskStatusBaseRecord(data: TaskStatusBaseRecord): {
	code: TaskStatusBaseRecord["Code"]
	description: TaskStatusBaseRecord["Description"]
	sortOrder: TaskStatusBaseRecord["SortOrder"]
	isDefaultInd: TaskStatusBaseRecord["IsDefaultInd"]
	activeInd: TaskStatusBaseRecord["ActiveInd"]
	createdOnDt: TaskStatusBaseRecord["CreatedOnDt"]
	createdBy: TaskStatusBaseRecord["CreatedBy"]
	modifiedOnDt?: TaskStatusBaseRecord["ModifiedOnDt"]
	modifiedBy?: TaskStatusBaseRecord["ModifiedBy"]
	rv: TaskStatusBaseRecord["rv"]
	taskStatusId: TaskStatusBaseRecord["TaskStatusId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		taskStatusId: data.TaskStatusId,
	};
}

/**
 * Read schema for the "dbo.TaskStatus" table (after casing transform).
 */
export const TaskStatusTableSchema = TaskStatusTableBaseSchema.transform(transformTaskStatusBaseRecord);

/**
 * Base insert/write schema for the "dbo.TaskStatus" table (no casing transforms).
 */
export const TaskStatusTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	taskStatusId: z.any().optional(),
});

/**
 * The base record type for the "dbo.TaskStatus" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type TaskStatusInsertBaseRecord = z.output<typeof TaskStatusTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.TaskStatus" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type TaskStatusUpdateBaseRecord = Partial<TaskStatusInsertBaseRecord>;

/**
 * Insert transform for the "dbo.TaskStatus" table.
 * Maps app cased properties to database fields.
 */
export function transformTaskStatusInsertBaseRecord(data: TaskStatusInsertBaseRecord): {
	Code: TaskStatusInsertBaseRecord["code"]
	Description: TaskStatusInsertBaseRecord["description"]
	SortOrder?: TaskStatusInsertBaseRecord["sortOrder"]
	IsDefaultInd?: TaskStatusInsertBaseRecord["isDefaultInd"]
	ActiveInd?: TaskStatusInsertBaseRecord["activeInd"]
	CreatedOnDt?: TaskStatusInsertBaseRecord["createdOnDt"]
	CreatedBy?: TaskStatusInsertBaseRecord["createdBy"]
	ModifiedOnDt?: TaskStatusInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: TaskStatusInsertBaseRecord["modifiedBy"]
	rv: TaskStatusInsertBaseRecord["rv"]
	TaskStatusId?: TaskStatusInsertBaseRecord["taskStatusId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		TaskStatusId: data.taskStatusId,
	};
}

/**
 * Update transform for the "dbo.TaskStatus" table.
 * Maps app cased properties to database fields.
 */
export function transformTaskStatusUpdateBaseRecord(data: TaskStatusUpdateBaseRecord): {
	Code: TaskStatusUpdateBaseRecord["code"]
	Description: TaskStatusUpdateBaseRecord["description"]
	SortOrder?: TaskStatusUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: TaskStatusUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: TaskStatusUpdateBaseRecord["activeInd"]
	CreatedOnDt?: TaskStatusUpdateBaseRecord["createdOnDt"]
	CreatedBy?: TaskStatusUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: TaskStatusUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: TaskStatusUpdateBaseRecord["modifiedBy"]
	rv: TaskStatusUpdateBaseRecord["rv"]
	TaskStatusId?: TaskStatusUpdateBaseRecord["taskStatusId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		TaskStatusId: data.taskStatusId,
	};
}

/**
 * Insert schema for the "dbo.TaskStatus" table (after casing transform).
 */
export const TaskStatusTableInsertSchema = TaskStatusTableInsertBaseSchema.transform(transformTaskStatusInsertBaseRecord);

/**
 * Update schema for the "dbo.TaskStatus" table (after casing transform).
 */
export const TaskStatusTableUpdateSchema = TaskStatusTableInsertBaseSchema.partial().transform(transformTaskStatusUpdateBaseRecord);

type TableInsertRecord = z.input<typeof TaskStatusTableInsertSchema>;
type TableReadRecord = z.output<typeof TaskStatusTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.TaskStatus" table.
 */
export interface TaskStatusRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	taskStatusId: TableReadRecord["taskStatusId"]
}

/**
 * Insert record (casing transformed) for the "dbo.TaskStatus" table.
 */
export interface TaskStatusInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	taskStatusId?: TableInsertRecord["taskStatusId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.TaskStatus" table.
 */
export type TaskStatusUpdateRecord = Partial<TaskStatusInsertRecord>;
