// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.ProgramCode" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const ProgramCodeTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: nvarchar
	 */
	DefaultProgramType: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ExampleFormat: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	ProgramCodeId: z.any(),
});

/**
 * The base record type for the "dbo.ProgramCode" table.
 * This type represents the raw database record without case transforms.
 */
export type ProgramCodeBaseRecord = z.output<typeof ProgramCodeTableBaseSchema>;

/**
 * Read transform for the "dbo.ProgramCode" table.
 * Maps database fields to app case properties.
 */
export function transformProgramCodeBaseRecord(data: ProgramCodeBaseRecord): {
	code: ProgramCodeBaseRecord["Code"]
	description: ProgramCodeBaseRecord["Description"]
	defaultProgramType?: ProgramCodeBaseRecord["DefaultProgramType"]
	exampleFormat: ProgramCodeBaseRecord["ExampleFormat"]
	sortOrder: ProgramCodeBaseRecord["SortOrder"]
	isDefaultInd: ProgramCodeBaseRecord["IsDefaultInd"]
	activeInd: ProgramCodeBaseRecord["ActiveInd"]
	createdOnDt: ProgramCodeBaseRecord["CreatedOnDt"]
	createdBy: ProgramCodeBaseRecord["CreatedBy"]
	modifiedOnDt?: ProgramCodeBaseRecord["ModifiedOnDt"]
	modifiedBy?: ProgramCodeBaseRecord["ModifiedBy"]
	rv: ProgramCodeBaseRecord["rv"]
	programCodeId: ProgramCodeBaseRecord["ProgramCodeId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		defaultProgramType: data.DefaultProgramType,
		exampleFormat: data.ExampleFormat,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		programCodeId: data.ProgramCodeId,
	};
}

/**
 * Read schema for the "dbo.ProgramCode" table (after casing transform).
 */
export const ProgramCodeTableSchema = ProgramCodeTableBaseSchema.transform(transformProgramCodeBaseRecord);

/**
 * Base insert/write schema for the "dbo.ProgramCode" table (no casing transforms).
 */
export const ProgramCodeTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: nvarchar
	 */
	defaultProgramType: z.string().max(50).nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	exampleFormat: z.string().max(50),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	programCodeId: z.any().optional(),
});

/**
 * The base record type for the "dbo.ProgramCode" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type ProgramCodeInsertBaseRecord = z.output<typeof ProgramCodeTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.ProgramCode" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type ProgramCodeUpdateBaseRecord = Partial<ProgramCodeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.ProgramCode" table.
 * Maps app cased properties to database fields.
 */
export function transformProgramCodeInsertBaseRecord(data: ProgramCodeInsertBaseRecord): {
	Code: ProgramCodeInsertBaseRecord["code"]
	Description: ProgramCodeInsertBaseRecord["description"]
	DefaultProgramType?: ProgramCodeInsertBaseRecord["defaultProgramType"]
	ExampleFormat: ProgramCodeInsertBaseRecord["exampleFormat"]
	SortOrder?: ProgramCodeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: ProgramCodeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: ProgramCodeInsertBaseRecord["activeInd"]
	CreatedOnDt?: ProgramCodeInsertBaseRecord["createdOnDt"]
	CreatedBy?: ProgramCodeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: ProgramCodeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: ProgramCodeInsertBaseRecord["modifiedBy"]
	rv: ProgramCodeInsertBaseRecord["rv"]
	ProgramCodeId?: ProgramCodeInsertBaseRecord["programCodeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		DefaultProgramType: data.defaultProgramType,
		ExampleFormat: data.exampleFormat,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		ProgramCodeId: data.programCodeId,
	};
}

/**
 * Update transform for the "dbo.ProgramCode" table.
 * Maps app cased properties to database fields.
 */
export function transformProgramCodeUpdateBaseRecord(data: ProgramCodeUpdateBaseRecord): {
	Code: ProgramCodeUpdateBaseRecord["code"]
	Description: ProgramCodeUpdateBaseRecord["description"]
	DefaultProgramType?: ProgramCodeUpdateBaseRecord["defaultProgramType"]
	ExampleFormat: ProgramCodeUpdateBaseRecord["exampleFormat"]
	SortOrder?: ProgramCodeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: ProgramCodeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: ProgramCodeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: ProgramCodeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: ProgramCodeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: ProgramCodeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: ProgramCodeUpdateBaseRecord["modifiedBy"]
	rv: ProgramCodeUpdateBaseRecord["rv"]
	ProgramCodeId?: ProgramCodeUpdateBaseRecord["programCodeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		DefaultProgramType: data.defaultProgramType,
		ExampleFormat: data.exampleFormat,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		ProgramCodeId: data.programCodeId,
	};
}

/**
 * Insert schema for the "dbo.ProgramCode" table (after casing transform).
 */
export const ProgramCodeTableInsertSchema = ProgramCodeTableInsertBaseSchema.transform(transformProgramCodeInsertBaseRecord);

/**
 * Update schema for the "dbo.ProgramCode" table (after casing transform).
 */
export const ProgramCodeTableUpdateSchema = ProgramCodeTableInsertBaseSchema.partial().transform(transformProgramCodeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof ProgramCodeTableInsertSchema>;
type TableReadRecord = z.output<typeof ProgramCodeTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.ProgramCode" table.
 */
export interface ProgramCodeRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	defaultProgramType?: TableReadRecord["defaultProgramType"]
	exampleFormat: TableReadRecord["exampleFormat"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	programCodeId: TableReadRecord["programCodeId"]
}

/**
 * Insert record (casing transformed) for the "dbo.ProgramCode" table.
 */
export interface ProgramCodeInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @maxLen: 50
	 */
	defaultProgramType?: TableInsertRecord["defaultProgramType"]
	/**
	 * @maxLen: 50
	 */
	exampleFormat: TableInsertRecord["exampleFormat"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (CONVERT([nvarchar](50),coalesce(session_context(N'UserName'),suser_sname())))
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	programCodeId?: TableInsertRecord["programCodeId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.ProgramCode" table.
 */
export type ProgramCodeUpdateRecord = Partial<ProgramCodeInsertRecord>;
