// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.Region" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const RegionTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	RegionId: z.any(),
});

/**
 * The base record type for the "dbo.Region" table.
 * This type represents the raw database record without case transforms.
 */
export type RegionBaseRecord = z.output<typeof RegionTableBaseSchema>;

/**
 * Read transform for the "dbo.Region" table.
 * Maps database fields to app case properties.
 */
export function transformRegionBaseRecord(data: RegionBaseRecord): {
	code: RegionBaseRecord["Code"]
	description: RegionBaseRecord["Description"]
	sortOrder: RegionBaseRecord["SortOrder"]
	isDefaultInd: RegionBaseRecord["IsDefaultInd"]
	activeInd: RegionBaseRecord["ActiveInd"]
	createdOnDt: RegionBaseRecord["CreatedOnDt"]
	createdBy: RegionBaseRecord["CreatedBy"]
	modifiedOnDt?: RegionBaseRecord["ModifiedOnDt"]
	modifiedBy?: RegionBaseRecord["ModifiedBy"]
	rv: RegionBaseRecord["rv"]
	regionId: RegionBaseRecord["RegionId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		regionId: data.RegionId,
	};
}

/**
 * Read schema for the "dbo.Region" table (after casing transform).
 */
export const RegionTableSchema = RegionTableBaseSchema.transform(transformRegionBaseRecord);

/**
 * Base insert/write schema for the "dbo.Region" table (no casing transforms).
 */
export const RegionTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	regionId: z.any().optional(),
});

/**
 * The base record type for the "dbo.Region" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type RegionInsertBaseRecord = z.output<typeof RegionTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.Region" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type RegionUpdateBaseRecord = Partial<RegionInsertBaseRecord>;

/**
 * Insert transform for the "dbo.Region" table.
 * Maps app cased properties to database fields.
 */
export function transformRegionInsertBaseRecord(data: RegionInsertBaseRecord): {
	Code: RegionInsertBaseRecord["code"]
	Description: RegionInsertBaseRecord["description"]
	SortOrder?: RegionInsertBaseRecord["sortOrder"]
	IsDefaultInd?: RegionInsertBaseRecord["isDefaultInd"]
	ActiveInd?: RegionInsertBaseRecord["activeInd"]
	CreatedOnDt?: RegionInsertBaseRecord["createdOnDt"]
	CreatedBy?: RegionInsertBaseRecord["createdBy"]
	ModifiedOnDt?: RegionInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: RegionInsertBaseRecord["modifiedBy"]
	rv: RegionInsertBaseRecord["rv"]
	RegionId?: RegionInsertBaseRecord["regionId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		RegionId: data.regionId,
	};
}

/**
 * Update transform for the "dbo.Region" table.
 * Maps app cased properties to database fields.
 */
export function transformRegionUpdateBaseRecord(data: RegionUpdateBaseRecord): {
	Code: RegionUpdateBaseRecord["code"]
	Description: RegionUpdateBaseRecord["description"]
	SortOrder?: RegionUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: RegionUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: RegionUpdateBaseRecord["activeInd"]
	CreatedOnDt?: RegionUpdateBaseRecord["createdOnDt"]
	CreatedBy?: RegionUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: RegionUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: RegionUpdateBaseRecord["modifiedBy"]
	rv: RegionUpdateBaseRecord["rv"]
	RegionId?: RegionUpdateBaseRecord["regionId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		RegionId: data.regionId,
	};
}

/**
 * Insert schema for the "dbo.Region" table (after casing transform).
 */
export const RegionTableInsertSchema = RegionTableInsertBaseSchema.transform(transformRegionInsertBaseRecord);

/**
 * Update schema for the "dbo.Region" table (after casing transform).
 */
export const RegionTableUpdateSchema = RegionTableInsertBaseSchema.partial().transform(transformRegionUpdateBaseRecord);

type TableInsertRecord = z.input<typeof RegionTableInsertSchema>;
type TableReadRecord = z.output<typeof RegionTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.Region" table.
 */
export interface RegionRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	regionId: TableReadRecord["regionId"]
}

/**
 * Insert record (casing transformed) for the "dbo.Region" table.
 */
export interface RegionInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	regionId?: TableInsertRecord["regionId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.Region" table.
 */
export type RegionUpdateRecord = Partial<RegionInsertRecord>;
