// This file is auto-generated by zod-dbs. Do not edit this file directly.

import { z } from "zod";

/**
 * Base read schema for the "dbo.LoggingEventType" table.
 * Validates raw rows read from the database (no casing transforms applied yet).
 */
export const LoggingEventTypeTableBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	Code: z.string(),
	/**
	 * dataType: nvarchar
	 */
	Description: z.string(),
	/**
	 * dataType: smallint
	 */
	SortOrder: z.number(),
	/**
	 * dataType: bit
	 */
	IsDefaultInd: z.any(),
	/**
	 * dataType: bit
	 */
	ActiveInd: z.any(),
	/**
	 * dataType: datetimeoffset
	 */
	CreatedOnDt: z.any(),
	/**
	 * dataType: nvarchar
	 */
	CreatedBy: z.string(),
	/**
	 * dataType: datetimeoffset
	 */
	ModifiedOnDt: z.any().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: nvarchar
	 */
	ModifiedBy: z.string().nullable().transform(value => value ?? undefined).optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.coerce.date(),
	/**
	 * dataType: uniqueidentifier
	 */
	LoggingEventTypeId: z.any(),
});

/**
 * The base record type for the "dbo.LoggingEventType" table.
 * This type represents the raw database record without case transforms.
 */
export type LoggingEventTypeBaseRecord = z.output<typeof LoggingEventTypeTableBaseSchema>;

/**
 * Read transform for the "dbo.LoggingEventType" table.
 * Maps database fields to app case properties.
 */
export function transformLoggingEventTypeBaseRecord(data: LoggingEventTypeBaseRecord): {
	code: LoggingEventTypeBaseRecord["Code"]
	description: LoggingEventTypeBaseRecord["Description"]
	sortOrder: LoggingEventTypeBaseRecord["SortOrder"]
	isDefaultInd: LoggingEventTypeBaseRecord["IsDefaultInd"]
	activeInd: LoggingEventTypeBaseRecord["ActiveInd"]
	createdOnDt: LoggingEventTypeBaseRecord["CreatedOnDt"]
	createdBy: LoggingEventTypeBaseRecord["CreatedBy"]
	modifiedOnDt?: LoggingEventTypeBaseRecord["ModifiedOnDt"]
	modifiedBy?: LoggingEventTypeBaseRecord["ModifiedBy"]
	rv: LoggingEventTypeBaseRecord["rv"]
	loggingEventTypeId: LoggingEventTypeBaseRecord["LoggingEventTypeId"]
} {
	return {
		code: data.Code,
		description: data.Description,
		sortOrder: data.SortOrder,
		isDefaultInd: data.IsDefaultInd,
		activeInd: data.ActiveInd,
		createdOnDt: data.CreatedOnDt,
		createdBy: data.CreatedBy,
		modifiedOnDt: data.ModifiedOnDt,
		modifiedBy: data.ModifiedBy,
		rv: data.rv,
		loggingEventTypeId: data.LoggingEventTypeId,
	};
}

/**
 * Read schema for the "dbo.LoggingEventType" table (after casing transform).
 */
export const LoggingEventTypeTableSchema = LoggingEventTypeTableBaseSchema.transform(transformLoggingEventTypeBaseRecord);

/**
 * Base insert/write schema for the "dbo.LoggingEventType" table (no casing transforms).
 */
export const LoggingEventTypeTableInsertBaseSchema = z.object({
	/**
	 * dataType: nvarchar
	 */
	code: z.string().max(50),
	/**
	 * dataType: nvarchar
	 */
	description: z.string().max(1000),
	/**
	 * dataType: smallint
	 * defaultValue: ((0))
	 */
	sortOrder: z.number().int().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((0))
	 */
	isDefaultInd: z.any().optional(),
	/**
	 * dataType: bit
	 * defaultValue: ((1))
	 */
	activeInd: z.any().optional(),
	/**
	 * dataType: datetimeoffset
	 * defaultValue: (sysdatetimeoffset())
	 */
	createdOnDt: z.any().optional(),
	/**
	 * dataType: nvarchar
	 * defaultValue: (suser_sname())
	 */
	createdBy: z.string().max(50).optional(),
	/**
	 * dataType: datetimeoffset
	 */
	modifiedOnDt: z.any().nullable().optional(),
	/**
	 * dataType: nvarchar
	 */
	modifiedBy: z.string().max(50).nullable().optional(),
	/**
	 * dataType: timestamp
	 */
	rv: z.date(),
	/**
	 * dataType: uniqueidentifier
	 * defaultValue: (newid())
	 */
	loggingEventTypeId: z.any().optional(),
});

/**
 * The base record type for the "dbo.LoggingEventType" table.
 * This type represents an insertable database record before casing transformations are applied.
 */
export type LoggingEventTypeInsertBaseRecord = z.output<typeof LoggingEventTypeTableInsertBaseSchema>;

/**
 * The base record type for the "dbo.LoggingEventType" table.
 * This type represents an updatable database record before casing transformations are applied.
 */
export type LoggingEventTypeUpdateBaseRecord = Partial<LoggingEventTypeInsertBaseRecord>;

/**
 * Insert transform for the "dbo.LoggingEventType" table.
 * Maps app cased properties to database fields.
 */
export function transformLoggingEventTypeInsertBaseRecord(data: LoggingEventTypeInsertBaseRecord): {
	Code: LoggingEventTypeInsertBaseRecord["code"]
	Description: LoggingEventTypeInsertBaseRecord["description"]
	SortOrder?: LoggingEventTypeInsertBaseRecord["sortOrder"]
	IsDefaultInd?: LoggingEventTypeInsertBaseRecord["isDefaultInd"]
	ActiveInd?: LoggingEventTypeInsertBaseRecord["activeInd"]
	CreatedOnDt?: LoggingEventTypeInsertBaseRecord["createdOnDt"]
	CreatedBy?: LoggingEventTypeInsertBaseRecord["createdBy"]
	ModifiedOnDt?: LoggingEventTypeInsertBaseRecord["modifiedOnDt"]
	ModifiedBy?: LoggingEventTypeInsertBaseRecord["modifiedBy"]
	rv: LoggingEventTypeInsertBaseRecord["rv"]
	LoggingEventTypeId?: LoggingEventTypeInsertBaseRecord["loggingEventTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		LoggingEventTypeId: data.loggingEventTypeId,
	};
}

/**
 * Update transform for the "dbo.LoggingEventType" table.
 * Maps app cased properties to database fields.
 */
export function transformLoggingEventTypeUpdateBaseRecord(data: LoggingEventTypeUpdateBaseRecord): {
	Code: LoggingEventTypeUpdateBaseRecord["code"]
	Description: LoggingEventTypeUpdateBaseRecord["description"]
	SortOrder?: LoggingEventTypeUpdateBaseRecord["sortOrder"]
	IsDefaultInd?: LoggingEventTypeUpdateBaseRecord["isDefaultInd"]
	ActiveInd?: LoggingEventTypeUpdateBaseRecord["activeInd"]
	CreatedOnDt?: LoggingEventTypeUpdateBaseRecord["createdOnDt"]
	CreatedBy?: LoggingEventTypeUpdateBaseRecord["createdBy"]
	ModifiedOnDt?: LoggingEventTypeUpdateBaseRecord["modifiedOnDt"]
	ModifiedBy?: LoggingEventTypeUpdateBaseRecord["modifiedBy"]
	rv: LoggingEventTypeUpdateBaseRecord["rv"]
	LoggingEventTypeId?: LoggingEventTypeUpdateBaseRecord["loggingEventTypeId"]
} {
	return {
		Code: data.code,
		Description: data.description,
		SortOrder: data.sortOrder,
		IsDefaultInd: data.isDefaultInd,
		ActiveInd: data.activeInd,
		CreatedOnDt: data.createdOnDt,
		CreatedBy: data.createdBy,
		ModifiedOnDt: data.modifiedOnDt,
		ModifiedBy: data.modifiedBy,
		rv: data.rv,
		LoggingEventTypeId: data.loggingEventTypeId,
	};
}

/**
 * Insert schema for the "dbo.LoggingEventType" table (after casing transform).
 */
export const LoggingEventTypeTableInsertSchema = LoggingEventTypeTableInsertBaseSchema.transform(transformLoggingEventTypeInsertBaseRecord);

/**
 * Update schema for the "dbo.LoggingEventType" table (after casing transform).
 */
export const LoggingEventTypeTableUpdateSchema = LoggingEventTypeTableInsertBaseSchema.partial().transform(transformLoggingEventTypeUpdateBaseRecord);

type TableInsertRecord = z.input<typeof LoggingEventTypeTableInsertSchema>;
type TableReadRecord = z.output<typeof LoggingEventTypeTableSchema>;

/**
 * Read record (casing transformed) for the "dbo.LoggingEventType" table.
 */
export interface LoggingEventTypeRecord {
	code: TableReadRecord["code"]
	description: TableReadRecord["description"]
	sortOrder: TableReadRecord["sortOrder"]
	isDefaultInd: TableReadRecord["isDefaultInd"]
	activeInd: TableReadRecord["activeInd"]
	createdOnDt: TableReadRecord["createdOnDt"]
	createdBy: TableReadRecord["createdBy"]
	modifiedOnDt?: TableReadRecord["modifiedOnDt"]
	modifiedBy?: TableReadRecord["modifiedBy"]
	rv: TableReadRecord["rv"]
	loggingEventTypeId: TableReadRecord["loggingEventTypeId"]
}

/**
 * Insert record (casing transformed) for the "dbo.LoggingEventType" table.
 */
export interface LoggingEventTypeInsertRecord {
	/**
	 * @maxLen: 50
	 */
	code: TableInsertRecord["code"]
	/**
	 * @maxLen: 1000
	 */
	description: TableInsertRecord["description"]
	/**
	 * @default: ((0))
	 */
	sortOrder?: TableInsertRecord["sortOrder"]
	/**
	 * @default: ((0))
	 */
	isDefaultInd?: TableInsertRecord["isDefaultInd"]
	/**
	 * @default: ((1))
	 */
	activeInd?: TableInsertRecord["activeInd"]
	/**
	 * @default: (sysdatetimeoffset())
	 */
	createdOnDt?: TableInsertRecord["createdOnDt"]
	/**
	 * @maxLen: 50
	 * @default: (suser_sname())
	 */
	createdBy?: TableInsertRecord["createdBy"]
	modifiedOnDt?: TableInsertRecord["modifiedOnDt"]
	/**
	 * @maxLen: 50
	 */
	modifiedBy?: TableInsertRecord["modifiedBy"]
	rv: TableInsertRecord["rv"]
	/**
	 * @default: (newid())
	 */
	loggingEventTypeId?: TableInsertRecord["loggingEventTypeId"]
}

/**
 * Updatable record (casing transformed) for the "dbo.LoggingEventType" table.
 */
export type LoggingEventTypeUpdateRecord = Partial<LoggingEventTypeInsertRecord>;
